Inventory: Inventory Class Reference
Inventory Class Reference
Public Member Functions
__construct ($host, $user, $pass, $database, $pref_tablename)
install ()
create_inventory_count_table ()
handlePOST ()
write ()
process_inventory ()
submenu_choices ()
check_edit_conflicts ()
copy_from_session ()
copy_to_session ()
line_start_focus ()
can_process ()
check_item_data ()
handle_update_item ()
handle_delete_item ($line_no)
isStockid ($stock_id)
isItemCode ($item_code)
inItemCode ($item_code)
get_item_description ()
add_item ()
find_cart_item ()
handle_new_item ()
handle_cancel_inventory ()
create_cart ()
create_location_scancode_table ()
hasBarcode ()
haslocation ()
islocationCode ($upc)
display_inventory_header ($hidden_action="")
upc_table ()
scan_form ()
get_item_qoh_location ($stock_id)
get_items_qoh_location ()
call_table ($action, $msg)
xfer_all_to_location ()
xfer_all_to_holding ()
xfer_all_settings ($action)
add_all_list ($action="zero")
xfer_all_to_holding_form ()
xfer_all_to_location_form ()
xferall_form ()
overunder_form ()
Inventory_form ()
EXPORT_CSV_form ()
config_form ()
handle_new_inventory ()
init_tables_form ()
init_tables_completed_form ()
create_table_inventory_last_performed ()
record_last_inv_date ($stock_id)
process ()
process_form ()
display_adjustment_items ($title, $doEdit=TRUE, $showStock=FALSE, $action="inventory")
display_inventory_summary ($title, &$inventory, $editable_items=false)
adjustment_edit_item_controls ($line_no=-1)
adjustment_options_controls ()
table_memo_field ()
processing_start ()
processing_end ()
confirm_dialog ($submit, $msg)
page_processing ($msg=false)
page_modified ($status=true)
Public Member Functions inherited from generic_interface
__construct ($host, $user, $pass, $database, $prefs_tablename)
related_tabs ()
show_form ()
base_page ()
display ()
run ()
append_file ($filename)
overwrite_file ($filename)
close_file ($fp)
Public Member Functions inherited from db_base
__construct ($prefs_tablename)
set_var ($var, $value)
get_var ($var)
is_installed ()
set_prefix ()
create_prefs_tablename ()
set_pref ($pref, $value)
get_pref ($pref)
loadprefs ()
updateprefs ()
Data Fields
$mailto
$email_subject
email subject line. Not currently implemented.
$email_body
$csv_filename
$pretty_filename
$location
$holdtank
$to_location
$from_location
$url
$trans_type
$trans_no
$barcode
$locationPrefix
$locationPrefix2
$line_items
$reference
$Comments
$document_date
$ex_rate
$deliver_to
$delivery_address
$copyfromcount
$copytocount
$title
$path_to_root
$update_quantity
$add_quantity
$item_text
$stock_id
$change_line_number
$table_interface
Data Fields inherited from generic_interface
$errors
$javascript
$help_context
$page_title
Data Fields inherited from db_base
$action
$dbHost
$dbUser
$dbPassword
$dbName
$db_connection
$prefs_tablename
$company_prefix
$config_values = array()
Detailed Description
Definition at line 80 of file class.Inventory.php.
Constructor & Destructor Documentation
__construct()
__construct ($host, $user, $pass, $database, $pref_tablename)
Definition at line 121 of file class.Inventory.php.
References $path_to_root, create_cart(), handlePOST(), and db_base\set_var().
Member Function Documentation
add_all_list()
add_all_list ($action = "zero")
Definition at line 1091 of file class.Inventory.php.
References db_base\$action, add_item(), and db_base\set_var().
Referenced by xfer_all_settings().
add_item()
add_item ()
Definition at line 665 of file class.Inventory.php.
References $add_quantity, $barcode, $item_text, $stock_id, copy_to_session(), find_cart_item(), get_item_description(), isItemCode(), and isStockid().
Referenced by add_all_list(), handle_new_item(), and scan_form().
adjustment_edit_item_controls()
adjustment_edit_item_controls ($line_no = -1)
Definition at line 1652 of file class.Inventory.php.
References $id.
Referenced by display_adjustment_items(), and display_inventory_summary().
adjustment_options_controls()
adjustment_options_controls ()
Definition at line 1740 of file class.Inventory.php.
Referenced by Inventory_form().
call_table()
call_table ($action, $msg)
Definition at line 1039 of file class.Inventory.php.
References db_base\$action.
Referenced by init_tables_form(), xfer_all_to_holding_form(), and xfer_all_to_location_form().
can_process()
can_process ()
Definition at line 498 of file class.Inventory.php.
Referenced by process_form().
check_edit_conflicts()
check_edit_conflicts ()
Definition at line 347 of file class.Inventory.php.
Referenced by submenu_choices().
check_item_data()
check_item_data ()
Definition at line 551 of file class.Inventory.php.
config_form()
config_form ()
Definition at line 1312 of file class.Inventory.php.
confirm_dialog()
confirm_dialog ($submit, $msg)
Definition at line 1763 of file class.Inventory.php.
copy_from_session()
copy_from_session ()
copy_from_session Copies out of $_SESSION into a CART structure the line items including stock_id, qoh, quantity, etc. Also includes from_location and to_location
Parameters
NONE
Returns
NONE
Definition at line 362 of file class.Inventory.php.
References find_cart_item().
Referenced by create_cart().
copy_to_session()
copy_to_session ()
Definition at line 441 of file class.Inventory.php.
References $Comments, $document_date, $from_location, $location, $reference, and $to_location.
Referenced by add_item(), create_cart(), handle_delete_item(), handlePOST(), overunder_form(), process(), xfer_all_settings(), and xferall_form().
create_cart()
create_cart ()
Definition at line 792 of file class.Inventory.php.
References copy_from_session(), and copy_to_session().
Referenced by __construct(), and handle_new_inventory().
create_inventory_count_table()
create_inventory_count_table ()
Definition at line 196 of file class.Inventory.php.
create_location_scancode_table()
create_location_scancode_table ()
Definition at line 806 of file class.Inventory.php.
create_table_inventory_last_performed()
create_table_inventory_last_performed ()
Definition at line 1375 of file class.Inventory.php.
Referenced by init_tables_completed_form().
display_adjustment_items()
display_adjustment_items ($title, $doEdit = TRUE, $showStock = FALSE, $action = "inventory")
Definition at line 1443 of file class.Inventory.php.
References db_base\$action, $id, and adjustment_edit_item_controls().
Referenced by Inventory_form(), overunder_form(), and xferall_form().
display_inventory_header()
display_inventory_header ($hidden_action = "")
Definition at line 882 of file class.Inventory.php.
Referenced by Inventory_form(), overunder_form(), scan_form(), and xferall_form().
display_inventory_summary()
display_inventory_summary ($title, & $inventory, $editable_items = false)
Definition at line 1550 of file class.Inventory.php.
References $id, and adjustment_edit_item_controls().
EXPORT_CSV_form()
EXPORT_CSV_form ()
Definition at line 1305 of file class.Inventory.php.
find_cart_item()
find_cart_item ()
Definition at line 720 of file class.Inventory.php.
Referenced by add_item(), and copy_from_session().
get_item_description()
get_item_description ()
Definition at line 643 of file class.Inventory.php.
Referenced by add_item().
get_item_qoh_location()
get_item_qoh_location ($stock_id)
Definition at line 1025 of file class.Inventory.php.
Referenced by get_items_qoh_location().
get_items_qoh_location()
get_items_qoh_location ()
Definition at line 1030 of file class.Inventory.php.
References get_item_qoh_location().
Referenced by overunder_form(), and xferall_form().
handle_cancel_inventory()
handle_cancel_inventory ()
Definition at line 761 of file class.Inventory.php.
handle_delete_item()
handle_delete_item ($line_no)
Definition at line 588 of file class.Inventory.php.
References copy_to_session(), line_start_focus(), and page_modified().
Referenced by handlePOST().
handle_new_inventory()
handle_new_inventory ()
Definition at line 1345 of file class.Inventory.php.
References create_cart(), and ST_Inventory.
handle_new_item()
handle_new_item ()
Definition at line 749 of file class.Inventory.php.
References add_item(), line_start_focus(), and page_modified().
Referenced by handlePOST().
handle_update_item()
handle_update_item ()
Definition at line 571 of file class.Inventory.php.
References line_start_focus(), and page_modified().
Referenced by handlePOST().
handlePOST()
handlePOST ()
Definition at line 199 of file class.Inventory.php.
References $holdtank, $id, copy_to_session(), handle_delete_item(), handle_new_item(), handle_update_item(), and line_start_focus().
Referenced by __construct().
hasBarcode()
hasBarcode ()
Definition at line 823 of file class.Inventory.php.
Referenced by scan_form().
haslocation()
haslocation ()
Definition at line 836 of file class.Inventory.php.
init_tables_completed_form()
init_tables_completed_form ()
Definition at line 1366 of file class.Inventory.php.
References create_table_inventory_last_performed().
init_tables_form()
init_tables_form ()
Definition at line 1360 of file class.Inventory.php.
References call_table().
inItemCode()
inItemCode ($item_code)
Definition at line 625 of file class.Inventory.php.
install()
install ()
Definition at line 185 of file class.Inventory.php.
References db_base\create_prefs_tablename(), db_base\loadprefs(), and db_base\updateprefs().
Inventory_form()
Inventory_form ()
Definition at line 1226 of file class.Inventory.php.
References generic_interface\$help_context, $holdtank, adjustment_options_controls(), display_adjustment_items(), and display_inventory_header().
isItemCode()
isItemCode ($item_code)
Definition at line 606 of file class.Inventory.php.
Referenced by add_item().
islocationCode()
islocationCode ($upc)
Definition at line 849 of file class.Inventory.php.
isStockid()
isStockid ($stock_id)
Definition at line 600 of file class.Inventory.php.
Referenced by add_item().
line_start_focus()
line_start_focus ()
Definition at line 489 of file class.Inventory.php.
Referenced by handle_delete_item(), handle_new_item(), handle_update_item(), and handlePOST().
overunder_form()
overunder_form ()
Definition at line 1197 of file class.Inventory.php.
References generic_interface\$help_context, copy_to_session(), display_adjustment_items(), display_inventory_header(), and get_items_qoh_location().
Referenced by xfer_all_to_holding().
page_modified()
page_modified ($status = true)
Definition at line 1792 of file class.Inventory.php.
Referenced by handle_delete_item(), handle_new_item(), and handle_update_item().
page_processing()
page_processing ($msg = false)
Definition at line 1774 of file class.Inventory.php.
References $js.
Referenced by processing_end(), and processing_start().
process()
process ()
Definition at line 1401 of file class.Inventory.php.
References copy_to_session(), and record_last_inv_date().
Referenced by process_form().
process_form()
process_form ()
Definition at line 1429 of file class.Inventory.php.
References generic_interface\$help_context, can_process(), and process().
process_inventory()
process_inventory ()
Definition at line 257 of file class.Inventory.php.
References processing_end(), ST_Inventory, and write().
processing_end()
processing_end ()
Definition at line 1757 of file class.Inventory.php.
References page_processing().
Referenced by process_inventory(), and processing_start().
processing_start()
processing_start ()
Definition at line 1750 of file class.Inventory.php.
References page_processing(), and processing_end().
record_last_inv_date()
record_last_inv_date ($stock_id)
Definition at line 1390 of file class.Inventory.php.
Referenced by process().
scan_form()
scan_form ()
Definition at line 915 of file class.Inventory.php.
References add_item(), display_inventory_header(), hasBarcode(), db_base\set_var(), and upc_table().
submenu_choices()
submenu_choices ()
Definition at line 303 of file class.Inventory.php.
References check_edit_conflicts(), and ST_Inventory.
table_memo_field()
table_memo_field ()
Definition at line 1743 of file class.Inventory.php.
upc_table()
upc_table ()
Definition at line 900 of file class.Inventory.php.
Referenced by scan_form().
write()
write ()
Definition at line 254 of file class.Inventory.php.
Referenced by process_inventory().
xfer_all_settings()
xfer_all_settings ($action)
Definition at line 1080 of file class.Inventory.php.
References db_base\$action, add_all_list(), and copy_to_session().
Referenced by xfer_all_to_holding(), and xfer_all_to_location().
xfer_all_to_holding()
xfer_all_to_holding ()
Definition at line 1073 of file class.Inventory.php.
References $holdtank, overunder_form(), and xfer_all_settings().
xfer_all_to_holding_form()
xfer_all_to_holding_form ()
Definition at line 1134 of file class.Inventory.php.
References call_table().
xfer_all_to_location()
xfer_all_to_location ()
Definition at line 1065 of file class.Inventory.php.
References xfer_all_settings(), and xferall_form().
xfer_all_to_location_form()
xfer_all_to_location_form ()
Definition at line 1152 of file class.Inventory.php.
References call_table().
xferall_form()
xferall_form ()
Definition at line 1168 of file class.Inventory.php.
References generic_interface\$help_context, copy_to_session(), display_adjustment_items(), display_inventory_header(), and get_items_qoh_location().
Referenced by xfer_all_to_location().
Field Documentation
$add_quantity
$add_quantity
Definition at line 116 of file class.Inventory.php.
Referenced by add_item().
$barcode
$barcode
Definition at line 96 of file class.Inventory.php.
Referenced by add_item().
$change_line_number
$change_line_number
Definition at line 119 of file class.Inventory.php.
$Comments
$Comments
Definition at line 104 of file class.Inventory.php.
Referenced by copy_to_session().
$copyfromcount
$copyfromcount
Definition at line 111 of file class.Inventory.php.
$copytocount
$copytocount
Definition at line 112 of file class.Inventory.php.
$csv_filename
$csv_filename
Definition at line 86 of file class.Inventory.php.
$deliver_to
$deliver_to
Definition at line 107 of file class.Inventory.php.
$delivery_address
$delivery_address
Definition at line 108 of file class.Inventory.php.
$document_date
$document_date
Definition at line 105 of file class.Inventory.php.
Referenced by copy_to_session().
$email_body
$email_body
Definition at line 85 of file class.Inventory.php.
$email_subject
$email_subject
email subject line. Not currently implemented.
Definition at line 84 of file class.Inventory.php.
$ex_rate
$ex_rate
Definition at line 106 of file class.Inventory.php.
$from_location
$from_location
Definition at line 91 of file class.Inventory.php.
Referenced by copy_to_session().
$holdtank
$holdtank
Definition at line 89 of file class.Inventory.php.
Referenced by handlePOST(), Inventory_form(), and xfer_all_to_holding().
$item_text
$item_text
Definition at line 117 of file class.Inventory.php.
Referenced by add_item().
$line_items
$line_items
Definition at line 99 of file class.Inventory.php.
$location
$location
Definition at line 88 of file class.Inventory.php.
Referenced by copy_to_session().
$locationPrefix
$locationPrefix
Definition at line 97 of file class.Inventory.php.
$locationPrefix2
$locationPrefix2
Definition at line 98 of file class.Inventory.php.
$mailto
$mailto
mailto address for emailing reports. Not implemented currently
Definition at line 83 of file class.Inventory.php.
$path_to_root
$path_to_root
Definition at line 114 of file class.Inventory.php.
Referenced by __construct().
$pretty_filename
$pretty_filename
Definition at line 87 of file class.Inventory.php.
$reference
$reference
Definition at line 103 of file class.Inventory.php.
Referenced by copy_to_session().
$stock_id
$stock_id
Definition at line 118 of file class.Inventory.php.
Referenced by add_item().
$table_interface
$table_interface
Definition at line 120 of file class.Inventory.php.
$title
$title
Definition at line 113 of file class.Inventory.php.
$to_location
$to_location
Definition at line 90 of file class.Inventory.php.
Referenced by copy_to_session().
$trans_no
$trans_no
Definition at line 95 of file class.Inventory.php.
$trans_type
$trans_type
Definition at line 94 of file class.Inventory.php.
$update_quantity
$update_quantity
Definition at line 115 of file class.Inventory.php.
$url
$url
Definition at line 92 of file class.Inventory.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/devel/fhs/frontaccounting/modules/Inventory/class.Inventory.php