Inventory: generic_interface Class Reference
generic_interface Class Reference
Public Member Functions
__construct ($host, $user, $pass, $database, $prefs_tablename)
related_tabs ()
show_form ()
base_page ()
display ()
run ()
append_file ($filename)
overwrite_file ($filename)
close_file ($fp)
Public Member Functions inherited from db_base
__construct ($prefs_tablename)
set_var ($var, $value)
get_var ($var)
is_installed ()
set_prefix ()
create_prefs_tablename ()
set_pref ($pref, $value)
get_pref ($pref)
loadprefs ()
updateprefs ()
Data Fields
$errors
$javascript
$help_context
$page_title
Data Fields inherited from db_base
$action
$dbHost
$dbUser
$dbPassword
$dbName
$db_connection
$prefs_tablename
$company_prefix
$config_values = array()
Detailed Description
Definition at line 5 of file class.generic_interface.php.
Constructor & Destructor Documentation
__construct()
__construct ($host, $user, $pass, $database, $prefs_tablename)
Definition at line 11 of file class.generic_interface.php.
References db_base\$prefs_tablename.
Member Function Documentation
append_file()
append_file ($filename)
Definition at line 85 of file class.generic_interface.php.
base_page()
base_page ()
Definition at line 51 of file class.generic_interface.php.
References related_tabs().
Referenced by display().
close_file()
close_file ($fp)
Definition at line 95 of file class.generic_interface.php.
display()
display ()
Definition at line 57 of file class.generic_interface.php.
References base_page(), and show_form().
Referenced by run().
overwrite_file()
overwrite_file ($filename)
Definition at line 90 of file class.generic_interface.php.
related_tabs()
related_tabs ()
Definition at line 15 of file class.generic_interface.php.
References db_base\$action.
Referenced by base_page().
run()
run ()
Definition at line 63 of file class.generic_interface.php.
References display(), db_base\loadprefs(), and db_base\set_var().
show_form()
show_form ()
Definition at line 38 of file class.generic_interface.php.
References db_base\$action.
Referenced by display().
Field Documentation
$errors
$errors
Definition at line 7 of file class.generic_interface.php.
$help_context
$help_context
Definition at line 9 of file class.generic_interface.php.
$javascript
$javascript
Definition at line 8 of file class.generic_interface.php.
$page_title
$page_title
Definition at line 10 of file class.generic_interface.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/devel/fhs/frontaccounting/modules/Inventory/class.generic_interface.php