Inventory: db_base Class Reference
db_base Class Reference
Public Member Functions
__construct ($prefs_tablename)
set_var ($var, $value)
get_var ($var)
is_installed ()
set_prefix ()
create_prefs_tablename ()
set_pref ($pref, $value)
get_pref ($pref)
loadprefs ()
updateprefs ()
Data Fields
$action
$dbHost
$dbUser
$dbPassword
$dbName
$db_connection
$prefs_tablename
$company_prefix
$config_values = array()
Detailed Description
Definition at line 8 of file db_base.php.
Constructor & Destructor Documentation
__construct()
__construct ($prefs_tablename)
Definition at line 21 of file db_base.php.
References set_prefix(), and set_var().
Member Function Documentation
create_prefs_tablename()
create_prefs_tablename ()
Definition at line 84 of file db_base.php.
References $prefs_tablename.
Referenced by generic_orders\install().
get_pref()
get_pref ($pref)
Definition at line 102 of file db_base.php.
Referenced by generic_orders\loadprefs(), and loadprefs().
get_var()
get_var ($var)
Definition at line 38 of file db_base.php.
is_installed()
is_installed ()
Definition at line 57 of file db_base.php.
loadprefs()
loadprefs ()
Definition at line 114 of file db_base.php.
References get_pref(), and set_var().
Referenced by generic_interface\run().
set_pref()
set_pref ($pref, $value)
Definition at line 97 of file db_base.php.
Referenced by generic_orders\updateprefs(), and updateprefs().
set_prefix()
set_prefix ()
Definition at line 68 of file db_base.php.
References set_var().
Referenced by __construct().
set_var()
set_var ($var, $value)
Definition at line 34 of file db_base.php.
Referenced by __construct(), generic_orders\loadprefs(), loadprefs(), generic_interface\run(), generic_orders\run(), set_prefix(), generic_orders\updateprefs(), and updateprefs().
updateprefs()
updateprefs ()
Definition at line 122 of file db_base.php.
References set_pref(), and set_var().
Field Documentation
$action
$action
Definition at line 10 of file db_base.php.
Referenced by generic_interface\related_tabs(), and generic_interface\show_form().
$company_prefix
$company_prefix
Definition at line 17 of file db_base.php.
$config_values
$config_values = array()
Definition at line 18 of file db_base.php.
$db_connection
$db_connection
Definition at line 15 of file db_base.php.
$dbHost
$dbHost
Definition at line 11 of file db_base.php.
$dbName
$dbName
Definition at line 14 of file db_base.php.
$dbPassword
$dbPassword
Definition at line 13 of file db_base.php.
$dbUser
$dbUser
Definition at line 12 of file db_base.php.
$prefs_tablename
$prefs_tablename
Definition at line 16 of file db_base.php.
Referenced by generic_interface\__construct(), and create_prefs_tablename().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/devel/fhs/frontaccounting/modules/Inventory/db_base.php