Inventory: generic_orders Class Reference
generic_orders Class Reference
Public Member Functions
__construct ($host, $user, $pass, $database, $pref_tablename)
install ()
get_purchase_order ()
get_id_range ()
get_supplier_order ()
export_orders ()
loadprefs ()
updateprefs ()
checkprefs ()
action_show_form ()
form_export ()
related_tabs ()
show_form ()
base_page ()
display ()
run ()
Public Member Functions inherited from db_base
__construct ($prefs_tablename)
set_var ($var, $value)
get_var ($var)
is_installed ()
set_prefix ()
create_prefs_tablename ()
set_pref ($pref, $value)
get_pref ($pref)
loadprefs ()
updateprefs ()
Data Fields
$order_no
$db_Host
$db_User
$db_Password
$db_Name
$last_order_no
$vendor
$tabs = array()
$found
$purchase_order
$config_values = array()
$help_context
$action
$redirect_to
Data Fields inherited from db_base
$action
$dbHost
$dbUser
$dbPassword
$dbName
$db_connection
$prefs_tablename
$company_prefix
$config_values = array()
Detailed Description
Definition at line 7 of file class.generic_orders.php.
Constructor & Destructor Documentation
__construct()
__construct ($host, $user, $pass, $database, $pref_tablename)
Definition at line 31 of file class.generic_orders.php.
Member Function Documentation
action_show_form()
action_show_form ()
Definition at line 109 of file class.generic_orders.php.
base_page()
base_page ()
Definition at line 223 of file class.generic_orders.php.
References related_tabs().
Referenced by display().
checkprefs()
checkprefs ()
Definition at line 105 of file class.generic_orders.php.
References updateprefs().
Referenced by install().
display()
display ()
Definition at line 228 of file class.generic_orders.php.
References base_page(), and show_form().
Referenced by run().
export_orders()
export_orders ()
Definition at line 81 of file class.generic_orders.php.
form_export()
form_export ()
Definition at line 138 of file class.generic_orders.php.
References get_id_range().
get_id_range()
get_id_range ()
Definition at line 59 of file class.generic_orders.php.
Referenced by form_export().
get_purchase_order()
get_purchase_order ()
Definition at line 49 of file class.generic_orders.php.
get_supplier_order()
get_supplier_order ()
Definition at line 67 of file class.generic_orders.php.
install()
install ()
Definition at line 39 of file class.generic_orders.php.
References checkprefs(), db_base\create_prefs_tablename(), and loadprefs().
Referenced by run().
loadprefs()
loadprefs ()
Definition at line 86 of file class.generic_orders.php.
References db_base\get_pref(), and db_base\set_var().
Referenced by install(), and run().
related_tabs()
related_tabs ()
Definition at line 187 of file class.generic_orders.php.
References $action.
Referenced by base_page().
run()
run ()
Definition at line 234 of file class.generic_orders.php.
References display(), install(), loadprefs(), and db_base\set_var().
show_form()
show_form ()
Definition at line 210 of file class.generic_orders.php.
References $action.
Referenced by display().
updateprefs()
updateprefs ()
Definition at line 94 of file class.generic_orders.php.
References db_base\set_pref(), and db_base\set_var().
Referenced by checkprefs().
Field Documentation
$action
$action
Definition at line 22 of file class.generic_orders.php.
Referenced by related_tabs(), and show_form().
$config_values
$config_values = array()
Definition at line 20 of file class.generic_orders.php.
$db_Host
$db_Host
Definition at line 11 of file class.generic_orders.php.
$db_Name
$db_Name
Definition at line 14 of file class.generic_orders.php.
$db_Password
$db_Password
Definition at line 13 of file class.generic_orders.php.
$db_User
$db_User
Definition at line 12 of file class.generic_orders.php.
$found
$found
Definition at line 18 of file class.generic_orders.php.
$help_context
$help_context
Definition at line 21 of file class.generic_orders.php.
$last_order_no
$last_order_no
Definition at line 15 of file class.generic_orders.php.
$order_no
$order_no
Definition at line 10 of file class.generic_orders.php.
$purchase_order
$purchase_order
Definition at line 19 of file class.generic_orders.php.
$redirect_to
$redirect_to
Definition at line 23 of file class.generic_orders.php.
$tabs
$tabs = array()
Definition at line 17 of file class.generic_orders.php.
$vendor
$vendor
Definition at line 16 of file class.generic_orders.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/devel/fhs/frontaccounting/modules/Inventory/class.generic_orders.php