Inventory: C:/xampp/htdocs/devel/fhs/frontaccounting/modules/Inventory/inventory_entry.php File Reference
inventory_entry.php File Reference
Functions
copy_to_cart ()
copy_from_cart ()
line_start_focus ()
can_process ()
if(isset($_POST['update'])) if(isset($_POST['ProcessOrder']) &&can_process()) check_item_data ()
handle_update_item ()
handle_delete_item ($line_no)
handle_new_item ()
handle_cancel_order ()
create_cart ($type, $trans_no)
Variables
$path_to_root = "../.."
$page_security = 'SA_Inventory'
$js = ''
$id = find_submit('Delete')
if($_SESSION['Items']->trans_type==ST_Inventory) elseif($_SESSION['Items']->trans_type==ST_CUSTDELIVERY) elseif($_SESSION['Items']->trans_type==ST_Inventory) else
$orderitems = _("Sales Order Items")
$deliverydetails = _("Enter Delivery Details and Confirm Order")
$cancelorder = _("Cancel Order")
$porder = _("Place Order")
$corder = _("Commit Order Changes")
$customer_error
Function Documentation
can_process()
can_process ()
Definition at line 335 of file inventory_entry.php.
References copy_to_cart(), and ST_Inventory.
check_item_data()
if (isset($_POST[ 'update'])) if (isset($_POST[ 'ProcessOrder']) &&can_process()) check_item_data ()
Definition at line 492 of file inventory_entry.php.
Referenced by handle_new_item(), and handle_update_item().
copy_from_cart()
copy_from_cart ()
Definition at line 295 of file inventory_entry.php.
References ST_Inventory.
Referenced by create_cart().
copy_to_cart()
copy_to_cart ()
Definition at line 244 of file inventory_entry.php.
References ST_Inventory.
Referenced by can_process().
create_cart()
create_cart ($type, $trans_no)
Definition at line 623 of file inventory_entry.php.
References copy_from_cart(), handle_cancel_order(), and ST_Inventory.
handle_cancel_order()
handle_cancel_order ()
Definition at line 580 of file inventory_entry.php.
References $path_to_root, and ST_Inventory.
Referenced by create_cart().
handle_delete_item()
handle_delete_item ($line_no)
Definition at line 552 of file inventory_entry.php.
References line_start_focus().
handle_new_item()
handle_new_item ()
Definition at line 564 of file inventory_entry.php.
References check_item_data(), and line_start_focus().
handle_update_item()
handle_update_item ()
Definition at line 539 of file inventory_entry.php.
References check_item_data(), and line_start_focus().
line_start_focus()
line_start_focus ()
Definition at line 327 of file inventory_entry.php.
Referenced by handle_delete_item(), handle_new_item(), and handle_update_item().
Variable Documentation
$cancelorder
$cancelorder = _("Cancel Order")
Definition at line 708 of file inventory_entry.php.
$corder
$corder = _("Commit Order Changes")
Definition at line 710 of file inventory_entry.php.
$customer_error
$customer_error
Initial value:
= display_order_header($_SESSION['Items'],
    ($_SESSION['Items']->any_already_delivered() == 0), $idate)
Definition at line 715 of file inventory_entry.php.
$deliverydetails
$deliverydetails = _("Enter Delivery Details and Confirm Order")
Definition at line 707 of file inventory_entry.php.
$id
$id = find_submit('Delete')
Definition at line 666 of file inventory_entry.php.
$js
$js = ''
Definition at line 52 of file inventory_entry.php.
$orderitems
$orderitems = _("Sales Order Items")
Definition at line 706 of file inventory_entry.php.
$page_security
$page_security = 'SA_Inventory'
Definition at line 21 of file inventory_entry.php.
$path_to_root
$path_to_root = "../.."
Definition at line 20 of file inventory_entry.php.
Referenced by handle_cancel_order().
$porder
$porder = _("Place Order")
Definition at line 709 of file inventory_entry.php.
else
if ($customer_error=="") else
Initial value:
{
    $idate = _("Order Date:")
Definition at line 704 of file inventory_entry.php.