Inventory: C:/xampp/htdocs/devel/fhs/frontaccounting/modules/Inventory/transfers.php File Reference
transfers.php File Reference
Functions
if(isset($_GET['AddedID'])) line_start_focus ()
handle_new_order ()
if(isset($_POST['Process'])) if(isset($_POST['Process'])) check_item_data ()
handle_update_item ()
handle_delete_item ($id)
handle_new_item ()
Variables
$page_security = 'SA_LOCATIONTRANSFER'
$path_to_root = ".."
$js = ""
$id = find_submit('Delete')
Function Documentation
check_item_data()
if (isset($_POST[ 'Process'])) if (isset($_POST[ 'Process'])) check_item_data ()
Definition at line 150 of file transfers.php.
Referenced by handle_new_item(), and handle_update_item().
handle_delete_item()
handle_delete_item ($id)
Definition at line 177 of file transfers.php.
References $id, and line_start_focus().
handle_new_item()
handle_new_item ()
Definition at line 185 of file transfers.php.
References check_item_data(), and line_start_focus().
handle_new_order()
handle_new_order ()
Definition at line 60 of file transfers.php.
handle_update_item()
handle_update_item ()
Definition at line 163 of file transfers.php.
References $id, check_item_data(), and line_start_focus().
line_start_focus()
if (isset($_GET[ 'AddedID'])) line_start_focus ()
Definition at line 52 of file transfers.php.
Referenced by handle_delete_item(), handle_new_item(), and handle_update_item().
Variable Documentation
$id
$id = find_submit('Delete')
Definition at line 196 of file transfers.php.
Referenced by handle_delete_item(), and handle_update_item().
$js
$js = ""
Definition at line 23 of file transfers.php.
$page_security
$page_security = 'SA_LOCATIONTRANSFER'
Definition at line 12 of file transfers.php.
$path_to_root
$path_to_root = ".."
Definition at line 13 of file transfers.php.