<?php
/**
 * Simple test for UI constants in ui_strings.php
 */

require_once __DIR__ . '/../includes/ui_strings.php';

// Test that key constants are defined
$constants = [
    'UI_TEXT_VOID_TRANSACTION_TITLE',
    'UI_TEXT_TRANSACTION_TYPE_LABEL',
    'UI_TEXT_FROM_LABEL',
    'UI_TEXT_TO_LABEL',
    'UI_TEXT_SEARCH',
    'UI_TEXT_MARKED_WILL_BE_VOIDED',
    'UI_TEXT_TRANSACTION_NUMBER',
    'UI_TEXT_VOIDING_DATE',
    'UI_TEXT_MEMO_LABEL',
    'UI_TEXT_VOID_TRANSACTION_BUTTON',
    'UI_TEXT_ENTERED_TRANSACTION_NOT_FOUND',
    'UI_TEXT_INSUFFICIENT_QUANTITY_WARNING',
    'UI_TEXT_QUANTITY_ON_HAND',
    'UI_TEXT_VOID_CONFIRMATION',
    'UI_TEXT_VOID_PROCEED',
    'UI_TEXT_CANCEL',
    'UI_TEXT_CLOSED_TRANSACTION_ERROR',
    'UI_TEXT_INVALID_DATE_ERROR',
    'UI_TEXT_DATE_OUT_OF_FISCAL_YEAR_ERROR',
    'UI_TEXT_NUMERIC_TRANSACTION_NUMBER_ERROR',
    'UI_TEXT_ALREADY_VOIDED_ERROR',
    'UI_TEXT_TRANSACTION_VOIDED_NOTICE',
    'UI_TEXT_REFERENCE_COLUMN',
    'UI_TEXT_DATE_COLUMN',
    'UI_TEXT_NUMBER_COLUMN',
    'UI_TEXT_NA',
    'UI_TEXT_PRINT',
    'UI_TEXT_ONLY_DOCUMENTS_PRINTABLE',
    'UI_TEXT_TYPE_LABEL',
    'UI_TEXT_FROM_NUMBER',
    'UI_TEXT_TO_NUMBER',
    'UI_TEXT_START_TRANS_NUMERIC_ERROR',
    'UI_TEXT_END_TRANS_NUMERIC_ERROR',
    'UI_TEXT_VIEW_PRINT_TRANSACTIONS_TITLE',
    'UI_TEXT_UNSPECIFIED_TAG_TYPE',
    'UI_TEXT_TAG_NAME_EMPTY_ERROR',
    'UI_TEXT_CANNOT_DELETE_TAG_ERROR',
    'UI_TEXT_TAG_NAME',
    'UI_TEXT_TAG_DESCRIPTION',
    'UI_TEXT_EDIT',
    'UI_TEXT_DELETE',
    'UI_TEXT_ACCOUNT_TAGS_TITLE',
    'UI_TEXT_DIMENSION_TAGS_TITLE',
    'UI_TEXT_TAG_NAME_LABEL',
    'UI_TEXT_TAG_DESCRIPTION_LABEL',
    'UI_TEXT_USERS_TITLE',
    'UI_TEXT_USER_LOGIN_TOO_SHORT_ERROR',
    'UI_TEXT_PASSWORD_TOO_SHORT_ERROR',
    'UI_TEXT_PASSWORD_CONTAINS_LOGIN_ERROR',
    'UI_TEXT_USER_UPDATED_NOTICE',
    'UI_TEXT_USER_ADDED_NOTICE',
    'UI_TEXT_CANNOT_DELETE_USER_ERROR',
    'UI_TEXT_USER_DELETED_NOTICE',
    'UI_TEXT_USER_LOGIN',
    'UI_TEXT_FULL_NAME',
    'UI_TEXT_PHONE',
    'UI_TEXT_EMAIL',
    'UI_TEXT_LAST_VISIT',
    'UI_TEXT_ACCESS_LEVEL',
    'UI_TEXT_USER_LOGIN_LABEL',
    'UI_TEXT_PASSWORD_LABEL',
    'UI_TEXT_ENTER_NEW_PASSWORD_INSTRUCTION',
    'UI_TEXT_TELEPHONE_LABEL',
    'UI_TEXT_EMAIL_ADDRESS_LABEL',
    'UI_TEXT_LANGUAGE_LABEL',
    'UI_TEXT_USERS_POS_LABEL',
    'UI_TEXT_PRINTING_PROFILE_LABEL',
    'UI_TEXT_USE_POPUP_WINDOW_LABEL',
    'UI_TEXT_BROWSER_PRINTING_SUPPORT',
    'UI_TEXT_POPUP_WINDOW_INSTRUCTION',
    'UI_TEXT_GL_LABEL',
    'UI_TEXT_SELECT'
];

$failed = [];
foreach ($constants as $const) {
    if (!defined($const)) {
        $failed[] = $const;
    }
}

if (empty($failed)) {
    echo "All UI constants are defined.\n";
    exit(0);
} else {
    echo "Missing constants: " . implode(', ', $failed) . "\n";
    exit(1);
}
