<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
  0 => 
  array (
    'name' => 'English Canadian COA - General',
    'package' => 'chart_en_CA-general',
    'version' => '2.3.0-5',
    'type' => 'chart',
    'active' => false,
    'path' => 'sql',
    'sql' => 'en_CA-general.sql',
  ),
  1 => 
  array (
    'name' => '8 digit GAAP compatible American chart of accounts',
    'package' => 'chart_en_US-GAAP',
    'version' => '2.3.0-3',
    'type' => 'chart',
    'active' => false,
    'path' => 'sql',
    'sql' => 'en_US-GAAP.sql',
  ),
  8 => 
  array (
    'name' => 'Sales Summary Report',
    'package' => 'rep_sales_summary',
    'version' => '2.3.3-3',
    'type' => 'extension',
    'active' => false,
    'path' => 'modules/rep_sales_summary',
  ),
  12 => 
  array (
    'name' => 'Cash Flow Statement Report',
    'package' => 'rep_cash_flow_statement',
    'version' => '2.3.0-1',
    'type' => 'extension',
    'active' => false,
    'path' => 'modules/rep_cash_flow_statement',
  ),
  13 => 
  array (
    'name' => 'Annual expense breakdown report',
    'package' => 'rep_annual_expense_breakdown',
    'version' => '2.3.0-1',
    'type' => 'extension',
    'active' => false,
    'path' => 'modules/rep_annual_expense_breakdown',
  ),
  14 => 
  array (
    'name' => 'Annual balance breakdown report',
    'package' => 'rep_annual_balance_breakdown',
    'version' => '2.3.0-1',
    'type' => 'extension',
    'active' => false,
    'path' => 'modules/rep_annual_balance_breakdown',
  ),
  36 => 
  array (
    'package' => 'ksf_data_dictionary',
    'name' => 'ksf_data_dictionary',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/ksf_data_dictionary',
    'active' => 1,
  ),
  38 => 
  array (
    'package' => 'ksf_qoh',
    'name' => 'ksf_qoh',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/ksf_qoh',
    'active' => 0,
  ),
  43 => 
  array (
    'package' => 'ksf_payment_destinations',
    'name' => 'ksf_payment_destinations',
    'version' => '1',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/ksf_payment_destinations',
    'active' => 0,
  ),
  44 => 
  array (
    'package' => 'ksf_suitecrm',
    'name' => 'ksf_suitecrm',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/ksf_suitecrm',
    'active' => 0,
  ),
  53 => 
  array (
    'package' => 'pl_dimension',
    'name' => 'pl_dimension',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/pl_dimension',
    'active' => false,
  ),
  58 => 
  array (
    'name' => 'Import Multiple Journal Entries',
    'package' => 'import_multijournalentries',
    'version' => '2.3.0-8',
    'type' => 'extension',
    'active' => 1,
    'path' => 'modules/import_multijournalentries',
  ),
  59 => 
  array (
    'package' => 'ksf_import',
    'name' => 'ksf_import',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/ksf_import',
    'active' => 0,
  ),
  60 => 
  array (
    'package' => 'bank_import',
    'name' => 'bank_import',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/bank_import',
    'active' => 1,
  ),
  61 => 
  array (
    'name' => 'Import Paypal transactions',
    'package' => 'import_paypal',
    'version' => '2.3.10-4',
    'type' => 'extension',
    'active' => false,
    'path' => 'modules/import_paypal',
  ),
  62 => 
  array (
    'package' => 'mail',
    'name' => 'mail',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/mail',
    'active' => 1,
  ),
);
?>