CREATE TABLE `0_crm_activity` (
  `id_crm_activity` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `crm_activity` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `source_record_id` int(10) unsigned DEFAULT NULL COMMENT 'Artificial FK to original transaction (e.g. contribution) IF it is not an Activity. Table can be figured out through activity_type_id, and further through component registry.',
  `id_crm_activity_type` int(11) unsigned NOT NULL COMMENT 'FK to civicrm_option_value.id, that has to be valid, registered activity type.',
  `description` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `activity_date_time` datetime DEFAULT NULL COMMENT 'Date and time this activity is scheduled to occur. Formerly named scheduled_date_time.',
  `duration` int(10) unsigned DEFAULT NULL COMMENT 'Planned or actual duration of activity expressed in minutes. Conglomerate of former duration_hours and duration_minutes.',
  `location` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Location of the activity (optional, open text).',
  `phone_id` int(10) unsigned DEFAULT NULL COMMENT 'Phone ID of the number called (optional - used if an existing phone number is selected).',
  `details` text COLLATE utf8_unicode_ci COMMENT 'Details about the activity (agenda, notes, etc).',
  `id_crm_campaign_status_code` int(10) unsigned DEFAULT NULL COMMENT 'ID of the status this activity is currently in. Foreign key to civicrm_option_value.',
  `id_crm_campaign_outcome_codes` int(11) DEFAULT NULL,
  `b_deleted` int(1) DEFAULT '0',
  `id_crm_campaign` int(11) unsigned DEFAULT NULL,
  `engagement_level` int(10) unsigned DEFAULT NULL COMMENT 'Assign a specific level of engagement to this activity. Used for tracking constituents in ladder of engagement.',
  PRIMARY KEY (`id_crm_activity`),
  KEY `UI_source_record_id` (`source_record_id`),
  KEY `UI_activity_type_id` (`id_crm_activity_type`),
  KEY `index_is_deleted` (`b_deleted`),
  KEY `FK_civicrm_activity_phone_id` (`phone_id`),
  KEY `FK_civicrm_activity_campaign_id` (`id_crm_campaign`)
) ENGINE=InnoDB AUTO_INCREMENT=625 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `0_crm_activity_persons` (
  `id_crm_activity_persons` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `crm_outcome_code` varchar(32) NOT NULL,
  `id_crm_persons` int(11) NOT NULL,
  `assigned_date` date NOT NULL,
  `outcome_date` date NOT NULL,
  `role` varchar(32) NOT NULL,
  PRIMARY KEY (`id_crm_activity_persons`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_crm_activity_types` (
  `id_crm_activity_type` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `activity_type` varchar(32) NOT NULL,
  `name` varchar(20) NOT NULL,
  `description` varchar(60) NOT NULL,
  `effective_date` date NOT NULL DEFAULT '0000-00-00',
  `end_date` date NOT NULL DEFAULT '0000-00-00',
  `reference` varchar(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id_crm_activity_type`),
  KEY `tran_date` (`effective_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_crm_campaign_details` (
  `id_crm_campaign_details` int(11) NOT NULL AUTO_INCREMENT,
  `id_crm_campaigns` int(11) NOT NULL,
  `id_hrm_position` int(11) NOT NULL COMMENT 'Sponsor',
  `budget` double NOT NULL COMMENT 'for category selector',
  `description` tinytext NOT NULL COMMENT 'usage description',
  `spend_to_date` double NOT NULL,
  `expected_revenue` double NOT NULL,
  `actual_revenue` double NOT NULL,
  `expected_roi` double NOT NULL,
  `actual_roi` double NOT NULL,
  `id_item_codes` int(11) NOT NULL COMMENT 'Product',
  PRIMARY KEY (`id_crm_campaign_details`),
  UNIQUE KEY `type` (`id_crm_campaigns`,`id_hrm_position`),
  UNIQUE KEY `type_2` (`id_crm_campaigns`,`budget`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_crm_campaign_event` (
  `id_crm_campaign_event` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Event Title (e.g. Fall Fundraiser Dinner)',
  `summary` text COLLATE utf8_unicode_ci COMMENT 'Brief summary of event. Text and html allowed. Displayed on Event Registration form and can be used on other CMS pages which need an event summary.',
  `description` text COLLATE utf8_unicode_ci COMMENT 'Full description of event. Text and html allowed. Displayed on built-in Event Information screens.',
  `id_crm_campaign_event_types` int(11) unsigned DEFAULT NULL,
  `is_public` tinyint(4) DEFAULT '1' COMMENT 'Public events will be included in the iCal feeds. Access to private event information may be limited using ACLs.',
  `start_date` datetime DEFAULT NULL COMMENT 'Date and time that event starts.',
  `end_date` datetime DEFAULT NULL COMMENT 'Date and time that event ends. May be NULL if no defined end date/time',
  `location` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `is_online_registration` tinyint(4) DEFAULT '0' COMMENT 'If true, include registration link on Event Info page.',
  `registration_link_text` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Text for link to Event Registration form which is displayed on Event Information screen when is_online_registration is true.',
  `registration_start_date` datetime DEFAULT NULL COMMENT 'Date and time that online registration starts.',
  `registration_end_date` datetime DEFAULT NULL COMMENT 'Date and time that online registration ends.',
  `max_participants` int(10) unsigned DEFAULT NULL COMMENT 'Maximum number of registered participants to allow. After max is reached, a custom Event Full message is displayed. If NULL, allow unlimited number of participants.',
  `event_full_text` text COLLATE utf8_unicode_ci COMMENT 'Message to display on Event Information page and INSTEAD OF Event Registration form if maximum participants are signed up. Can include email address/info about getting on a waiting list, etc. Text and html allowed.',
  `intro_text` text COLLATE utf8_unicode_ci COMMENT 'Introductory message for Event Registration page. Text and html allowed. Displayed at the top of Event Registration form.',
  `footer_text` text COLLATE utf8_unicode_ci COMMENT 'Footer message for Event Registration page. Text and html allowed. Displayed at the bottom of Event Registration form.',
  `confirm_title` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Title for Confirmation page.',
  `confirm_text` text COLLATE utf8_unicode_ci COMMENT 'Introductory message for Event Registration page. Text and html allowed. Displayed at the top of Event Registration form.',
  `confirm_footer_text` text COLLATE utf8_unicode_ci COMMENT 'Footer message for Event Registration page. Text and html allowed. Displayed at the bottom of Event Registration form.',
  `is_email_confirm` tinyint(4) DEFAULT '0' COMMENT 'If true, confirmation is automatically emailed to contact on successful registration.',
  `confirm_email_text` text COLLATE utf8_unicode_ci COMMENT 'text to include above standard event info on confirmation email. emails are text-only, so do not allow html for now',
  `confirm_from_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'FROM email name used for confirmation emails.',
  `confirm_from_email` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'FROM email address used for confirmation emails.',
  `cc_confirm` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'comma-separated list of email addresses to cc each time a confirmation is sent',
  `bcc_confirm` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'comma-separated list of email addresses to bcc each time a confirmation is sent',
  `thankyou_title` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Title for ThankYou page.',
  `thankyou_text` text COLLATE utf8_unicode_ci COMMENT 'ThankYou Text.',
  `thankyou_footer_text` text COLLATE utf8_unicode_ci COMMENT 'Footer message.',
  `is_multiple_registrations` tinyint(4) DEFAULT '0' COMMENT 'if true - allows the user to register multiple participants for event',
  `allow_same_participant_emails` tinyint(4) DEFAULT '0' COMMENT 'if true - allows the user to register multiple registrations from same email address.',
  `has_waitlist` tinyint(4) DEFAULT NULL COMMENT 'Whether the event has waitlist support.',
  `requires_approval` tinyint(4) DEFAULT NULL COMMENT 'Whether participants require approval before they can finish registering.',
  `approval_req_text` text COLLATE utf8_unicode_ci COMMENT 'Text to display when the approval is required to complete registration for an event.',
  `campaign_id` int(10) unsigned DEFAULT NULL COMMENT 'The campaign for which this event has been created.',
  `is_share` tinyint(4) DEFAULT '1' COMMENT 'Can people share the event through social media?',
  PRIMARY KEY (`id_crm_campaign_event`),
  KEY `index_event_type_id` (`id_crm_campaign_event_types`),
  KEY `FK_civicrm_event_campaign_id` (`campaign_id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `0_crm_campaign_event_persons` (
  `id_crm_campaign_event_persons` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `crm_outcome_code` varchar(32) NOT NULL,
  `id_crm_persons` int(11) NOT NULL,
  `assigned_date` date NOT NULL,
  `outcome_date` date NOT NULL,
  PRIMARY KEY (`id_crm_campaign_event_persons`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_crm_campaign_event_types` (
  `id_crm_campaign_event_type` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `campaign_event_type` varchar(32) NOT NULL,
  `name` varchar(20) NOT NULL,
  `description` varchar(60) NOT NULL,
  `effective_date` date NOT NULL DEFAULT '0000-00-00',
  `end_date` date NOT NULL DEFAULT '0000-00-00',
  `reference` varchar(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id_crm_campaign_event_type`),
  KEY `tran_date` (`effective_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_crm_campaign_mailling` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `domain_id` int(10) unsigned DEFAULT NULL COMMENT 'Which site is this mailing for',
  `header_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to the header component.',
  `footer_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to the footer component.',
  `reply_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to the auto-responder component.',
  `unsubscribe_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to the unsubscribe component.',
  `resubscribe_id` int(10) unsigned DEFAULT NULL,
  `optout_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to the opt-out component.',
  `name` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Mailing Name.',
  `from_name` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'From Header of mailing',
  `from_email` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'From Email of mailing',
  `replyto_email` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Reply-To Email of mailing',
  `subject` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Subject of mailing',
  `body_text` longtext COLLATE utf8_unicode_ci COMMENT 'Body of the mailing in text format.',
  `body_html` longtext COLLATE utf8_unicode_ci COMMENT 'Body of the mailing in html format.',
  `url_tracking` tinyint(4) DEFAULT NULL COMMENT 'Should we track URL click-throughs for this mailing?',
  `forward_replies` tinyint(4) DEFAULT NULL COMMENT 'Should we forward replies back to the author?',
  `auto_responder` tinyint(4) DEFAULT NULL COMMENT 'Should we enable the auto-responder?',
  `open_tracking` tinyint(4) DEFAULT NULL COMMENT 'Should we track when recipients open/read this mailing?',
  `is_completed` tinyint(4) DEFAULT NULL COMMENT 'Has at least one job associated with this mailing finished?',
  `msg_template_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to the message template.',
  `override_verp` tinyint(4) DEFAULT '0' COMMENT 'Should we overrite VERP address in Reply-To',
  `created_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to Contact ID who first created this mailing',
  `created_date` datetime DEFAULT NULL COMMENT 'Date and time this mailing was created.',
  `scheduled_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to Contact ID who scheduled this mailing',
  `scheduled_date` datetime DEFAULT NULL COMMENT 'Date and time this mailing was scheduled.',
  `approver_id` int(10) unsigned DEFAULT NULL COMMENT 'FK to Contact ID who approved this mailing',
  `approval_date` datetime DEFAULT NULL COMMENT 'Date and time this mailing was approved.',
  `approval_status_id` int(10) unsigned DEFAULT NULL COMMENT 'The status of this mailing. Values: none, approved, rejected',
  `approval_note` longtext COLLATE utf8_unicode_ci COMMENT 'Note behind the decision.',
  `is_archived` tinyint(4) DEFAULT '0' COMMENT 'Is this mailing archived?',
  `visibility` enum('User and User Admin Only','Public Pages') COLLATE utf8_unicode_ci DEFAULT 'User and User Admin Only' COMMENT 'In what context(s) is the mailing contents visible (online viewing)',
  `campaign_id` int(10) unsigned DEFAULT NULL COMMENT 'The campaign for which this mailing has been initiated.',
  `dedupe_email` tinyint(4) DEFAULT '0' COMMENT 'Remove duplicate emails?',
  `sms_provider_id` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_civicrm_mailing_domain_id` (`domain_id`),
  KEY `FK_civicrm_mailing_header_id` (`header_id`),
  KEY `FK_civicrm_mailing_footer_id` (`footer_id`),
  KEY `FK_civicrm_mailing_reply_id` (`reply_id`),
  KEY `FK_civicrm_mailing_unsubscribe_id` (`unsubscribe_id`),
  KEY `FK_civicrm_mailing_optout_id` (`optout_id`),
  KEY `FK_civicrm_mailing_msg_template_id` (`msg_template_id`),
  KEY `FK_civicrm_mailing_created_id` (`created_id`),
  KEY `FK_civicrm_mailing_scheduled_id` (`scheduled_id`),
  KEY `FK_civicrm_mailing_approver_id` (`approver_id`),
  KEY `FK_civicrm_mailing_campaign_id` (`campaign_id`),
  KEY `FK_civicrm_mailing_sms_provider_id` (`sms_provider_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `0_crm_campaign_outcome_codes` (
  `id_crm_campaign_outcome_codes` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `campaign_outcome_code` varchar(32) NOT NULL,
  `name` varchar(20) NOT NULL,
  `description` varchar(60) NOT NULL,
  `effective_date` date NOT NULL DEFAULT '0000-00-00',
  `end_date` date NOT NULL DEFAULT '0000-00-00',
  `reference` varchar(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id_crm_campaign_outcome_codes`),
  KEY `tran_date` (`effective_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_crm_campaign_persons` (
  `id_crm_campaign_persons` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `crm_outcome_code` varchar(32) NOT NULL,
  `id_crm_persons` int(11) NOT NULL,
  `assigned_date` date NOT NULL,
  `outcome_date` date NOT NULL,
  PRIMARY KEY (`id_crm_campaign_persons`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_crm_campaign_status_codes` (
  `id_crm_campaign_status_codes` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `campaign_status_code` varchar(32) NOT NULL,
  `name` varchar(20) NOT NULL,
  `description` varchar(60) NOT NULL,
  `effective_date` date NOT NULL DEFAULT '0000-00-00',
  `end_date` date NOT NULL DEFAULT '0000-00-00',
  `reference` varchar(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id_crm_campaign_status_codes`),
  KEY `tran_date` (`effective_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_crm_campaign_types` (
  `id_crm_campaign_type` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `campaign_type` varchar(32) NOT NULL,
  `name` varchar(20) NOT NULL,
  `description` varchar(60) NOT NULL,
  `effective_date` date NOT NULL DEFAULT '0000-00-00',
  `end_date` date NOT NULL DEFAULT '0000-00-00',
  `reference` varchar(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id_crm_campaign_type`),
  KEY `tran_date` (`effective_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_crm_campaigns` (
  `id_crm_campaigns` int(11) NOT NULL AUTO_INCREMENT,
  `id_crm_campaign_type` int(11) NOT NULL,
  `action` varchar(20) NOT NULL COMMENT 'detailed usage e.g. department',
  `name` varchar(30) NOT NULL COMMENT 'for category selector',
  `description` tinytext NOT NULL COMMENT 'usage description',
  `Objective` varchar(255) NOT NULL,
  `Start_date` date NOT NULL,
  `End_date` date NOT NULL,
  `target_demographics` varchar(256) NOT NULL,
  `id_crm_campaign_status_code` varchar(16) NOT NULL,
  `id_crm_campaign_outcome_codes` int(11) NOT NULL,
  `id_crm_satisfaction_survey` int(11) NOT NULL,
  PRIMARY KEY (`id_crm_campaigns`),
  UNIQUE KEY `type` (`id_crm_campaign_type`,`action`),
  UNIQUE KEY `type_2` (`id_crm_campaign_type`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_crm_categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'pure technical key',
  `type` varchar(20) NOT NULL COMMENT 'contact type e.g. customer',
  `action` varchar(20) NOT NULL COMMENT 'detailed usage e.g. department',
  `name` varchar(30) NOT NULL COMMENT 'for category selector',
  `description` tinytext NOT NULL COMMENT 'usage description',
  `system` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'nonzero for core system usage',
  `inactive` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `type` (`type`,`action`),
  UNIQUE KEY `type_2` (`type`,`name`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;
CREATE TABLE `0_crm_contacts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `person_id` int(11) NOT NULL DEFAULT '0' COMMENT 'foreign key to crm_contacts',
  `type` varchar(20) NOT NULL COMMENT 'foreign key to crm_categories',
  `action` varchar(20) NOT NULL COMMENT 'foreign key to crm_categories',
  `entity_id` varchar(11) DEFAULT NULL COMMENT 'entity id in related class table',
  PRIMARY KEY (`id`),
  KEY `type` (`type`,`action`)
) ENGINE=InnoDB AUTO_INCREMENT=597 DEFAULT CHARSET=latin1;
CREATE TABLE `0_crm_ical_invite` (
  `idcal_invite` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `method` varchar(45) NOT NULL DEFAULT '',
  `dtstart` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `dtend` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `dtstamp` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `commonname` varchar(45) NOT NULL DEFAULT '',
  `class` varchar(45) NOT NULL DEFAULT '',
  `cutype` varchar(45) NOT NULL DEFAULT '',
  `part` varchar(45) NOT NULL DEFAULT '',
  `role` varchar(45) NOT NULL DEFAULT '',
  `partstat` varchar(45) NOT NULL DEFAULT '',
  `rsvp` varchar(45) NOT NULL DEFAULT '',
  `xnumguests` varchar(45) NOT NULL DEFAULT '',
  `mailto` varchar(45) NOT NULL DEFAULT '',
  `created` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `description` text NOT NULL,
  `lastmodified` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `location` varchar(45) NOT NULL DEFAULT '',
  `sequence` varchar(45) NOT NULL DEFAULT '',
  `status` varchar(45) NOT NULL DEFAULT '',
  `summary` varchar(45) NOT NULL DEFAULT '',
  `invitee` varchar(45) NOT NULL DEFAULT '',
  PRIMARY KEY (`idcal_invite`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_crm_mailinglist` (
  `id_crm_mailinglist` int(11) NOT NULL AUTO_INCREMENT,
  `id_external_mailinglist` int(11) NOT NULL COMMENT 'e.g. phpList',
  `name` varchar(30) NOT NULL COMMENT 'for category selector',
  `description` tinytext NOT NULL COMMENT 'usage description',
  `Objective` varchar(255) NOT NULL,
  `Start_date` date NOT NULL,
  `End_date` date NOT NULL,
  PRIMARY KEY (`id_crm_mailinglist`),
  UNIQUE KEY `type` (`id_external_mailinglist`),
  UNIQUE KEY `type_2` (`id_external_mailinglist`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_crm_mailinglist_persons` (
  `id_crm_mailinglist_persons` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `id_crm_persons` int(11) NOT NULL,
  `authorized_date` date NOT NULL,
  `revoked_date` date NOT NULL,
  `b_authorized` int(11) NOT NULL,
  `id_document_authorize` int(11) NOT NULL,
  `id_document_revoke` int(11) NOT NULL,
  PRIMARY KEY (`id_crm_mailinglist_persons`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_crm_person_details` (
  `id_crm_person_details` int(11) NOT NULL AUTO_INCREMENT,
  `id_crm_campaign_status_code` varchar(30) NOT NULL,
  `website_url` varchar(255) NOT NULL,
  `salutation` varchar(64) DEFAULT NULL,
  `job_title` varchar(64) DEFAULT NULL,
  `department` varchar(64) DEFAULT NULL,
  `homephone` varchar(30) DEFAULT NULL,
  `notes` tinytext NOT NULL,
  `inactive` tinyint(1) NOT NULL DEFAULT '0',
  `became_customer_date` date NOT NULL,
  `id_users` int(11) NOT NULL,
  `id_crm_persons` int(11) NOT NULL,
  `gender` varchar(1) NOT NULL,
  PRIMARY KEY (`id_crm_person_details`),
  KEY `ref` (`id_crm_campaign_status_code`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_crm_persons` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ref` varchar(30) NOT NULL,
  `name` varchar(60) NOT NULL,
  `name2` varchar(60) DEFAULT NULL,
  `address` tinytext,
  `phone` varchar(30) DEFAULT NULL,
  `phone2` varchar(30) DEFAULT NULL,
  `fax` varchar(30) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `lang` char(5) DEFAULT NULL,
  `notes` tinytext NOT NULL,
  `inactive` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `ref` (`ref`)
) ENGINE=InnoDB AUTO_INCREMENT=241 DEFAULT CHARSET=latin1;
CREATE TABLE `0_crm_prefs` (
  `name` varchar(32) NOT NULL DEFAULT '',
  `value` varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
CREATE TABLE `0_crm_satisfaction_survey` (
  `id_crm_satisfaction_survey` int(11) NOT NULL AUTO_INCREMENT,
  `id_limesurvey` int(11) NOT NULL,
  `name` varchar(30) NOT NULL COMMENT 'for category selector',
  `description` tinytext NOT NULL COMMENT 'usage description',
  `Objective` varchar(255) NOT NULL,
  `Start_date` date NOT NULL,
  `End_date` date NOT NULL,
  `target_demographics` varchar(256) NOT NULL,
  `id_crm_campaign_status_code` varchar(16) NOT NULL,
  `id_crm_campaign_outcome_codes` int(11) NOT NULL,
  PRIMARY KEY (`id_crm_satisfaction_survey`),
  UNIQUE KEY `type` (`id_limesurvey`),
  UNIQUE KEY `type_2` (`id_limesurvey`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_hrm_activity_type` (
  `id_crm_activity_type` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `activity_type` varchar(32) NOT NULL,
  `name` varchar(20) NOT NULL,
  `description` varchar(60) NOT NULL,
  `effective_date` date NOT NULL DEFAULT '0000-00-00',
  `end_date` date NOT NULL DEFAULT '0000-00-00',
  `reference` varchar(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id_crm_activity_type`),
  KEY `tran_date` (`effective_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_hrm_benefits` (
  `id_hrm_benefits` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `benefits_code` varchar(32) NOT NULL,
  `name` varchar(20) NOT NULL,
  `description` varchar(60) NOT NULL,
  `effective_date` date NOT NULL DEFAULT '0000-00-00',
  `end_date` date NOT NULL DEFAULT '0000-00-00',
  `reference` varchar(60) NOT NULL DEFAULT '',
  `affiliation_group` varchar(32) NOT NULL,
  `benefits_type` varchar(32) NOT NULL,
  PRIMARY KEY (`id_hrm_benefits`),
  KEY `tran_date` (`effective_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_hrm_benefits_group` (
  `id_hrm_benefits_group` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `benefits_group_code` varchar(32) NOT NULL,
  `name` varchar(20) NOT NULL,
  `description` varchar(60) NOT NULL,
  `effective_date` date NOT NULL DEFAULT '0000-00-00',
  `end_date` date NOT NULL DEFAULT '0000-00-00',
  `reference` varchar(60) NOT NULL DEFAULT '',
  `affiliation_group` varchar(32) NOT NULL,
  PRIMARY KEY (`id_hrm_benefits_group`),
  KEY `tran_date` (`effective_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_hrm_employee` (
  `id_hrm_employee` int(7) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(50) DEFAULT NULL,
  `lastname` varchar(100) NOT NULL,
  `firstname` varchar(100) NOT NULL,
  `middle_name` varchar(100) NOT NULL,
  `nick_name` varchar(100) DEFAULT NULL,
  `ssn` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
  `sin` varchar(100) DEFAULT NULL,
  `status_code` varchar(16) DEFAULT NULL,
  `status_code_effective_date` date NOT NULL,
  `job_title_code` int(7) DEFAULT NULL,
  `eeo_cat_code` int(11) DEFAULT NULL,
  `work_email` varchar(50) DEFAULT NULL,
  `joined_date` date DEFAULT NULL,
  `termination_date` date NOT NULL,
  `vacation_province_code` varchar(16) NOT NULL COMMENT 'Which province rules are used for calculating vacation pay',
  `vacation_tier` int(11) NOT NULL DEFAULT '1' COMMENT 'What vacation pay level',
  `vacation_next_tier_date` date NOT NULL,
  `id_users` int(11) NOT NULL,
  `manager_id` int(11) NOT NULL,
  PRIMARY KEY (`id_hrm_employee`),
  KEY `job_title_code` (`job_title_code`),
  KEY `emp_status` (`status_code`),
  KEY `eeo_cat_code` (`eeo_cat_code`),
  KEY `manager_id` (`manager_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
CREATE TABLE `0_hrm_employee_addresshistory` (
  `id_hrm_employee_addresshistory` int(7) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(50) DEFAULT NULL,
  `emp_lastname` varchar(100) NOT NULL DEFAULT '',
  `emp_firstname` varchar(100) NOT NULL DEFAULT '',
  `emp_middle_name` varchar(100) NOT NULL DEFAULT '',
  `home_street1` varchar(100) DEFAULT NULL,
  `home_street2` varchar(100) DEFAULT NULL,
  `home_city_code` varchar(100) DEFAULT NULL,
  `home_country_code` varchar(100) DEFAULT NULL,
  `home_province_code` varchar(100) DEFAULT NULL,
  `home_zipcode` varchar(20) DEFAULT NULL,
  `home_telephone` varchar(50) DEFAULT NULL,
  `home_mobile` varchar(50) DEFAULT NULL,
  `effective_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `current_address` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_hrm_employee_addresshistory`),
  KEY `termination_id` (`end_date`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
CREATE TABLE `0_hrm_employee_basicpay` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `emp_number` int(7) NOT NULL DEFAULT '0',
  `sal_grd_code` int(11) DEFAULT NULL,
  `currency_id` varchar(6) NOT NULL DEFAULT '',
  `ebsal_basic_salary` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
  `payperiod_code` varchar(13) DEFAULT NULL,
  `salary_component` varchar(100) DEFAULT NULL,
  `comments` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `sal_grd_code` (`sal_grd_code`),
  KEY `currency_id` (`currency_id`),
  KEY `emp_number` (`emp_number`),
  KEY `payperiod_code` (`payperiod_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `0_hrm_employee_details` (
  `id_hrm_employee_details` int(7) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(50) DEFAULT NULL,
  `emp_lastname` varchar(100) NOT NULL DEFAULT '',
  `emp_firstname` varchar(100) NOT NULL DEFAULT '',
  `emp_middle_name` varchar(100) NOT NULL DEFAULT '',
  `emp_nick_name` varchar(100) DEFAULT '',
  `emp_smoker` smallint(6) DEFAULT '0',
  `ethnic_race_code` varchar(13) DEFAULT NULL,
  `emp_birthday` date DEFAULT NULL,
  `nation_code` int(4) DEFAULT NULL,
  `emp_gender` smallint(6) DEFAULT NULL,
  `emp_marital_status` varchar(20) DEFAULT NULL,
  `emp_ssn_num` varchar(100) CHARACTER SET latin1 DEFAULT '',
  `emp_sin_num` varchar(100) DEFAULT '',
  `emp_other_id` varchar(100) DEFAULT '',
  `emp_dri_lice_num` varchar(100) DEFAULT '',
  `emp_dri_lice_exp_date` date DEFAULT NULL,
  `emp_military_service` varchar(100) DEFAULT '',
  `emp_status` int(13) DEFAULT NULL,
  `joined_date` date DEFAULT NULL,
  `emp_oth_email` varchar(50) DEFAULT NULL,
  `termination_id` int(4) DEFAULT NULL,
  PRIMARY KEY (`id_hrm_employee_details`),
  KEY `nation_code` (`nation_code`),
  KEY `emp_status` (`emp_status`),
  KEY `termination_id` (`termination_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
CREATE TABLE `0_hrm_employee_jobhistory` (
  `id_hrm_employee_jobhistory` int(7) NOT NULL AUTO_INCREMENT,
  `id_hrm_employee` int(11) NOT NULL,
  `employee_id` varchar(50) DEFAULT NULL,
  `emp_lastname` varchar(100) NOT NULL DEFAULT '',
  `emp_firstname` varchar(100) NOT NULL DEFAULT '',
  `emp_middle_name` varchar(100) NOT NULL DEFAULT '',
  `active_position` int(11) DEFAULT '0' COMMENT 'Is this their current position',
  `job_title_code` int(7) DEFAULT NULL,
  `eeo_cat_code` int(11) DEFAULT NULL,
  `work_desknumber` varchar(20) DEFAULT NULL,
  `work_street1` varchar(100) DEFAULT NULL,
  `work_street2` varchar(100) DEFAULT NULL,
  `work_city_code` varchar(100) DEFAULT NULL,
  `work_country_code` varchar(100) DEFAULT NULL,
  `work_province_code` varchar(100) DEFAULT NULL,
  `work_zipcode` varchar(20) DEFAULT NULL,
  `work_mobile` varchar(15) DEFAULT NULL,
  `work_telephone` varchar(15) DEFAULT NULL,
  `work_email` varchar(50) DEFAULT NULL,
  `hrm_salary_grade` varchar(16) DEFAULT NULL,
  `effective_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `custom8` varchar(250) DEFAULT NULL,
  `custom9` varchar(250) DEFAULT NULL,
  `custom10` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`id_hrm_employee_jobhistory`),
  KEY `work_station` (`work_desknumber`),
  KEY `job_title_code` (`job_title_code`),
  KEY `emp_status` (`active_position`),
  KEY `eeo_cat_code` (`eeo_cat_code`),
  KEY `termination_id` (`end_date`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
CREATE TABLE `0_hrm_employee_status_code` (
  `id_hrm_employee_status_codes` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `status_code` varchar(32) NOT NULL,
  `name` varchar(20) NOT NULL,
  `description` varchar(60) NOT NULL,
  `effective_date` date NOT NULL DEFAULT '0000-00-00',
  `end_date` date NOT NULL DEFAULT '0000-00-00',
  `reference` varchar(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id_hrm_employee_status_codes`),
  KEY `tran_date` (`effective_date`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=latin1;
CREATE TABLE `0_hrm_job` (
  `id_hrm_job` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `job_code` varchar(32) NOT NULL,
  `name` varchar(20) NOT NULL,
  `description` varchar(60) NOT NULL,
  `effective_date` date NOT NULL DEFAULT '0000-00-00',
  `end_date` date NOT NULL DEFAULT '0000-00-00',
  `reference` varchar(60) NOT NULL DEFAULT '',
  `affiliation_group` varchar(32) NOT NULL,
  `job_type` varchar(32) NOT NULL,
  `b_automatic_salary_increase` int(11) NOT NULL DEFAULT '0',
  `min_salary_increase` int(11) NOT NULL,
  `max_salary_increase` int(11) NOT NULL,
  PRIMARY KEY (`id_hrm_job`),
  KEY `tran_date` (`effective_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_hrm_job_affiliation` (
  `id_hrm_job_affiliation` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `affiliation_group` varchar(32) NOT NULL,
  `name` varchar(20) NOT NULL,
  `description` varchar(60) NOT NULL,
  `effective_date` date NOT NULL DEFAULT '0000-00-00',
  `end_date` date NOT NULL DEFAULT '0000-00-00',
  `reference` varchar(60) NOT NULL DEFAULT '',
  `b_automatic_salary_increase` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_hrm_job_affiliation`),
  KEY `tran_date` (`effective_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_hrm_job_type` (
  `id_hrm_job_type` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `job_type` varchar(32) NOT NULL,
  `name` varchar(20) NOT NULL,
  `description` varchar(60) NOT NULL,
  `effective_date` date NOT NULL DEFAULT '0000-00-00',
  `end_date` date NOT NULL DEFAULT '0000-00-00',
  `reference` varchar(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id_hrm_job_type`),
  KEY `tran_date` (`effective_date`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;
CREATE TABLE `0_hrm_ohrm_timesheet` (
  `timesheet_item_id` bigint(20) NOT NULL,
  `timesheet_id` bigint(20) NOT NULL,
  `date` date NOT NULL,
  `duration` bigint(20) DEFAULT NULL,
  `comment` text,
  `project_id` bigint(20) NOT NULL,
  `id_hrm_employee` int(11) NOT NULL,
  `activity_id` bigint(20) NOT NULL,
  PRIMARY KEY (`timesheet_item_id`),
  KEY `timesheet_id` (`timesheet_id`),
  KEY `activity_id` (`activity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `0_hrm_org` (
  `id_hrm_org` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `org_code` varchar(32) NOT NULL,
  `name` varchar(20) NOT NULL,
  `description` varchar(60) NOT NULL,
  `effective_date` date NOT NULL DEFAULT '0000-00-00',
  `end_date` date NOT NULL DEFAULT '0000-00-00',
  `reference` varchar(60) NOT NULL DEFAULT '',
  `affiliation_group` varchar(32) NOT NULL,
  PRIMARY KEY (`id_hrm_org`),
  KEY `tran_date` (`effective_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_hrm_pay_paycalendar` (
  `id_hrm_pay_paycalendar` int(11) NOT NULL AUTO_INCREMENT,
  `pay_type` varchar(32) NOT NULL,
  `pay_date` date NOT NULL,
  `reference` varchar(60) NOT NULL DEFAULT '',
  `dimension_id` int(11) NOT NULL DEFAULT '0',
  `dimension2_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_hrm_pay_paycalendar`),
  KEY `tran_date` (`pay_date`),
  KEY `Typo` (`pay_type`,`pay_date`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;
CREATE TABLE `0_hrm_pay_payslip` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `year` int(4) NOT NULL,
  `month` int(2) NOT NULL,
  `empl_id` int(10) NOT NULL,
  `basic` int(10) NOT NULL,
  `total_gross_pay` int(11) NOT NULL,
  `total_ded` int(10) NOT NULL,
  `total_net` int(10) NOT NULL,
  `date_of_pay` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_hrm_pay_periods` (
  `id` int(11) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `close_date` date NOT NULL,
  `check_date` date NOT NULL,
  `timesheet_aproval_due_date` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `0_hrm_pay_trans` (
  `id_hrm_pay_trans` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `type` smallint(6) unsigned NOT NULL DEFAULT '0',
  `control_run` int(11) unsigned NOT NULL,
  `id_hrm_employee` int(11) unsigned DEFAULT NULL,
  `branch_code` int(11) NOT NULL DEFAULT '-1',
  `tran_date` date NOT NULL DEFAULT '0000-00-00',
  `reference` varchar(60) NOT NULL DEFAULT '',
  `tpe` int(11) NOT NULL DEFAULT '0',
  `order_` int(11) NOT NULL DEFAULT '0',
  `alloc` double NOT NULL DEFAULT '0',
  `rate` double NOT NULL DEFAULT '1',
  `dimension_id` int(11) NOT NULL DEFAULT '0',
  `dimension2_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_hrm_pay_trans`),
  KEY `debtor_no` (`id_hrm_employee`,`branch_code`),
  KEY `tran_date` (`tran_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_hrm_pay_trans_codes` (
  `id_hrm_pay_trans_codes` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `pay_trans_code` varchar(32) NOT NULL,
  `name` varchar(20) NOT NULL,
  `description` varchar(60) NOT NULL,
  `effective_date` date NOT NULL DEFAULT '0000-00-00',
  `end_date` date NOT NULL DEFAULT '0000-00-00',
  `reference` varchar(60) NOT NULL DEFAULT '',
  `unit_rate` double NOT NULL DEFAULT '1',
  `non_unit_rate` decimal(10,0) NOT NULL DEFAULT '0' COMMENT 'If this is a one rate regardless of units',
  `b_by_unit` int(11) NOT NULL DEFAULT '1' COMMENT 'Is this rate paid by units',
  `b_employee_specific` int(11) NOT NULL DEFAULT '0' COMMENT 'Does the Unit Rate vary depending on employee',
  `b_taxable` int(11) NOT NULL DEFAULT '1',
  `b_pensionable` int(11) NOT NULL DEFAULT '0',
  `gl_type` int(6) NOT NULL,
  `gl_type_number` int(16) NOT NULL,
  `gl_account_debit` varchar(15) NOT NULL,
  `gl_account_credit` varchar(15) NOT NULL,
  PRIMARY KEY (`id_hrm_pay_trans_codes`),
  KEY `tran_date` (`effective_date`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1;
CREATE TABLE `0_hrm_pay_trans_details` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `debtor_trans_no` int(11) DEFAULT NULL,
  `debtor_trans_type` int(11) DEFAULT NULL,
  `stock_id` varchar(20) NOT NULL DEFAULT '',
  `description` tinytext,
  `unit_price` double NOT NULL DEFAULT '0',
  `unit_tax` double NOT NULL DEFAULT '0',
  `quantity` double NOT NULL DEFAULT '0',
  `discount_percent` double NOT NULL DEFAULT '0',
  `standard_cost` double NOT NULL DEFAULT '0',
  `qty_done` double NOT NULL DEFAULT '0',
  `src_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `Transaction` (`debtor_trans_type`,`debtor_trans_no`),
  KEY `src_id` (`src_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_hrm_position` (
  `id_hrm_position` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `position_code` varchar(32) NOT NULL,
  `name` varchar(20) NOT NULL,
  `description` varchar(60) NOT NULL,
  `effective_date` date NOT NULL DEFAULT '0000-00-00',
  `end_date` date NOT NULL DEFAULT '0000-00-00',
  `reference` varchar(60) NOT NULL DEFAULT '',
  `affiliation_group` varchar(32) NOT NULL,
  `id_hrm_job` int(11) NOT NULL,
  `b_automatic_salary_increase` int(11) NOT NULL DEFAULT '0',
  `min_salary_increase` int(11) NOT NULL,
  `max_salary_increase` int(11) NOT NULL,
  `id_hrm_org` int(11) NOT NULL,
  `id_manager_position` int(11) NOT NULL,
  `b_fulltime_ind` int(11) NOT NULL DEFAULT '0',
  `fulltime_percent` int(11) NOT NULL,
  PRIMARY KEY (`id_hrm_position`),
  KEY `tran_date` (`effective_date`),
  KEY `id_hrm_job` (`id_hrm_job`),
  KEY `id_manager_position` (`id_manager_position`),
  KEY `id_hrm_org` (`id_hrm_org`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE `0_hrm_prefs` (
  `name` varchar(32) NOT NULL DEFAULT '',
  `value` varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
CREATE TABLE `0_hrm_timeclock` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `employee_id` bigint(20) NOT NULL,
  `punch_in_utc_time` datetime DEFAULT NULL,
  `punch_in_note` varchar(255) DEFAULT NULL,
  `punch_in_time_offset` varchar(255) DEFAULT NULL,
  `punch_in_user_time` datetime DEFAULT NULL,
  `punch_out_utc_time` datetime DEFAULT NULL,
  `punch_out_note` varchar(255) DEFAULT NULL,
  `punch_out_time_offset` varchar(255) DEFAULT NULL,
  `punch_out_user_time` datetime DEFAULT NULL,
  `state` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `emp_id_state` (`employee_id`,`state`),
  KEY `emp_id_time` (`employee_id`,`punch_in_utc_time`,`punch_out_utc_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `0_hrm_vacation_tiers` (
  `id_hrm_vacation_tiers` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `vacation_province_code` varchar(32) NOT NULL,
  `vacation_tier` int(11) NOT NULL,
  `name` varchar(20) NOT NULL,
  `description` varchar(60) NOT NULL,
  `effective_date` date NOT NULL DEFAULT '0000-00-00',
  `end_date` date NOT NULL DEFAULT '0000-00-00',
  `reference` varchar(60) NOT NULL DEFAULT '',
  `unit_rate` double NOT NULL DEFAULT '1',
  `gl_type` int(6) NOT NULL,
  `gl_type_number` int(16) NOT NULL,
  `gl_account_debit` varchar(15) NOT NULL,
  `gl_account_credit` varchar(15) NOT NULL,
  PRIMARY KEY (`id_hrm_vacation_tiers`),
  KEY `tran_date` (`effective_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
