<?php
/**
 * UI string constants for multilingual readiness.
 */

if (!defined('UI_TEXT_GL_INQUIRY_TITLE')) {
    define('UI_TEXT_GL_INQUIRY_TITLE', 'General Ledger Inquiry');
    define('UI_TEXT_ACCOUNT_LABEL', 'Account:');
    define('UI_TEXT_ALL_ACCOUNTS', 'All Accounts');
    define('UI_TEXT_FROM_LABEL', 'from:');
    define('UI_TEXT_TO_LABEL', 'to:');
    define('UI_TEXT_DIMENSION', 'Dimension');
    define('UI_TEXT_MEMO_PLACEHOLDER', 'Enter memo fragment or leave empty');
    define('UI_TEXT_AMOUNT_MIN', 'Amount min:');
    define('UI_TEXT_AMOUNT_MAX', 'Amount max:');
    define('UI_TEXT_SHOW', 'Show');
    define('UI_TEXT_TYPE', 'Type');
    define('UI_TEXT_NUMBER', '#');
    define('UI_TEXT_REFERENCE', 'Reference');
    define('UI_TEXT_DATE', 'Date');
    define('UI_TEXT_ACCOUNT_COLUMN', 'Account');
    define('UI_TEXT_PERSON_ITEM', 'Person/Item');
    define('UI_TEXT_DEBIT', 'Debit');
    define('UI_TEXT_CREDIT', 'Credit');
    define('UI_TEXT_BALANCE', 'Balance');
    define('UI_TEXT_MEMO', 'Memo');
    define('UI_TEXT_OPENING_BALANCE', 'Opening Balance');
    define('UI_TEXT_ENDING_BALANCE', 'Ending Balance');
    define('UI_TEXT_WARNING_OPENING_MISMATCH', 'The Opening Balance is not in balance, probably due to a non closed Previous Fiscalyear.');
    define('UI_TEXT_GL_LABEL', 'GL');
    define('UI_TEXT_SELECT', 'Select');
    define('UI_TEXT_VOID_TRANSACTION_TITLE', 'Void a Transaction');
    define('UI_TEXT_TRANSACTION_TYPE_LABEL', 'Transaction Type:');
    define('UI_TEXT_SEARCH', 'Search');
    define('UI_TEXT_MARKED_WILL_BE_VOIDED', 'Marked transactions will be voided.');
    define('UI_TEXT_TRANSACTION_NUMBER', 'Transaction #:');
    define('UI_TEXT_VOIDING_DATE', 'Voiding Date:');
    define('UI_TEXT_MEMO_LABEL', 'Memo:');
    define('UI_TEXT_VOID_TRANSACTION_BUTTON', 'Void Transaction');
    define('UI_TEXT_ENTERED_TRANSACTION_NOT_FOUND', 'The entered transaction does not exist or cannot be voided.');
    define('UI_TEXT_INSUFFICIENT_QUANTITY_WARNING', 'The void cannot be processed because there is an insufficient quantity for item:');
    define('UI_TEXT_QUANTITY_ON_HAND', 'Quantity On Hand');
    define('UI_TEXT_VOID_CONFIRMATION', 'Are you sure you want to void this transaction ? This action cannot be undone.');
    define('UI_TEXT_VOID_PROCEED', 'Proceed');
    define('UI_TEXT_CANCEL', 'Cancel');
    define('UI_TEXT_CLOSED_TRANSACTION_ERROR', 'The selected transaction was closed for edition and cannot be voided.');
    define('UI_TEXT_INVALID_DATE_ERROR', 'The entered date is invalid.');
    define('UI_TEXT_DATE_OUT_OF_FISCAL_YEAR_ERROR', 'The entered date is out of fiscal year or is closed for further data entry.');
    define('UI_TEXT_NUMERIC_TRANSACTION_NUMBER_ERROR', 'The transaction number is expected to be numeric and greater than zero.');
    define('UI_TEXT_ALREADY_VOIDED_ERROR', 'The selected transaction has already been voided.');
    define('UI_TEXT_TRANSACTION_VOIDED_NOTICE', 'Selected transaction has been voided.');
    define('UI_TEXT_REFERENCE_COLUMN', 'Reference');
    define('UI_TEXT_DATE_COLUMN', 'Date');
    define('UI_TEXT_NUMBER_COLUMN', '#');
    define('UI_TEXT_NA', 'N/A');
    define('UI_TEXT_PRINT', 'Print');
    define('UI_TEXT_ONLY_DOCUMENTS_PRINTABLE', 'Only documents can be printed.');
    define('UI_TEXT_TYPE_LABEL', 'Type:');
    define('UI_TEXT_FROM_NUMBER', 'from #:');
    define('UI_TEXT_TO_NUMBER', 'to #:');
    define('UI_TEXT_START_TRANS_NUMERIC_ERROR', 'The starting transaction number is expected to be numeric and greater than zero.');
    define('UI_TEXT_END_TRANS_NUMERIC_ERROR', 'The ending transaction number is expected to be numeric and greater than zero.');
    define('UI_TEXT_VIEW_PRINT_TRANSACTIONS_TITLE', 'View or Print Transactions');
    define('UI_TEXT_UNSPECIFIED_TAG_TYPE', 'Unspecified tag type');
    define('UI_TEXT_TAG_NAME_EMPTY_ERROR', 'The tag name cannot be empty.');
    define('UI_TEXT_CANNOT_DELETE_TAG_ERROR', 'Cannot delete this tag because records have been created referring to it.');
    define('UI_TEXT_TAG_NAME', 'Tag Name');
    define('UI_TEXT_TAG_DESCRIPTION', 'Tag Description');
    define('UI_TEXT_EDIT', 'Edit');
    define('UI_TEXT_DELETE', 'Delete');
    define('UI_TEXT_ACCOUNT_TAGS_TITLE', 'Account Tags');
    define('UI_TEXT_DIMENSION_TAGS_TITLE', 'Dimension Tags');
    define('UI_TEXT_TAG_NAME_LABEL', 'Tag Name:');
    define('UI_TEXT_TAG_DESCRIPTION_LABEL', 'Tag Description:');
    define('UI_TEXT_USERS_TITLE', 'Users');
    define('UI_TEXT_USER_LOGIN_TOO_SHORT_ERROR', 'The user login entered must be at least 4 characters long.');
    define('UI_TEXT_PASSWORD_TOO_SHORT_ERROR', 'The password entered must be at least 4 characters long.');
    define('UI_TEXT_PASSWORD_CONTAINS_LOGIN_ERROR', 'The password cannot contain the user login.');
    define('UI_TEXT_USER_UPDATED_NOTICE', 'The selected user has been updated.');
    define('UI_TEXT_USER_ADDED_NOTICE', 'A new user has been added.');
    define('UI_TEXT_CANNOT_DELETE_USER_ERROR', 'Cannot delete this user because entries are associated with this user.');
    define('UI_TEXT_USER_DELETED_NOTICE', 'User has been deleted.');
    define('UI_TEXT_USER_LOGIN', 'User login');
    define('UI_TEXT_FULL_NAME', 'Full Name');
    define('UI_TEXT_PHONE', 'Phone');
    define('UI_TEXT_EMAIL', 'E-mail');
    define('UI_TEXT_LAST_VISIT', 'Last Visit');
    define('UI_TEXT_ACCESS_LEVEL', 'Access Level');
    define('UI_TEXT_USER_LOGIN_LABEL', 'User login:');
    define('UI_TEXT_PASSWORD_LABEL', 'Password:');
    define('UI_TEXT_ENTER_NEW_PASSWORD_INSTRUCTION', 'Enter a new password to change, leave empty to keep current.');
    define('UI_TEXT_TELEPHONE_LABEL', 'Telephone No.:');
    define('UI_TEXT_EMAIL_ADDRESS_LABEL', 'Email Address:');
    define('UI_TEXT_LANGUAGE_LABEL', 'Language:');
    define('UI_TEXT_USERS_POS_LABEL', "User's POS:");
    define('UI_TEXT_PRINTING_PROFILE_LABEL', 'Printing profile:');
    define('UI_TEXT_USE_POPUP_WINDOW_LABEL', 'Use popup window for reports:');
    define('UI_TEXT_BROWSER_PRINTING_SUPPORT', 'Browser printing support');
    define('UI_TEXT_POPUP_WINDOW_INSTRUCTION', 'Set this option to on if your browser directly supports pdf files');
    define('UI_TEXT_COMPANY_SETUP_TITLE', 'Company Setup');
    define('UI_TEXT_LOGIN_TIMEOUT_ERROR', 'Login timeout must be positive number not less than 10.');
    define('UI_TEXT_COMPANY_NAME_REQUIRED_ERROR', 'The company name must be entered.');
    define('UI_TEXT_TAX_PERIODS_ERROR', 'Tax Periods must be positive number.');
    define('UI_TEXT_TAX_LAST_PERIODS_ERROR', 'Tax Last Periods must be positive number.');
    define('UI_TEXT_ROUND_CALCULATED_ERROR', 'Round Calculated field must be a positive number.');
    define('UI_TEXT_MAX_DAY_RANGE_ERROR', 'Max day range in Documents must be a positive number.');
    define('UI_TEXT_ADD_PRICE_FROM_STD_COST_ERROR', 'Add Price from Std Cost field must be number.');
    define('UI_TEXT_COMPANY_SETUP_UPDATED_NOTICE', 'Company setup has been updated.');
    define('UI_TEXT_GENERAL_SETTINGS', 'General settings');
    define('UI_TEXT_COMPANY_NAME_LABEL', 'Name (to appear on reports):');
    define('UI_TEXT_ADDRESS_LABEL', 'Address:');
    define('UI_TEXT_DOMICILE_LABEL', 'Domicile:');
    define('UI_TEXT_PHONE_NUMBER_LABEL', 'Phone Number:');
    define('UI_TEXT_FAX_NUMBER_LABEL', 'Fax Number:');
    define('UI_TEXT_BCC_EMAIL_LABEL', 'BCC Address for all outgoing mails:');
    define('UI_TEXT_OFFICIAL_COMPANY_NUMBER_LABEL', 'Official Company Number:');
    define('UI_TEXT_GST_NO_LABEL', 'GSTNo:');
    define('UI_TEXT_HOME_CURRENCY_LABEL', 'Home Currency:');
    define('UI_TEXT_COMPANY_LOGO_LABEL', 'Company Logo:');
    define('UI_TEXT_NEW_COMPANY_LOGO_LABEL', 'New Company Logo (.jpg)');
    define('UI_TEXT_DELETE_COMPANY_LOGO_LABEL', 'Delete Company Logo:');
    define('UI_TEXT_TIME_ZONE_ON_REPORTS_LABEL', 'Time Zone on Reports');
    define('UI_TEXT_COMPANY_LOGO_ON_REPORTS_LABEL', 'Company Logo on Reports');
    define('UI_TEXT_FILE_SIZE_OVER_MAX_ERROR', 'The file size is over the maximum allowed.');
    define('UI_TEXT_USE_BARCODES_ON_STOCKS_LABEL', 'Use Barcodes on Stocks');
    define('UI_TEXT_AUTO_INCREASE_DOC_REFS_LABEL', 'Auto Increase of Document References');
    define('UI_TEXT_USE_DIMENSIONS_ON_RECURRENT_INVOICES_LABEL', 'Use Dimensions on Recurrent Invoices');
    define('UI_TEXT_USE_LONG_DESCRIPTIONS_ON_INVOICES_LABEL', 'Use Long Descriptions on Invoices');
    define('UI_TEXT_COMPANY_LOGO_ON_VIEWS_LABEL', 'Company Logo on Views');
    define('UI_TEXT_DATABASE_SCHEME_VERSION_LABEL', 'Database Scheme Version');
    define('UI_TEXT_GENERAL_LEDGER_SETTINGS', 'General Ledger Settings');
    define('UI_TEXT_FISCAL_YEAR_LABEL', 'Fiscal Year:');
    define('UI_TEXT_TAX_PERIODS_LABEL', 'Tax Periods:');
    define('UI_TEXT_MONTHS', 'Months.');
    define('UI_TEXT_TAX_LAST_PERIOD_LABEL', 'Tax Last Period:');
    define('UI_TEXT_MONTHS_BACK', 'Months back.');
    define('UI_TEXT_PUT_ALTERNATIVE_TAX_INCLUDE_ON_DOCS_LABEL', 'Put alternative Tax Include on Docs');
    define('UI_TEXT_SUPPRESS_TAX_RATES_ON_DOCS_LABEL', 'Suppress Tax Rates on Docs');
    define('UI_TEXT_AUTOMATIC_REVALUATION_CURRENCY_ACCOUNTS_LABEL', 'Automatic Revaluation Currency Accounts');
    define('UI_TEXT_SALES_PRICING', 'Sales Pricing');
    define('UI_TEXT_BASE_FOR_AUTO_PRICE_CALCULATIONS_LABEL', 'Base for auto price calculations:');
    define('UI_TEXT_ADD_PRICE_FROM_STD_COST_LABEL', 'Add Price from Std Cost:');
    define('UI_TEXT_ROUND_CALCULATED_PRICES_LABEL', 'Round calculated prices to nearest:');
    define('UI_TEXT_OPTIONAL_MODULES', 'Optional Modules');
    define('UI_TEXT_MANUFACTURING_LABEL', 'Manufacturing');
    define('UI_TEXT_FIXED_ASSETS_LABEL', 'Fixed Assets');
    define('UI_TEXT_USE_DIMENSIONS_LABEL', 'Use Dimensions:');
    define('UI_TEXT_ERROR_UPLOADING_LOGO_FILE', 'Error uploading logo file.');
    define('UI_TEXT_NO_BASE_PRICE_LIST', 'No base price list');
    define('UI_TEXT_USER_INTERFACE_OPTIONS', 'User Interface Options');
    define('UI_TEXT_SHORT_NAME_AND_NAME_IN_LIST_LABEL', 'Short Name and Name in List');
    define('UI_TEXT_OPEN_PRINT_DIALOG_DIRECT_ON_REPORTS_LABEL', 'Open Print Dialog Direct on Reports');
    define('UI_TEXT_SEARCH_ITEM_LIST_LABEL', 'Search Item List');
    define('UI_TEXT_SEARCH_CUSTOMER_LIST_LABEL', 'Search Customer List');
    define('UI_TEXT_SEARCH_SUPPLIER_LIST_LABEL', 'Search Supplier List');
    define('UI_TEXT_LOGIN_TIMEOUT_LABEL', 'Login Timeout:');
    define('UI_TEXT_SECONDS', 'seconds');
    define('UI_TEXT_MAX_DAY_RANGE_IN_DOCUMENTS_LABEL', 'Max day range in documents');
    define('UI_TEXT_DAYS', 'days.');
    define('UI_TEXT_UPDATE_BUTTON', 'Update');
    define('UI_TEXT_ACCESS_SETUP_TITLE', 'Access setup');
    define('UI_TEXT_ROLE_DESCRIPTION_EMPTY_ERROR', 'Role description cannot be empty.');
    define('UI_TEXT_ROLE_NAME_EMPTY_ERROR', 'Role name cannot be empty.');
    define('UI_TEXT_ACCESS_LEVEL_EDITION_DISABLED_ERROR', 'Access level edition in Company setup section have to be enabled for your account.');
    define('UI_TEXT_NEW_SECURITY_ROLE_ADDED_NOTICE', 'New security role has been added.');
    define('UI_TEXT_SECURITY_ROLE_UPDATED_NOTICE', 'Security role has been updated.');
    define('UI_TEXT_ROLE_ASSIGNED_CANNOT_DELETE_ERROR', 'This role is currently assigned to some users and cannot be deleted');
    define('UI_TEXT_SECURITY_ROLE_DELETED_NOTICE', 'Security role has been sucessfully deleted.');
    define('UI_TEXT_ROLE_LABEL', 'Role:');
    define('UI_TEXT_SHOW_INACTIVE_LABEL', 'Show inactive:');
    define('UI_TEXT_ROLE_NAME_LABEL', 'Role name:');
    define('UI_TEXT_ROLE_DESCRIPTION_LABEL', 'Role description:');
    define('UI_TEXT_CURRENT_STATUS_LABEL', 'Current status:');
    define('UI_TEXT_ON_OFF_SET_OF_FEATURES', 'On/off set of features');
    define('UI_TEXT_UPDATE_VIEW_BUTTON', 'Update view');
    define('UI_TEXT_INSERT_NEW_ROLE_BUTTON', 'Insert New Role');
    define('UI_TEXT_SAVE_ROLE_BUTTON', 'Save Role');
    define('UI_TEXT_CLONE_THIS_ROLE_BUTTON', 'Clone This Role');
    define('UI_TEXT_DELETE_THIS_ROLE_BUTTON', 'Delete This Role');
    define('UI_TEXT_CANCEL_EDITION', 'Cancel Edition');
}
