<?php
/**
 * UI string constants for multilingual readiness.
 */

if (!defined('UI_TEXT_GL_INQUIRY_TITLE')) {
    define('UI_TEXT_GL_INQUIRY_TITLE', 'General Ledger Inquiry');
    define('UI_TEXT_ACCOUNT_LABEL', 'Account:');
    define('UI_TEXT_ALL_ACCOUNTS', 'All Accounts');
    define('UI_TEXT_FROM_LABEL', 'from:');
    define('UI_TEXT_TO_LABEL', 'to:');
    define('UI_TEXT_DIMENSION', 'Dimension');
    define('UI_TEXT_MEMO_PLACEHOLDER', 'Enter memo fragment or leave empty');
    define('UI_TEXT_AMOUNT_MIN', 'Amount min:');
    define('UI_TEXT_AMOUNT_MAX', 'Amount max:');
    define('UI_TEXT_SHOW', 'Show');
    define('UI_TEXT_TYPE', 'Type');
    define('UI_TEXT_NUMBER', '#');
    define('UI_TEXT_REFERENCE', 'Reference');
    define('UI_TEXT_DATE', 'Date');
    define('UI_TEXT_ACCOUNT_COLUMN', 'Account');
    define('UI_TEXT_PERSON_ITEM', 'Person/Item');
    define('UI_TEXT_DEBIT', 'Debit');
    define('UI_TEXT_CREDIT', 'Credit');
    define('UI_TEXT_BALANCE', 'Balance');
    define('UI_TEXT_MEMO', 'Memo');
    define('UI_TEXT_OPENING_BALANCE', 'Opening Balance');
    define('UI_TEXT_ENDING_BALANCE', 'Ending Balance');
    define('UI_TEXT_WARNING_OPENING_MISMATCH', 'The Opening Balance is not in balance, probably due to a non closed Previous Fiscalyear.');
    define('UI_TEXT_GL_LABEL', 'GL');
    define('UI_TEXT_SELECT', 'Select');
    define('UI_TEXT_VOID_TRANSACTION_TITLE', 'Void a Transaction');
    define('UI_TEXT_TRANSACTION_TYPE_LABEL', 'Transaction Type:');
    define('UI_TEXT_SEARCH', 'Search');
    define('UI_TEXT_MARKED_WILL_BE_VOIDED', 'Marked transactions will be voided.');
    define('UI_TEXT_TRANSACTION_NUMBER', 'Transaction #:');
    define('UI_TEXT_VOIDING_DATE', 'Voiding Date:');
    define('UI_TEXT_MEMO_LABEL', 'Memo:');
    define('UI_TEXT_VOID_TRANSACTION_BUTTON', 'Void Transaction');
    define('UI_TEXT_ENTERED_TRANSACTION_NOT_FOUND', 'The entered transaction does not exist or cannot be voided.');
    define('UI_TEXT_INSUFFICIENT_QUANTITY_WARNING', 'The void cannot be processed because there is an insufficient quantity for item:');
    define('UI_TEXT_QUANTITY_ON_HAND', 'Quantity On Hand');
    define('UI_TEXT_VOID_CONFIRMATION', 'Are you sure you want to void this transaction ? This action cannot be undone.');
    define('UI_TEXT_VOID_PROCEED', 'Proceed');
    define('UI_TEXT_CANCEL', 'Cancel');
    define('UI_TEXT_CLOSED_TRANSACTION_ERROR', 'The selected transaction was closed for edition and cannot be voided.');
    define('UI_TEXT_INVALID_DATE_ERROR', 'The entered date is invalid.');
    define('UI_TEXT_DATE_OUT_OF_FISCAL_YEAR_ERROR', 'The entered date is out of fiscal year or is closed for further data entry.');
    define('UI_TEXT_NUMERIC_TRANSACTION_NUMBER_ERROR', 'The transaction number is expected to be numeric and greater than zero.');
    define('UI_TEXT_ALREADY_VOIDED_ERROR', 'The selected transaction has already been voided.');
    define('UI_TEXT_TRANSACTION_VOIDED_NOTICE', 'Selected transaction has been voided.');
    define('UI_TEXT_REFERENCE_COLUMN', 'Reference');
    define('UI_TEXT_DATE_COLUMN', 'Date');
    define('UI_TEXT_NUMBER_COLUMN', '#');
    define('UI_TEXT_NA', 'N/A');
    define('UI_TEXT_PRINT', 'Print');
    define('UI_TEXT_ONLY_DOCUMENTS_PRINTABLE', 'Only documents can be printed.');
    define('UI_TEXT_TYPE_LABEL', 'Type:');
    define('UI_TEXT_FROM_NUMBER', 'from #:');
    define('UI_TEXT_TO_NUMBER', 'to #:');
    define('UI_TEXT_START_TRANS_NUMERIC_ERROR', 'The starting transaction number is expected to be numeric and greater than zero.');
    define('UI_TEXT_END_TRANS_NUMERIC_ERROR', 'The ending transaction number is expected to be numeric and greater than zero.');
    define('UI_TEXT_VIEW_PRINT_TRANSACTIONS_TITLE', 'View or Print Transactions');
    define('UI_TEXT_UNSPECIFIED_TAG_TYPE', 'Unspecified tag type');
    define('UI_TEXT_TAG_NAME_EMPTY_ERROR', 'The tag name cannot be empty.');
    define('UI_TEXT_CANNOT_DELETE_TAG_ERROR', 'Cannot delete this tag because records have been created referring to it.');
    define('UI_TEXT_TAG_NAME', 'Tag Name');
    define('UI_TEXT_TAG_DESCRIPTION', 'Tag Description');
    define('UI_TEXT_EDIT', 'Edit');
    define('UI_TEXT_DELETE', 'Delete');
    define('UI_TEXT_ACCOUNT_TAGS_TITLE', 'Account Tags');
    define('UI_TEXT_DIMENSION_TAGS_TITLE', 'Dimension Tags');
    define('UI_TEXT_TAG_NAME_LABEL', 'Tag Name:');
    define('UI_TEXT_TAG_DESCRIPTION_LABEL', 'Tag Description:');
    define('UI_TEXT_USERS_TITLE', 'Users');
    define('UI_TEXT_USER_LOGIN_TOO_SHORT_ERROR', 'The user login entered must be at least 4 characters long.');
    define('UI_TEXT_PASSWORD_TOO_SHORT_ERROR', 'The password entered must be at least 4 characters long.');
    define('UI_TEXT_PASSWORD_CONTAINS_LOGIN_ERROR', 'The password cannot contain the user login.');
    define('UI_TEXT_USER_UPDATED_NOTICE', 'The selected user has been updated.');
    define('UI_TEXT_USER_ADDED_NOTICE', 'A new user has been added.');
    define('UI_TEXT_CANNOT_DELETE_USER_ERROR', 'Cannot delete this user because entries are associated with this user.');
    define('UI_TEXT_USER_DELETED_NOTICE', 'User has been deleted.');
    define('UI_TEXT_USER_LOGIN', 'User login');
    define('UI_TEXT_FULL_NAME', 'Full Name');
    define('UI_TEXT_PHONE', 'Phone');
    define('UI_TEXT_EMAIL', 'E-mail');
    define('UI_TEXT_LAST_VISIT', 'Last Visit');
    define('UI_TEXT_ACCESS_LEVEL', 'Access Level');
    define('UI_TEXT_USER_LOGIN_LABEL', 'User login:');
    define('UI_TEXT_PASSWORD_LABEL', 'Password:');
    define('UI_TEXT_ENTER_NEW_PASSWORD_INSTRUCTION', 'Enter a new password to change, leave empty to keep current.');
    define('UI_TEXT_TELEPHONE_LABEL', 'Telephone No.:');
    define('UI_TEXT_EMAIL_ADDRESS_LABEL', 'Email Address:');
    define('UI_TEXT_LANGUAGE_LABEL', 'Language:');
    define('UI_TEXT_USERS_POS_LABEL', "User's POS:");
    define('UI_TEXT_PRINTING_PROFILE_LABEL', 'Printing profile:');
    define('UI_TEXT_USE_POPUP_WINDOW_LABEL', 'Use popup window for reports:');
    define('UI_TEXT_BROWSER_PRINTING_SUPPORT', 'Browser printing support');
    define('UI_TEXT_POPUP_WINDOW_INSTRUCTION', 'Set this option to on if your browser directly supports pdf files');
    define('UI_TEXT_COMPANY_SETUP_TITLE', 'Company Setup');
    define('UI_TEXT_LOGIN_TIMEOUT_ERROR', 'Login timeout must be positive number not less than 10.');
    define('UI_TEXT_COMPANY_NAME_REQUIRED_ERROR', 'The company name must be entered.');
    define('UI_TEXT_TAX_PERIODS_ERROR', 'Tax Periods must be positive number.');
    define('UI_TEXT_TAX_LAST_PERIODS_ERROR', 'Tax Last Periods must be positive number.');
    define('UI_TEXT_ROUND_CALCULATED_ERROR', 'Round Calculated field must be a positive number.');
    define('UI_TEXT_MAX_DAY_RANGE_ERROR', 'Max day range in Documents must be a positive number.');
    define('UI_TEXT_ADD_PRICE_FROM_STD_COST_ERROR', 'Add Price from Std Cost field must be number.');
    define('UI_TEXT_COMPANY_SETUP_UPDATED_NOTICE', 'Company setup has been updated.');
    define('UI_TEXT_GENERAL_SETTINGS', 'General settings');
    define('UI_TEXT_COMPANY_NAME_LABEL', 'Name (to appear on reports):');
    define('UI_TEXT_ADDRESS_LABEL', 'Address:');
    define('UI_TEXT_DOMICILE_LABEL', 'Domicile:');
    define('UI_TEXT_PHONE_NUMBER_LABEL', 'Phone Number:');
    define('UI_TEXT_FAX_NUMBER_LABEL', 'Fax Number:');
    define('UI_TEXT_BCC_EMAIL_LABEL', 'BCC Address for all outgoing mails:');
    define('UI_TEXT_OFFICIAL_COMPANY_NUMBER_LABEL', 'Official Company Number:');
    define('UI_TEXT_GST_NO_LABEL', 'GSTNo:');
    define('UI_TEXT_HOME_CURRENCY_LABEL', 'Home Currency:');
    define('UI_TEXT_COMPANY_LOGO_LABEL', 'Company Logo:');
    define('UI_TEXT_NEW_COMPANY_LOGO_LABEL', 'New Company Logo (.jpg)');
    define('UI_TEXT_DELETE_COMPANY_LOGO_LABEL', 'Delete Company Logo:');
    define('UI_TEXT_TIME_ZONE_ON_REPORTS_LABEL', 'Time Zone on Reports');
    define('UI_TEXT_COMPANY_LOGO_ON_REPORTS_LABEL', 'Company Logo on Reports');
    define('UI_TEXT_FILE_SIZE_OVER_MAX_ERROR', 'The file size is over the maximum allowed.');
    define('UI_TEXT_USE_BARCODES_ON_STOCKS_LABEL', 'Use Barcodes on Stocks');
    define('UI_TEXT_AUTO_INCREASE_DOC_REFS_LABEL', 'Auto Increase of Document References');
    define('UI_TEXT_USE_DIMENSIONS_ON_RECURRENT_INVOICES_LABEL', 'Use Dimensions on Recurrent Invoices');
    define('UI_TEXT_USE_LONG_DESCRIPTIONS_ON_INVOICES_LABEL', 'Use Long Descriptions on Invoices');
    define('UI_TEXT_COMPANY_LOGO_ON_VIEWS_LABEL', 'Company Logo on Views');
    define('UI_TEXT_DATABASE_SCHEME_VERSION_LABEL', 'Database Scheme Version');
    define('UI_TEXT_GENERAL_LEDGER_SETTINGS', 'General Ledger Settings');
    define('UI_TEXT_FISCAL_YEAR_LABEL', 'Fiscal Year:');
    define('UI_TEXT_TAX_PERIODS_LABEL', 'Tax Periods:');
    define('UI_TEXT_MONTHS', 'Months.');
    define('UI_TEXT_TAX_LAST_PERIOD_LABEL', 'Tax Last Period:');
    define('UI_TEXT_MONTHS_BACK', 'Months back.');
    define('UI_TEXT_PUT_ALTERNATIVE_TAX_INCLUDE_ON_DOCS_LABEL', 'Put alternative Tax Include on Docs');
    define('UI_TEXT_SUPPRESS_TAX_RATES_ON_DOCS_LABEL', 'Suppress Tax Rates on Docs');
    define('UI_TEXT_AUTOMATIC_REVALUATION_CURRENCY_ACCOUNTS_LABEL', 'Automatic Revaluation Currency Accounts');
    define('UI_TEXT_SALES_PRICING', 'Sales Pricing');
    define('UI_TEXT_BASE_FOR_AUTO_PRICE_CALCULATIONS_LABEL', 'Base for auto price calculations:');
    define('UI_TEXT_ADD_PRICE_FROM_STD_COST_LABEL', 'Add Price from Std Cost:');
    define('UI_TEXT_ROUND_CALCULATED_PRICES_LABEL', 'Round calculated prices to nearest:');
    define('UI_TEXT_OPTIONAL_MODULES', 'Optional Modules');
    define('UI_TEXT_MANUFACTURING_LABEL', 'Manufacturing');
    define('UI_TEXT_FIXED_ASSETS_LABEL', 'Fixed Assets');
    define('UI_TEXT_USE_DIMENSIONS_LABEL', 'Use Dimensions:');
    define('UI_TEXT_ERROR_UPLOADING_LOGO_FILE', 'Error uploading logo file.');
    define('UI_TEXT_NO_BASE_PRICE_LIST', 'No base price list');
    define('UI_TEXT_USER_INTERFACE_OPTIONS', 'User Interface Options');
    define('UI_TEXT_SHORT_NAME_AND_NAME_IN_LIST_LABEL', 'Short Name and Name in List');
    define('UI_TEXT_OPEN_PRINT_DIALOG_DIRECT_ON_REPORTS_LABEL', 'Open Print Dialog Direct on Reports');
    define('UI_TEXT_SEARCH_ITEM_LIST_LABEL', 'Search Item List');
    define('UI_TEXT_SEARCH_CUSTOMER_LIST_LABEL', 'Search Customer List');
    define('UI_TEXT_SEARCH_SUPPLIER_LIST_LABEL', 'Search Supplier List');
    define('UI_TEXT_LOGIN_TIMEOUT_LABEL', 'Login Timeout:');
    define('UI_TEXT_SECONDS', 'seconds');
    define('UI_TEXT_MAX_DAY_RANGE_IN_DOCUMENTS_LABEL', 'Max day range in documents');
    define('UI_TEXT_DAYS', 'days.');
    define('UI_TEXT_UPDATE_BUTTON', 'Update');
    define('UI_TEXT_ACCESS_SETUP_TITLE', 'Access setup');
    define('UI_TEXT_ROLE_DESCRIPTION_EMPTY_ERROR', 'Role description cannot be empty.');
    define('UI_TEXT_ROLE_NAME_EMPTY_ERROR', 'Role name cannot be empty.');
    define('UI_TEXT_ACCESS_LEVEL_EDITION_DISABLED_ERROR', 'Access level edition in Company setup section have to be enabled for your account.');
    define('UI_TEXT_NEW_SECURITY_ROLE_ADDED_NOTICE', 'New security role has been added.');
    define('UI_TEXT_SECURITY_ROLE_UPDATED_NOTICE', 'Security role has been updated.');
    define('UI_TEXT_ROLE_ASSIGNED_CANNOT_DELETE_ERROR', 'This role is currently assigned to some users and cannot be deleted');
    define('UI_TEXT_SECURITY_ROLE_DELETED_NOTICE', 'Security role has been sucessfully deleted.');
    define('UI_TEXT_ROLE_LABEL', 'Role:');
    define('UI_TEXT_SHOW_INACTIVE_LABEL', 'Show inactive:');
    define('UI_TEXT_ROLE_NAME_LABEL', 'Role name:');
    define('UI_TEXT_ROLE_DESCRIPTION_LABEL', 'Role description:');
    define('UI_TEXT_CURRENT_STATUS_LABEL', 'Current status:');
    define('UI_TEXT_ON_OFF_SET_OF_FEATURES', 'On/off set of features');
    define('UI_TEXT_UPDATE_VIEW_BUTTON', 'Update view');
    define('UI_TEXT_INSERT_NEW_ROLE_BUTTON', 'Insert New Role');
    define('UI_TEXT_SAVE_ROLE_BUTTON', 'Save Role');
    define('UI_TEXT_CLONE_THIS_ROLE_BUTTON', 'Clone This Role');
    define('UI_TEXT_DELETE_THIS_ROLE_BUTTON', 'Delete This Role');
    define('UI_TEXT_CANCEL_EDITION', 'Cancel Edition');
    define('UI_TEXT_PRINTER_LOCATIONS_TITLE', 'Printer Locations');
    define('UI_TEXT_PRINTER_NAME_EMPTY_ERROR', 'Printer name cannot be empty.');
    define('UI_TEXT_PRINTING_TO_SERVER_AT_USER_IP_NOTICE', 'You have selected printing to server at user IP.');
    define('UI_TEXT_TIMEOUT_INVALID_ERROR', 'Timeout cannot be less than zero nor longer than 60 (sec).');
    define('UI_TEXT_CANNOT_DELETE_PRINTER_ERROR', 'Cannot delete this printer definition, because print profile have been created using it.');
    define('UI_TEXT_NAME', 'Name');
    define('UI_TEXT_DESCRIPTION', 'Description');
    define('UI_TEXT_HOST', 'Host');
    define('UI_TEXT_PRINTER_QUEUE', 'Printer Queue');
    define('UI_TEXT_PRINTER_NAME', 'Printer Name');
    define('UI_TEXT_PRINTER_DESCRIPTION', 'Printer Description');
    define('UI_TEXT_HOST_NAME_OR_IP', 'Host name or IP');
    define('UI_TEXT_PORT', 'Port');
    define('UI_TEXT_TIMEOUT', 'Timeout');
    define('UI_TEXT_SELECTED_PRINTER_DELETED_NOTICE', 'Selected printer definition has been deleted');
    define('UI_TEXT_FISCAL_YEARS_TITLE', 'Fiscal Years');
    define('UI_TEXT_INVALID_BEGIN_DATE_ERROR', 'Invalid BEGIN date in fiscal year.');
    define('UI_TEXT_INVALID_END_DATE_ERROR', 'Invalid END date in fiscal year.');
    define('UI_TEXT_INVALID_BEGIN_OR_END_DATE_ERROR', 'Invalid BEGIN or END date in fiscal year.');
    define('UI_TEXT_BEGIN_DATE_BIGGER_THAN_END_ERROR', 'BEGIN date bigger than END date.');
    define('UI_TEXT_CANNOT_CLOSE_YEAR_ERROR', 'Cannot CLOSE this year because there are open fiscal years before');
    define('UI_TEXT_CANNOT_DELETE_FISCAL_YEAR_BEFORE_ERROR', 'Cannot delete this fiscal year because there are fiscal years before.');
    define('UI_TEXT_CANNOT_DELETE_FISCAL_YEAR_NOT_CLOSED_ERROR', 'Cannot delete this fiscal year because the fiscal year is not closed.');
    define('UI_TEXT_WARNING_DELETING_FISCAL_YEAR', 'Warning: Deleting a fiscal year all transactions');
    define('UI_TEXT_FISCAL_YEAR_BEGIN', 'Fiscal Year Begin');
    define('UI_TEXT_FISCAL_YEAR_END', 'Fiscal Year End');
    define('UI_TEXT_CLOSED', 'Closed');
    define('UI_TEXT_NO', 'No');
    define('UI_TEXT_YES', 'Yes');
    define('UI_TEXT_CONFIRM_DELETE_FISCAL_YEAR', 'Are you sure you want to delete fiscal year %s - %s? All transactions are deleted and converted into relevant balances. Do you want to continue ?');
    define('UI_TEXT_CURRENT_FISCAL_YEAR_CANNOT_DELETE', 'The marked fiscal year is the current fiscal year which cannot be deleted.');
    define('UI_TEXT_FISCAL_YEAR_BEGIN_LABEL', 'Fiscal Year Begin:');
    define('UI_TEXT_FISCAL_YEAR_END_LABEL', 'Fiscal Year End:');
    define('UI_TEXT_PRINTING_PROFILE_NAME_CANNOT_BE_EMPTY_ERROR', 'Printing profile name cannot be empty.');
    define('UI_TEXT_PRINTING_PROFILE_NAME_LABEL', 'Printing Profile Name');
    define('UI_TEXT_REPORT_ID', 'Report Id');
    define('UI_TEXT_PRINTER', 'Printer');
    define('UI_TEXT_NO_TITLE_FOUND_IN_REPORT_DEFINITION', 'no title was found in this report definition file.');
    define('UI_TEXT_ADD_NEW_PROFILE', 'Add New Profile');
    define('UI_TEXT_UPDATE_PROFILE', 'Update Profile');
    define('UI_TEXT_DELETE_PROFILE', 'Delete Profile');
    define('UI_TEXT_UPDATE_PRINTER_PROFILE', 'Update printer profile');
    define('UI_TEXT_DELETE_PRINTER_PROFILE', 'Delete printer profile (only if not used by any user)');
    define('UI_TEXT_SHIPPING_COMPANY_NAME_CANNOT_BE_EMPTY_ERROR', 'The shipping company name cannot be empty.');
    define('UI_TEXT_CANNOT_DELETE_SHIPPING_COMPANY_SALES_ORDERS_ERROR', 'Cannot delete this shipping company because sales orders have been created using this shipper.');
    define('UI_TEXT_CANNOT_DELETE_SHIPPING_COMPANY_INVOICES_ERROR', 'Cannot delete this shipping company because invoices have been created using this shipping company.');
    define('UI_TEXT_CONTACT_PERSON', 'Contact Person');
    define('UI_TEXT_SECONDARY_PHONE', 'Secondary Phone');
    define('UI_TEXT_CONTACT_PERSON_LABEL', 'Contact Person:');
    define('UI_TEXT_SECONDARY_PHONE_NUMBER_LABEL', 'Secondary Phone Number:');
    define('UI_TEXT_COMPANY_UPGRADED_SUCCESSFULLY', 'Company upgraded successfully.');
    define('UI_TEXT_COMPANY', 'Company');
    define('UI_TEXT_TABLE_SET', 'Table set');
    define('UI_TEXT_CURRENT_VERSION', 'Current version');
    define('UI_TEXT_LAST_LOG', 'Last log');
    define('UI_TEXT_UPGRADE', 'Upgrade');
    define('UI_TEXT_DO_YOU_REALLY_WANT_TO_CLEAR_THIS_UPGRADE_LOG', 'Do you really want to clear this upgrade log?');
    define('UI_TEXT_SELECT_COMPANY_FOR_INCREMENTAL_UPGRADE', 'Select company for incremental upgrade.');
    define('UI_TEXT_SELECT_BACKUP_FILE_FIRST', 'Select backup file first.');
    define('UI_TEXT_BACKUP_PATHS_NOT_SET_CORRECTLY', 'Backup paths have not been set correctly.');
    define('UI_TEXT_PLEASE_CONTACT_SYSTEM_ADMINISTRATOR', 'Please contact System Administrator.');
    define('UI_TEXT_CANNOT_FIND_BACKUP_DIRECTORY', 'cannot find backup directory');
    define('UI_TEXT_BACKUP_SUCCESSFULLY_GENERATED', 'Backup successfully generated.');
    define('UI_TEXT_FILENAME', 'Filename');
    define('UI_TEXT_DATABASE_BACKUP_FAILED', 'Database backup failed.');
    define('UI_TEXT_RESTORE_BACKUP_COMPLETED', 'Restore backup completed.');
    define('UI_TEXT_FILE_SUCCESSFULLY_DELETED', 'File successfully deleted.');
    define('UI_TEXT_CANT_DELETE_BACKUP_FILE', 'Can\'t delete backup file.');
    define('UI_TEXT_YOU_CAN_ONLY_UPLOAD_SQL_BACKUP_FILES', 'You can only upload *.sql backup files');
    define('UI_TEXT_FILENAME_CONTAINS_FORBIDDEN_CHARS', 'Filename contains forbidden chars. Please rename file and try again.');
    define('UI_TEXT_FILE_UPLOADED_TO_BACKUP_DIRECTORY', 'File uploaded to backup directory');
    define('UI_TEXT_FILE_WAS_NOT_UPLOADED_INTO_THE_SYSTEM', 'File was not uploaded into the system.');
    define('UI_TEXT_COMMENTS_LABEL', 'Comments:');
    define('UI_TEXT_COMPRESSION_LABEL', 'Compression:');
    define('UI_TEXT_CREATE_BACKUP', 'Create Backup');
    define('UI_TEXT_BACKUP_SCRIPTS_MAINTENANCE', 'Backup scripts maintenance');
    define('UI_TEXT_VIEW_BACKUP', 'View Backup');
    define('UI_TEXT_DOWNLOAD_BACKUP', 'Download Backup');
    define('UI_TEXT_RESTORE_BACKUP', 'Restore Backup');
    define('UI_TEXT_YOU_ARE_ABOUT_TO_RESTORE_DATABASE_FROM_BACKUP_FILE', 'You are about to restore database from backup file.\nDo you want to continue?');
    define('UI_TEXT_DELETE_BACKUP', 'Delete Backup');
    define('UI_TEXT_YOU_ARE_ABOUT_TO_REMOVE_SELECTED_BACKUP_FILE', 'You are about to remove selected backup file.\nDo you want to continue ?');
    define('UI_TEXT_UPLOAD_FILE', 'Upload file');
    define('UI_TEXT_NUMBER_OF_DAYS_OR_DAY_IN_FOLLOWING_MONTH_MUST_BE_NUMERIC_ERROR', 'The number of days or the day in the following month must be numeric.');
    define('UI_TEXT_TERMS_DESCRIPTION_MUST_BE_ENTERED_ERROR', 'The Terms description must be entered.');
    define('UI_TEXT_CANNOT_DELETE_PAYMENT_TERM_CUSTOMER_ACCOUNTS_ERROR', 'Cannot delete this payment term, because customer accounts have been created referring to this term.');
    define('UI_TEXT_CANNOT_DELETE_PAYMENT_TERM_SUPPLIER_ACCOUNTS_ERROR', 'Cannot delete this payment term, because supplier accounts have been created referring to this term');
    define('UI_TEXT_DUE_AFTER_DAYS', 'Due After/Days');
    define('UI_TEXT_TERMS_DESCRIPTION_LABEL', 'Terms Description:');
    define('UI_TEXT_PAYMENT_TYPE_LABEL', 'Payment type:');
    define('UI_TEXT_DAYS_OR_DAY_IN_FOLLOWING_MONTH_LABEL', 'Days (Or Day In Following Month):');
    define('UI_TEXT_SELECTED_THEME_HAS_BEEN_SUCCESSFULLY_DELETED', 'Selected theme has been successfully deleted');
    define('UI_TEXT_THEME', 'Theme');
    define('UI_TEXT_INSTALLED', 'Installed');
    define('UI_TEXT_AVAILABLE', 'Available');
    define('UI_TEXT_NO_OPTIONAL_THEME_IS_CURRENTLY_AVAILABLE', 'No optional theme is currently available.');
    define('UI_TEXT_UPDATE', 'Update');
    define('UI_TEXT_INSTALL', 'Install');
    define('UI_TEXT_YOU_ARE_ABOUT_TO_REMOVE_PACKAGE', 'You are about to remove package \'%s\'.\nDo you want to continue ?');
    define('UI_TEXT_SELECTED_EXTENSION_HAS_BEEN_SUCCESSFULLY_DELETED', 'Selected extension has been successfully deleted');
    define('UI_TEXT_EXTENSION', 'Extension');
    define('UI_TEXT_VERSION', 'Version');
    define('UI_TEXT_PATH', 'Path');
    define('UI_TEXT_ACTIVE', 'Active');
    define('UI_TEXT_PACKAGE_IS_INCOMPATIBLE_WITH_CURRENT_APPLICATION_VERSION', 'Package \'%s\' is incompatible with current application version and cannot be activated.\nCheck Install/Activate page for newer package version.');
    define('UI_TEXT_NO_OPTIONAL_EXTENSION_MODULE_IS_CURRENTLY_AVAILABLE', 'No optional extension module is currently available.');
    define('UI_TEXT_INSTALL_THIRD_PARTY_EXTENSION', 'Install third-party extension.');
    define('UI_TEXT_LANGUAGE', 'Language');
    define('UI_TEXT_ENCODING', 'Encoding');
    define('UI_TEXT_RIGHT_TO_LEFT', 'Right To Left');
    define('UI_TEXT_DEFAULT', 'Default');
    define('UI_TEXT_SUPPORTED', 'Supported');
    define('UI_TEXT_YOU_ARE_ABOUT_TO_REMOVE_LANGUAGE', 'You are about to remove language \'%s\'.\nDo you want to continue ?');
    define('UI_TEXT_THE_MARKED_LANGUAGE_IS_THE_CURRENT_LANGUAGE_WHICH_CANNOT_BE_DELETED', 'The marked language is the current language which cannot be deleted.');
    define('UI_TEXT_UPDATE_DEFAULT', 'Update default');
    define('UI_TEXT_EDIT_NON_STANDARD_LANGUAGE_CONFIGURATION', 'Edit non standard language configuration');
    define('UI_TEXT_ADD_NEW_LANGUAGE_MANUALLY', 'Add new language manually');
    define('UI_TEXT_LANGUAGE_NAME_CODE_NOR_ENCODING_CANNOT_BE_EMPTY', 'Language name, code nor encoding cannot be empty');
    define('UI_TEXT_LANGUAGE_CODE', 'Language Code');
    define('UI_TEXT_LANGUAGE_NAME', 'Language Name');
    define('UI_TEXT_RIGHT_TO_LEFT_LABEL', 'Right To Left');
    define('UI_TEXT_DEFAULT_LANGUAGE', 'Default Language');
    define('UI_TEXT_LANGUAGE_FILE', 'Language File');
    define('UI_TEXT_SELECT_YOUR_LANGUAGE_FILES_FROM_YOUR_LOCAL_HARDDISK', 'Select your language files from your local harddisk.');
    define('UI_TEXT_SELECTED_TRANSACTION_DOES_NOT_EXISTS', 'Selected transaction does not exists.');
    define('UI_TEXT_SELECT_ATTACHMENT_FILE', 'Select attachment file.');
    define('UI_TEXT_THE_FILE_SIZE_IS_OVER_THE_MAXIMUM_ALLOWED', 'The file size is over the maximum allowed.');
    define('UI_TEXT_FILE_NAME_EXCEEDS_MAXIMUM_OF_60_CHARS', 'File name exceeds maximum of 60 chars. Please change filename and try again.');
    define('UI_TEXT_ATTACHMENT_HAS_BEEN_INSERTED', 'Attachment has been inserted.');
    define('UI_TEXT_ATTACHMENT_HAS_BEEN_UPDATED', 'Attachment has been updated.');
    define('UI_TEXT_ATTACHMENT_HAS_BEEN_DELETED', 'Attachment has been deleted.');
    define('UI_TEXT_SELECT_A_CUSTOMER_LABEL', 'Select a customer: ');
    define('UI_TEXT_SELECT_A_SUPPLIER_LABEL', 'Select a supplier: ');
    define('UI_TEXT_SELECT_AN_ITEM_LABEL', 'Select an Item: ');
    define('UI_TEXT_SELECT_A_BANK_ACCOUNT_LABEL', 'Select a Bank Account: ');
    define('UI_TEXT_VIEW', 'View');
    define('UI_TEXT_DOWNLOAD', 'Download');
    define('UI_TEXT_DOC_TITLE', 'Doc Title');
    define('UI_TEXT_SIZE', 'Size');
    define('UI_TEXT_FILETYPE', 'Filetype');
    define('UI_TEXT_DOC_DATE', 'Doc Date');
    define('UI_TEXT_ATTACHED_FILE', 'Attached File');
    define('UI_TEXT_PAST_DUE_DAYS_INTERVAL_ALLOWANCE_ERROR', 'The past due days interval allowance must be between 0 and 100.');
    define('UI_TEXT_QUOTE_VALID_DAYS_INVALID_ERROR', 'Quote Valid Days is not valid number.');
    define('UI_TEXT_DELIVERY_REQUIRED_BY_INVALID_ERROR', 'Delivery Required By is not valid number.');
    define('UI_TEXT_RECEIVAL_REQUIRED_BY_INVALID_ERROR', 'Receival Required By is not valid number.');
    define('UI_TEXT_WORK_ORDER_REQUIRED_BY_AFTER_INVALID_ERROR', 'Work Order Required By After is not valid number.');
    define('UI_TEXT_DELIVERY_OVER_RECEIVE_ALLOWANCE_ERROR', 'The delivery over-receive allowance must be between 0 and 100.');
    define('UI_TEXT_INVOICE_OVER_CHARGE_ALLOWANCE_ERROR', 'The invoice over-charge allowance must be between 0 and 100.');
    define('UI_TEXT_GRN_CLEARING_ACCOUNT_CHANGE_ERROR', 'Before GRN Clearing Account can be changed all GRNs have to be invoiced');
    define('UI_TEXT_RETAINED_EARNINGS_ACCOUNT_ERROR', 'The Retained Earnings Account should be a Balance Account or the Profit and Loss Year Account should be an Expense Account (preferred the last one in the Expense Class)');
    define('UI_TEXT_GENERAL_GL_SETUP_UPDATED', 'The general GL setup has been updated.');
    define('UI_TEXT_GENERAL_GL', 'General GL');
    define('UI_TEXT_PAST_DUE_DAYS_INTERVAL_LABEL', 'Past Due Days Interval:');
    define('UI_TEXT_ACCOUNTS_TYPE_LABEL', 'Accounts Type:');
    define('UI_TEXT_RETAINED_EARNINGS_LABEL', 'Retained Earnings:');
    define('UI_TEXT_PROFIT_LOSS_YEAR_LABEL', 'Profit/Loss Year:');
    define('UI_TEXT_EXCHANGE_VARIANCES_ACCOUNT_LABEL', 'Exchange Variances Account:');
    define('UI_TEXT_BANK_CHARGES_ACCOUNT_LABEL', 'Bank Charges Account:');
    define('UI_TEXT_TAX_ALGORITHM_LABEL', 'Tax Algorithm:');
    define('UI_TEXT_DIMENSION_DEFAULTS', 'Dimension Defaults');
    define('UI_TEXT_DIMENSION_REQUIRED_BY_AFTER_LABEL', 'Dimension Required By After:');
    define('UI_TEXT_CUSTOMERS_AND_SALES', 'Customers and Sales');
    define('UI_TEXT_DEFAULT_CREDIT_LIMIT_LABEL', 'Default Credit Limit:');
    define('UI_TEXT_INVOICE_IDENTIFICATION_LABEL', 'Invoice Identification:');
    define('UI_TEXT_NUMBER_OPTION', 'Number');
    define('UI_TEXT_ACCUMULATE_BATCH_SHIPPING_LABEL', 'Accumulate batch shipping:');
    define('UI_TEXT_PRINT_ITEM_IMAGE_ON_QUOTE_LABEL', 'Print Item Image on Quote:');
    define('UI_TEXT_LEGAL_TEXT_ON_INVOICE_LABEL', 'Legal Text on Invoice:');
    define('UI_TEXT_SHIPPING_CHARGED_ACCOUNT_LABEL', 'Shipping Charged Account:');
    define('UI_TEXT_DEFERRED_INCOME_ACCOUNT_LABEL', 'Deferred Income Account:');
    define('UI_TEXT_NOT_USED', 'Not used');
    define('UI_TEXT_CUSTOMERS_AND_SALES_DEFAULTS', 'Customers and Sales Defaults');
    define('UI_TEXT_RECEIVABLE_ACCOUNT_LABEL', 'Receivable Account:');
    define('UI_TEXT_SALES_ACCOUNT_LABEL', 'Sales Account:');
    define('UI_TEXT_SALES_DISCOUNT_ACCOUNT_LABEL', 'Sales Discount Account:');
    define('UI_TEXT_PROMPT_PAYMENT_DISCOUNT_ACCOUNT_LABEL', 'Prompt Payment Discount Account:');
    define('UI_TEXT_QUOTE_VALID_DAYS_LABEL', 'Quote Valid Days:');
    define('UI_TEXT_DELIVERY_REQUIRED_BY_LABEL', 'Delivery Required By:');
    define('UI_TEXT_SUPPLIERS_AND_PURCHASING', 'Suppliers and Purchasing');
    define('UI_TEXT_DELIVERY_OVER_RECEIVE_ALLOWANCE_LABEL', 'Delivery Over-Receive Allowance:');
    define('UI_TEXT_INVOICE_OVER_CHARGE_ALLOWANCE_LABEL', 'Invoice Over-Charge Allowance:');
    define('UI_TEXT_SUPPLIERS_AND_PURCHASING_DEFAULTS', 'Suppliers and Purchasing Defaults');
    define('UI_TEXT_PAYABLE_ACCOUNT_LABEL', 'Payable Account:');
    define('UI_TEXT_PURCHASE_DISCOUNT_ACCOUNT_LABEL', 'Purchase Discount Account:');
    define('UI_TEXT_GRN_CLEARING_ACCOUNT_LABEL', 'GRN Clearing Account:');
    define('UI_TEXT_NO_POSTINGS_ON_GRN', 'No postings on GRN');
    define('UI_TEXT_RECEIVAL_REQUIRED_BY_LABEL', 'Receival Required By:');
    define('UI_TEXT_SHOW_PO_ITEM_CODES_LABEL', 'Show PO item codes:');
    define('UI_TEXT_INVENTORY', 'Inventory');
    define('UI_TEXT_ALLOW_NEGATIVE_INVENTORY_LABEL', 'Allow Negative Inventory:');
    define('UI_TEXT_WARNING_DELAY_IN_GL_POSTINGS', 'Warning:  This may cause a delay in GL postings');
    define('UI_TEXT_NO_ZERO_AMOUNTS_SERVICE_LABEL', 'No zero-amounts (Service):');
    define('UI_TEXT_LOCATION_NOTIFICATIONS_LABEL', 'Location Notifications:');
    define('UI_TEXT_ALLOW_NEGATIVE_PRICES_LABEL', 'Allow Negative Prices:');
    define('UI_TEXT_ITEMS_DEFAULTS', 'Items Defaults');
    define('UI_TEXT_INVENTORY_ACCOUNT_LABEL', 'Inventory Account:');
    define('UI_TEXT_COGS_ACCOUNT_LABEL', 'C.O.G.S. Account:');
    define('UI_TEXT_INVENTORY_ADJUSTMENTS_ACCOUNT_LABEL', 'Inventory Adjustments Account:');
    define('UI_TEXT_WIP_ACCOUNT_LABEL', 'WIP Account:');
    define('UI_TEXT_FIXED_ASSETS_DEFAULTS', 'Fixed Assets Defaults');
    define('UI_TEXT_LOSS_ON_ASSET_DISPOSAL_ACCOUNT_LABEL', 'Loss On Asset Disposal Account:');
    define('UI_TEXT_DEPRECIATION_PERIOD_LABEL', 'Depreciation Period:');
    define('UI_TEXT_MONTHLY', 'Monthly');
    define('UI_TEXT_YEARLY', 'Yearly');
    define('UI_TEXT_MANUFACTURING_DEFAULTS', 'Manufacturing Defaults');
    define('UI_TEXT_WORK_ORDER_REQUIRED_BY_AFTER_LABEL', 'Work Order Required By After:');
    define('UI_TEXT_SELECTED_CHART_DELETED_SUCCESS', 'Selected chart has been successfully deleted');
    define('UI_TEXT_NO_OPTIONAL_CHART_AVAILABLE', 'No optional chart of accounts is currently available.');
    define('UI_TEXT_CHART', 'Chart');
    define('UI_TEXT_AVAILABLE', 'Available');
    define('UI_TEXT_ENCODING', 'Encoding');
    define('UI_TEXT_NONE', 'None');
    define('UI_TEXT_UNKNOWN', 'Unknown');
    define('UI_TEXT_REMOVE_PACKAGE_CONFIRM', 'You are about to remove package \'%s\'.\nDo you want to continue ?');
    define('UI_TEXT_INVALID_PASSWORD_ENTERED', 'Invalid password entered.');
    define('UI_TEXT_PASSWORD_TOO_SHORT', 'The password entered must be at least 4 characters long.');
    define('UI_TEXT_PASSWORD_CANNOT_CONTAIN_LOGIN', 'The password cannot contain the user login.');
    define('UI_TEXT_PASSWORDS_DO_NOT_MATCH', 'The passwords entered are not the same.');
    define('UI_TEXT_PASSWORD_CHANGE_DEMO_MODE', 'Password cannot be changed in demo mode.');
    define('UI_TEXT_PASSWORD_UPDATED', 'Your password has been updated.');
    define('UI_TEXT_USER_LOGIN_LABEL', 'User login:');
    define('UI_TEXT_CURRENT_PASSWORD_LABEL', 'Current Password:');
    define('UI_TEXT_NEW_PASSWORD_LABEL', 'New Password:');
    define('UI_TEXT_REPEAT_NEW_PASSWORD_LABEL', 'Repeat New Password:');
    define('UI_TEXT_ENTER_NEW_PASSWORD_INSTRUCTION', 'Enter your new password in the fields.');
    define('UI_TEXT_QUERY_SIZE_INVALID', 'Query size must be integer and greater than zero.');
    define('UI_TEXT_DISPLAY_SETTINGS_UPDATED_DEMO_WARNING', 'Display settings have been updated. Keep in mind that changed settings are restored on every login in demo mode.');
    define('UI_TEXT_DISPLAY_SETTINGS_UPDATED', 'Display settings have been updated.');
    define('UI_TEXT_DECIMAL_PLACES', 'Decimal Places');
    define('UI_TEXT_PRICES_AMOUNTS_LABEL', 'Prices/Amounts:');
    define('UI_TEXT_QUANTITIES_LABEL', 'Quantities:');
    define('UI_TEXT_EXCHANGE_RATES_LABEL', 'Exchange Rates:');
    define('UI_TEXT_PERCENTAGES_LABEL', 'Percentages:');
    define('UI_TEXT_DATE_FORMAT_AND_SEPARATORS', 'Date Format and Separators');
    define('UI_TEXT_DATE_FORMAT_LABEL', 'Date Format:');
    define('UI_TEXT_DATE_SEPARATOR_LABEL', 'Date Separator:');
    define('UI_TEXT_THOUSAND_SEPARATOR_LABEL', 'Thousand Separator:');
    define('UI_TEXT_DECIMAL_SEPARATOR_LABEL', 'Decimal Separator:');
    define('UI_TEXT_USE_DATE_PICKER_LABEL', 'Use Date Picker');
    define('UI_TEXT_REPORTS', 'Reports');
    define('UI_TEXT_SAVE_REPORT_SELECTION_DAYS_LABEL', 'Save Report Selection Days:');
    define('UI_TEXT_DEFAULT_REPORT_DESTINATION_LABEL', 'Default Report Destination:');
    define('UI_TEXT_EXCEL', 'Excel');
    define('UI_TEXT_PDF_PRINTER', 'PDF/Printer');
    define('UI_TEXT_DEFAULT_REPORT_ORIENTATION_LABEL', 'Default Report Orientation:');
    define('UI_TEXT_LANDSCAPE', 'Landscape');
    define('UI_TEXT_PORTRAIT', 'Portrait');
    define('UI_TEXT_MISCELLANEOUS', 'Miscellaneous');
    define('UI_TEXT_SHOW_HINTS_FOR_NEW_USERS_LABEL', 'Show hints for new users:');
    define('UI_TEXT_SHOW_GL_INFORMATION_LABEL', 'Show GL Information:');
    define('UI_TEXT_SHOW_ITEM_CODES_LABEL', 'Show Item Codes:');
    define('UI_TEXT_THEME_LABEL', 'Theme:');
    define('UI_TEXT_PAGE_SIZE_LABEL', 'Page Size:');
    define('UI_TEXT_STARTUP_TAB_LABEL', 'Start-up Tab');
    define('UI_TEXT_PRINTING_PROFILE_LABEL', 'Printing profile');
    define('UI_TEXT_USE_POPUP_WINDOW_FOR_REPORTS_LABEL', 'Use popup window to display reports:');
    define('UI_TEXT_BROWSER_PRINTING_SUPPORT', 'Browser printing support');
    define('UI_TEXT_SET_OPTION_FOR_PDF_SUPPORT', 'Set this option to on if your browser directly supports pdf files');
    define('UI_TEXT_USE_ICONS_INSTEAD_OF_TEXT_LINKS_LABEL', 'Use icons instead of text links:');
    define('UI_TEXT_SET_OPTION_FOR_ICONS', 'Set this option to on for using icons instead of text links');
    define('UI_TEXT_REMEMBER_LAST_DOCUMENT_DATE_LABEL', 'Remember last document date:');
    define('UI_TEXT_QUERY_PAGE_SIZE_LABEL', 'Query page size:');
    define('UI_TEXT_TRANSACTION_DAYS_LABEL', 'Transaction days:');
    define('UI_TEXT_LANGUAGE', 'Language');
    define('UI_TEXT_LANGUAGE_LABEL', 'Language:');
    define('UI_TEXT_IF_SET_DOCUMENT_DATE_REMEMBERED', 'If set document date is remembered on subsequent documents, otherwise default is current date');
    define('UI_TEXT_CATEGORY_DESCRIPTION_CANNOT_BE_EMPTY', 'Category description cannot be empty.');
    define('UI_TEXT_CANNOT_DELETE_CATEGORY_WITH_CONTACTS', 'Cannot delete this category because there are contacts related to it.');
    define('UI_TEXT_CATEGORY_TYPE', 'Category Type');
    define('UI_TEXT_CATEGORY_SUBTYPE', 'Category Subtype');
    define('UI_TEXT_SHORT_NAME', 'Short Name');
    define('UI_TEXT_DESCRIPTION', 'Description');
    define('UI_TEXT_CONTACT_CATEGORY_TYPE_LABEL', 'Contact Category Type:');
    define('UI_TEXT_CONTACT_CATEGORY_SUBTYPE_LABEL', 'Contact Category Subtype:');
    define('UI_TEXT_CATEGORY_SHORT_NAME_LABEL', 'Category Short Name:');
    define('UI_TEXT_CATEGORY_DESCRIPTION_LABEL', 'Category Description:');
    define('UI_TEXT_CATEGORY_HAS_BEEN_DELETED', 'Category has been deleted');
    define('UI_TEXT_DATABASE_SETTINGS_NOT_SPECIFIED', 'Database settings are not specified.');
    define('UI_TEXT_DATABASE_SETTINGS_ALREADY_USED', 'This database settings are already used by another company.');
    define('UI_TEXT_CANNOT_HAVE_TABLE_SET_WITHOUT_PREFIX', 'You cannot have table set without prefix together with prefixed sets in the same database.');
    define('UI_TEXT_ERROR_CREATING_DATABASE', 'Error creating Database: ');
    define('UI_TEXT_PLEASE_CREATE_MANUALLY', ', Please create it manually');
    define('UI_TEXT_CANNOT_OPEN_CONFIG_FILE', 'Cannot open the configuration file - ');
    define('UI_TEXT_CANNOT_WRITE_CONFIG_FILE', 'Cannot write to the configuration file - ');
    define('UI_TEXT_CONFIG_FILE_NOT_WRITABLE', ' is not writable. Change its permissions so it is, then re-run the operation.');
    define('UI_TEXT_CANNOT_RENAME_COMPANY_SUBDIRECTORY', 'Cannot rename company subdirectory');
    define('UI_TEXT_ERROR_REMOVING_DATABASE', 'Error removing Database: ');
    define('UI_TEXT_PLEASE_REMOVE_MANUALLY', ', please remove it manually');
    define('UI_TEXT_CANNOT_REMOVE_TEMP_RENAMED_COMPANY_DIR', 'Cannot remove temporary renamed company data directory ');
    define('UI_TEXT_SELECTED_COMPANY_DELETED', 'Selected company has been deleted');
        define('UI_TEXT_DATABASE_PORT_NUMERIC', 'Database port has to be numeric or empty.');
    define('UI_TEXT_CONFIG_FILE', 'The configuration file ');
    define('UI_TEXT_DATABASE_HOST', 'Database Host');
    define('UI_TEXT_DATABASE_PORT', 'Database Port');
    define('UI_TEXT_DATABASE_USER', 'Database User');
    define('UI_TEXT_DATABASE_NAME', 'Database Name');
    define('UI_TEXT_TABLE_PREF', 'Table Pref');
    define('UI_TEXT_CHARSET', 'Charset');
    define('UI_TEXT_CONFIRM_REMOVE_COMPANY', 'You are about to remove company \'%s\'.\nDo you want to continue ?');
    define('UI_TEXT_MARKED_COMPANY_CURRENT_CANNOT_DELETE', 'The marked company is the current company which cannot be deleted.');
    define('UI_TEXT_ADMIN_PASSWORD_DEFAULT', 'If no Admin Password is entered, the new Admin Password will be \'<b>password</b>\' by default ');
    define('UI_TEXT_SET_PORT_IF_NOT_DEFAULT', 'Set Only Port value if you cannot use the default port 3306.');
    define('UI_TEXT_DATABASE_PASSWORD', 'Database Password');
    define('UI_TEXT_DATABASE_COLLATION', 'Database Collation:');
    define('UI_TEXT_DEFAULT_COMPANY', 'Default Company');
    define('UI_TEXT_DATABASE_SCRIPT', 'Database Script');
    define('UI_TEXT_NEW_SCRIPT_ADMIN_PASSWORD', 'New script Admin Password');
    define('UI_TEXT_SETUP', 'S&etup');
    define('UI_TEXT_COMPANY_SETUP_MODULE', 'Company Setup');
    define('UI_TEXT_COMPANY_SETUP', '&Company Setup');
    define('UI_TEXT_USER_ACCOUNTS_SETUP', '&User Accounts Setup');
    define('UI_TEXT_ACCESS_SETUP', '&Access Setup');
    define('UI_TEXT_DISPLAY_SETUP', '&Display Setup');
    define('UI_TEXT_TRANSACTION_REFERENCES', 'Transaction &References');
    define('UI_TEXT_TAXES', '&Taxes');
    define('UI_TEXT_TAX_GROUPS', 'Tax &Groups');
    define('UI_TEXT_ITEM_TAX_TYPES', 'Item Ta&x Types');
    define('UI_TEXT_SYSTEM_GL_SETUP', 'System and &General GL Setup');
    define('UI_TEXT_FISCAL_YEARS', '&Fiscal Years');
    define('UI_TEXT_PRINT_PROFILES', '&Print Profiles');
    define('UI_TEXT_PAYMENT_TERMS', 'Pa&yment Terms');
    define('UI_TEXT_SHIPPING_COMPANY', 'Shi&pping Company');
    define('UI_TEXT_POINTS_OF_SALE', '&Points of Sale');
    define('UI_TEXT_PRINTERS', '&Printers');
    define('UI_TEXT_CONTACT_CATEGORIES', 'Contact &Categories');
    define('UI_TEXT_MAINTENANCE', 'Maintenance');
    define('UI_TEXT_VOID_TRANSACTION', '&Void a Transaction');
    define('UI_TEXT_VIEW_PRINT_TRANSACTIONS', 'View or &Print Transactions');
    define('UI_TEXT_ATTACH_DOCUMENTS', '&Attach Documents');
    define('UI_TEXT_SYSTEM_DIAGNOSTICS', 'System &Diagnostics');
    define('UI_TEXT_BACKUP_RESTORE', '&Backup and Restore');
    define('UI_TEXT_CREATE_UPDATE_COMPANIES', 'Create/Update &Companies');
    define('UI_TEXT_INSTALL_UPDATE_LANGUAGES', 'Install/Update &Languages');
    define('UI_TEXT_INSTALL_ACTIVATE_EXTENSIONS', 'Install/Activate &Extensions');
    define('UI_TEXT_INSTALL_ACTIVATE_THEMES', 'Install/Activate &Themes');
    define('UI_TEXT_INSTALL_ACTIVATE_CHART_ACCOUNTS', 'Install/Activate &Chart of Accounts');
    define('UI_TEXT_SOFTWARE_UPGRADE', 'Software &Upgrade');
    define('UI_TEXT_PURCHASES', '&Purchases');
    define('UI_TEXT_TRANSACTIONS', 'Transactions');
    define('UI_TEXT_PURCHASE_ORDER_ENTRY', 'Purchase &Order Entry');
    define('UI_TEXT_OUTSTANDING_PURCHASE_ORDERS_MAINTENANCE', '&Outstanding Purchase Orders Maintenance');
    define('UI_TEXT_DIRECT_GRN', 'Direct &GRN');
    define('UI_TEXT_DIRECT_SUPPLIER_INVOICE', 'Direct Supplier &Invoice');
    define('UI_TEXT_PAYMENTS_TO_SUPPLIERS', '&Payments to Suppliers');
    define('UI_TEXT_SUPPLIER_INVOICES', 'Supplier &Invoices');
    define('UI_TEXT_SUPPLIER_CREDIT_NOTES', 'Supplier &Credit Notes');
    define('UI_TEXT_ALLOCATE_SUPPLIER_PAYMENTS_CREDIT_NOTES', '&Allocate Supplier Payments or Credit Notes');
    define('UI_TEXT_INQUIRIES_AND_REPORTS', 'Inquiries and Reports');
    define('UI_TEXT_PURCHASE_ORDERS_INQUIRY', 'Purchase Orders &Inquiry');
    define('UI_TEXT_SUPPLIER_TRANSACTION_INQUIRY', 'Supplier Transaction &Inquiry');
    define('UI_TEXT_SUPPLIER_ALLOCATION_INQUIRY', 'Supplier Allocation &Inquiry');
    define('UI_TEXT_SUPPLIER_PURCHASING_REPORTS', 'Supplier and Purchasing &Reports');
    define('UI_TEXT_SUPPLIERS', '&Suppliers');
    define('UI_TEXT_MANUFACTURING', '&Manufacturing');
    define('UI_TEXT_WORK_ORDER_ENTRY', 'Work &Order Entry');
    define('UI_TEXT_OUTSTANDING_WORK_ORDERS', '&Outstanding Work Orders');
    define('UI_TEXT_COSTED_BILL_OF_MATERIAL_INQUIRY', 'Costed Bill Of Material Inquiry');
    define('UI_TEXT_INVENTORY_ITEM_WHERE_USED_INQUIRY', 'Inventory Item Where Used &Inquiry');
    define('UI_TEXT_WORK_ORDER_INQUIRY', 'Work Order &Inquiry');
    define('UI_TEXT_MANUFACTURING_REPORTS', 'Manufacturing &Reports');
    define('UI_TEXT_BILLS_OF_MATERIAL', '&Bills Of Material');
    define('UI_TEXT_WORK_CENTRES', '&Work Centres');
    define('UI_TEXT_ITEMS_AND_INVENTORY', '&Items and Inventory');
    define('UI_TEXT_INVENTORY_LOCATION_TRANSFERS', 'Inventory Location &Transfers');
    define('UI_TEXT_INVENTORY_ADJUSTMENTS', 'Inventory &Adjustments');
    define('UI_TEXT_INVENTORY_ITEM_MOVEMENTS', 'Inventory Item &Movements');
    define('UI_TEXT_INVENTORY_ITEM_STATUS', 'Inventory Item &Status');
    define('UI_TEXT_INVENTORY_REPORTS', 'Inventory &Reports');
    define('UI_TEXT_ITEMS', '&Items');
    define('UI_TEXT_FOREIGN_ITEM_CODES', '&Foreign Item Codes');
    define('UI_TEXT_SALES_KITS', 'Sales &Kits');
    define('UI_TEXT_ITEM_CATEGORIES', 'Item &Categories');
    define('UI_TEXT_INVENTORY_LOCATIONS', 'Inventory &Locations');
    define('UI_TEXT_UNITS_OF_MEASURE', '&Units of Measure');
    define('UI_TEXT_REORDER_LEVELS', '&Reorder Levels');
    define('UI_TEXT_PRICING_AND_COSTS', 'Pricing and Costs');
    define('UI_TEXT_PURCHASING_PRICING', 'Purchasing &Pricing');
    define('UI_TEXT_STANDARD_COSTS', 'Standard &Costs');
    define('UI_TEXT_FIXED_ASSETS', '&Fixed Assets');
    define('UI_TEXT_FIXED_ASSETS_PURCHASE', 'Fixed Assets &Purchase');
    define('UI_TEXT_FIXED_ASSETS_LOCATION_TRANSFERS', 'Fixed Assets Location &Transfers');
    define('UI_TEXT_FIXED_ASSETS_DISPOSAL', 'Fixed Assets &Disposal');
    define('UI_TEXT_FIXED_ASSETS_SALE', 'Fixed Assets &Sale');
    define('UI_TEXT_PROCESS_DEPRECIATION', 'Process &Depreciation');
    define('UI_TEXT_FIXED_ASSETS_MOVEMENTS', 'Fixed Assets &Movements');
    define('UI_TEXT_FIXED_ASSETS_INQUIRY', 'Fixed Assets In&quiry');
    define('UI_TEXT_FIXED_ASSETS_REPORTS', 'Fixed Assets &Reports');
    define('UI_TEXT_FIXED_ASSETS_MENU', 'Fixed &Assets');
    define('UI_TEXT_FIXED_ASSETS_LOCATIONS', 'Fixed Assets &Locations');
    define('UI_TEXT_FIXED_ASSETS_CATEGORIES', 'Fixed Assets &Categories');
    define('UI_TEXT_FIXED_ASSETS_CLASSES', 'Fixed Assets Cl&asses');
    define('UI_TEXT_SALES', '&Sales');
    define('UI_TEXT_SALES_QUOTATION_ENTRY', 'Sales &Quotation Entry');
    define('UI_TEXT_SALES_ORDER_ENTRY', 'Sales &Order Entry');
    define('UI_TEXT_DIRECT_DELIVERY', 'Direct &Delivery');
    define('UI_TEXT_DIRECT_INVOICE', 'Direct &Invoice');
    define('UI_TEXT_DELIVERY_AGAINST_SALES_ORDERS', '&Delivery Against Sales Orders');
    define('UI_TEXT_INVOICE_AGAINST_SALES_DELIVERY', '&Invoice Against Sales Delivery');
    define('UI_TEXT_TEMPLATE_DELIVERY', '&Template Delivery');
    define('UI_TEXT_TEMPLATE_INVOICE', '&Template Invoice');
    define('UI_TEXT_CREATE_PRINT_RECURRENT_INVOICES', '&Create and Print Recurrent Invoices');
    define('UI_TEXT_CUSTOMER_PAYMENTS', 'Customer &Payments');
    define('UI_TEXT_INVOICE_PREPAID_ORDERS', 'Invoice &Prepaid Orders');
    define('UI_TEXT_CUSTOMER_CREDIT_NOTES', 'Customer &Credit Notes');
    define('UI_TEXT_ALLOCATE_CUSTOMER_PAYMENTS_CREDIT_NOTES', '&Allocate Customer Payments or Credit Notes');
    define('UI_TEXT_SALES_QUOTATION_INQUIRY', 'Sales Quotation I&nquiry');
    define('UI_TEXT_SALES_ORDER_INQUIRY', 'Sales Order &Inquiry');
    define('UI_TEXT_CUSTOMER_TRANSACTION_INQUIRY', 'Customer Transaction &Inquiry');
    define('UI_TEXT_CUSTOMER_ALLOCATION_INQUIRY', 'Customer Allocation &Inquiry');
    define('UI_TEXT_CUSTOMER_SALES_REPORTS', 'Customer and Sales &Reports');
    define('UI_TEXT_ADD_MANAGE_CUSTOMERS', 'Add and Manage &Customers');
    define('UI_TEXT_CUSTOMER_BRANCHES', 'Customer &Branches');
    define('UI_TEXT_SALES_GROUPS', 'Sales &Groups');
    define('UI_TEXT_RECURRENT_INVOICES', 'Recurrent &Invoices');
    define('UI_TEXT_SALES_TYPES', 'Sales T&ypes');
    define('UI_TEXT_SALES_PERSONS', 'Sales &Persons');
    define('UI_TEXT_SALES_AREAS', 'Sales &Areas');
    define('UI_TEXT_CREDIT_STATUS_SETUP', 'Credit &Status Setup');
    define('UI_TEXT_DIMENSION_ENTRY', 'Dimension &Entry');
    define('UI_TEXT_OUTSTANDING_DIMENSIONS', '&Outstanding Dimensions');
    define('UI_TEXT_DIMENSION_INQUIRY', 'Dimension &Inquiry');
    define('UI_TEXT_DIMENSION_REPORTS', 'Dimension &Reports');
    define('UI_TEXT_DIMENSION_TAGS', 'Dimension &Tags');
    define('UI_TEXT_PAYMENTS', '&Payments');
    define('UI_TEXT_DEPOSITS', '&Deposits');
    define('UI_TEXT_BANK_ACCOUNT_TRANSFERS', 'Bank Account &Transfers');
    define('UI_TEXT_JOURNAL_ENTRY', '&Journal Entry');
    define('UI_TEXT_BUDGET_ENTRY', '&Budget Entry');
    define('UI_TEXT_RECONCILE_BANK_ACCOUNT', '&Reconcile Bank Account');
    define('UI_TEXT_REVENUE_COSTS_ACCRUALS', 'Revenue / &Costs Accruals');
    define('UI_TEXT_JOURNAL_INQUIRY', '&Journal Inquiry');
    define('UI_TEXT_GL_INQUIRY', 'GL &Inquiry');
    define('UI_TEXT_BANK_ACCOUNT_INQUIRY', 'Bank Account &Inquiry');
    define('UI_TEXT_TAX_INQUIRY', 'Ta&x Inquiry');
    define('UI_TEXT_TRIAL_BALANCE', 'Trial &Balance');
    define('UI_TEXT_BALANCE_SHEET_DRILLDOWN', 'Balance &Sheet Drilldown');
    define('UI_TEXT_PROFIT_AND_LOSS_DRILLDOWN', '&Profit and Loss Drilldown');
    define('UI_TEXT_BANKING_REPORTS', 'Banking &Reports');
    define('UI_TEXT_GENERAL_LEDGER_REPORTS', 'General Ledger &Reports');
    define('UI_TEXT_BANK_ACCOUNTS', 'Bank &Accounts');
    define('UI_TEXT_QUICK_ENTRIES', '&Quick Entries');
    define('UI_TEXT_GL_ACCOUNTS', '&GL Accounts');
    define('UI_TEXT_GL_ACCOUNT_GROUPS', 'GL Account &Groups');
    define('UI_TEXT_GL_ACCOUNT_CLASSES', 'GL Account &Classes');
    define('UI_TEXT_CLOSING_GL_TRANSACTIONS', '&Closing GL Transactions');
    define('UI_TEXT_REVALUATION_OF_CURRENCY_ACCOUNTS', '&Revaluation of Currency Accounts');
    define('UI_TEXT_ACCOUNT_TAGS', 'Account &Tags');
    define('UI_TEXT_CURRENCIES', '&Currencies');
    define('UI_TEXT_EXCHANGE_RATES', '&Exchange Rates');
    define('UI_TEXT_MODIFYING_SALES_ORDER', 'Modifying Sales Order # %d');
    define('UI_TEXT_MODIFYING_SALES_QUOTATION', 'Modifying Sales Quotation # %d');
    define('UI_TEXT_ORDER_CANNOT_EDIT', 'This order cannot be edited because there are invoices or payments related to it, and prepayment terms were used.');
    define('UI_TEXT_ORDER_ENTERED', 'Order # %d has been entered.');
    define('UI_TEXT_VIEW_THIS_ORDER', '&View This Order');
    define('UI_TEXT_PRINT_THIS_ORDER', '&Print This Order');
    define('UI_TEXT_EMAIL_THIS_ORDER', '&Email This Order');
    define('UI_TEXT_MAKE_DELIVERY_AGAINST_ORDER', 'Make &Delivery Against This Order');
    define('UI_TEXT_WORK_ORDER_ENTRY', 'Work &Order Entry');
    define('UI_TEXT_ENTER_NEW_ORDER', 'Enter a &New Order');
    define('UI_TEXT_RECEIVE_CUSTOMER_PAYMENT', 'Receive Customer Payment');
    define('UI_TEXT_ADD_ATTACHMENT', 'Add an Attachment');
    define('UI_TEXT_ORDER_UPDATED', 'Order # %d has been updated.');
    define('UI_TEXT_CONFIRM_QUANTITIES_MAKE_DELIVERY', 'Confirm Order Quantities and Make &Delivery');
    define('UI_TEXT_SELECT_DIFFERENT_ORDER', 'Select A Different &Order');
    define('UI_TEXT_QUOTATION_ENTERED', 'Quotation # %d has been entered.');
    define('UI_TEXT_VIEW_THIS_QUOTATION', '&View This Quotation');
    define('UI_TEXT_PRINT_THIS_QUOTATION', '&Print This Quotation');
    define('UI_TEXT_EMAIL_THIS_QUOTATION', '&Email This Quotation');
    define('UI_TEXT_MAKE_SALES_ORDER_AGAINST_QUOTATION', 'Make &Sales Order Against This Quotation');
    define('UI_TEXT_ENTER_NEW_QUOTATION', 'Enter a New &Quotation');
    define('UI_TEXT_SELECT_DIFFERENT_QUOTATION', 'Select A Different &Quotation');
    define('UI_TEXT_QUOTATION_UPDATED', 'Quotation # %d has been updated.');
    define('UI_TEXT_DELIVERY_ENTERED', 'Delivery # %d has been entered.');
    define('UI_TEXT_VIEW_THIS_DELIVERY', '&View This Delivery');
    define('UI_TEXT_PRINT_DELIVERY_NOTE', '&Print Delivery Note');
    define('UI_TEXT_EMAIL_DELIVERY_NOTE', '&Email Delivery Note');
    define('UI_TEXT_PRINT_PACKING_SLIP', 'P&rint as Packing Slip');
    define('UI_TEXT_EMAIL_PACKING_SLIP', 'E&mail as Packing Slip');
    define('UI_TEXT_VIEW_GL_JOURNAL_DISPATCH', 'View the GL Journal Entries for this Dispatch');
    define('UI_TEXT_MAKE_INVOICE_AGAINST_DELIVERY', 'Make &Invoice Against This Delivery');
    define('UI_TEXT_ENTER_NEW_TEMPLATE_DELIVERY', 'Enter a New Template &Delivery');
    define('UI_TEXT_ENTER_NEW_DELIVERY', 'Enter a &New Delivery');
    define('UI_TEXT_INVOICE_ENTERED', 'Invoice # %d has been entered.');
    define('UI_TEXT_VIEW_THIS_INVOICE', '&View This Invoice');
    define('UI_TEXT_PRINT_SALES_INVOICE', '&Print Sales Invoice');
    define('UI_TEXT_EMAIL_SALES_INVOICE', '&Email Sales Invoice');
    define('UI_TEXT_PRINT_RECEIPT', 'Print &Receipt');
    define('UI_TEXT_VIEW_GL_JOURNAL_INVOICE', 'View the GL &Journal Entries for this Invoice');
    define('UI_TEXT_ENTER_NEW_TEMPLATE_INVOICE', 'Enter a &New Template Invoice');
    define('UI_TEXT_ENTER_NEW_DIRECT_INVOICE', 'Enter a &New Direct Invoice');
    define('UI_TEXT_ENTRY_CUSTOMER_PAYMENT_INVOICE', 'Entry &customer payment for this invoice');
    define('UI_TEXT_NO_CUSTOMER_SELECTED', 'There is no customer selected.');
    define('UI_TEXT_CUSTOMER_NO_BRANCH', 'This customer has no branch defined.');
    define('UI_TEXT_DATE_INVALID', 'The entered date is invalid.');
    define('UI_TEXT_DATE_OUT_OF_FISCAL_YEAR', 'The entered date is out of fiscal year or is closed for further data entry.');
    define('UI_TEXT_MUST_ENTER_ITEM_LINE', 'You must enter at least one non empty item line.');
    define('UI_TEXT_INSUFFICIENT_QUANTITY', 'This document cannot be processed because there is insufficient quantity for items marked.');
    define('UI_TEXT_PREPAYMENT_POSITIVE_LESS_TOTAL', 'Pre-payment required have to be positive and less than total amount.');
    define('UI_TEXT_MUST_ENTER_DELIVERY_PERSON', 'You must enter the person or company to whom delivery should be made to.');
    define('UI_TEXT_STREET_ADDRESS_REQUIRED', 'You should enter the street address in the box provided. Orders cannot be accepted without a valid street address.');
    define('UI_TEXT_SHIPPING_COST_NUMERIC', 'The shipping cost entered is expected to be numeric.');
    define('UI_TEXT_VALID_DATE_INVALID', 'The Valid date is invalid.');
    define('UI_TEXT_DELIVERY_DATE_INVALID', 'The delivery date is invalid.');
    define('UI_TEXT_VALID_DATE_BEFORE_QUOTATION', 'The requested valid date is before the date of the quotation.');
    define('UI_TEXT_DELIVERY_DATE_BEFORE_ORDER', 'The requested delivery date is before the date of the order.');
    define('UI_TEXT_DEFINE_CASH_ACCOUNT', 'You need to define a cash account for your Sales Point.');
    define('UI_TEXT_MUST_ENTER_REFERENCE', 'You must enter a reference.');
    define('UI_TEXT_REFERENCE_ALREADY_IN_USE', 'The entered reference is already in use.');
    define('UI_TEXT_REFERENCE_FIELD_INCREASED', 'The reference number field has been increased. Please save the document again.');
    define('UI_TEXT_ITEM_DESCRIPTION_EMPTY', 'Item description cannot be empty.');
    define('UI_TEXT_QUANTITY_DISCOUNT_INVALID', 'The item could not be updated because you are attempting to set the quantity ordered to less than 0, or the discount percent to more than 100.');
    define('UI_TEXT_PRICE_MUST_BE_ENTERED', 'Price for inventory item must be entered and can not be less than 0');
    define('UI_TEXT_QUANTITY_LESS_THAN_DELIVERED', 'You attempting to make the quantity ordered a quantity less than has already been delivered. The quantity delivered cannot be modified retrospectively.');
    define('UI_TEXT_NO_CUSTOMERS_DEFINED', 'There are no customers defined in the system.');
    define('UI_TEXT_NO_BANK_ACCOUNTS_DEFINED', 'There are no bank accounts defined in the system.');
    define('UI_TEXT_INVALID_SALES_INVOICE_NUMBER', 'Invalid sales invoice number.');
    define('UI_TEXT_CUSTOMER_PAYMENT_ENTERED', 'The customer payment has been successfully entered.');
    define('UI_TEXT_PRINT_THIS_RECEIPT', '&Print This Receipt');
    define('UI_TEXT_EMAIL_THIS_RECEIPT', '&Email This Receipt');
    define('UI_TEXT_VIEW_THIS_CUSTOMER_PAYMENT', '&View this Customer Payment');
    define('UI_TEXT_VIEW_GL_JOURNAL_CUSTOMER_PAYMENT', '&View the GL Journal Entries for this Customer Payment');
    define('UI_TEXT_ENTER_ANOTHER_CUSTOMER_PAYMENT', 'Enter Another &Customer Payment');
    define('UI_TEXT_ENTER_OTHER_DEPOSIT', 'Enter Other &Deposit');
    define('UI_TEXT_ENTER_PAYMENT_TO_SUPPLIER', 'Enter Payment to &Supplier');
    define('UI_TEXT_ENTER_OTHER_PAYMENT', 'Enter Other &Payment');
    define('UI_TEXT_BANK_ACCOUNT_TRANSFER', 'Bank Account &Transfer');
    define('UI_TEXT_CUSTOMER_PAYMENT_UPDATED', 'The customer payment has been successfully updated.');
    define('UI_TEXT_SELECT_ANOTHER_CUSTOMER_PAYMENT_EDITION', 'Select Another Customer Payment for &Edition');
    define('UI_TEXT_MODIFYING_SALES_INVOICE', 'Modifying Sales Invoice # %d.');
    define('UI_TEXT_SELECTED_DELIVERIES_PROCESSED', 'Selected deliveries has been processed');
    define('UI_TEXT_SELECT_ANOTHER_DELIVERY_FOR_INVOICING', 'Select Another &Delivery For Invoicing');
    define('UI_TEXT_SELECT_ANOTHER_INVOICE_TO_MODIFY', 'Select Another &Invoice to Modify');
    define('UI_TEXT_SELECT_DIFFERENT_DELIVERY_TO_INVOICE', 'Select a different delivery to invoice');
    define('UI_TEXT_NO_DELIVERED_ITEMS_LEFT_TO_INVOICE', 'There are no delivered items with a quantity left to invoice. There is nothing left to invoice.');
    define('UI_TEXT_ALL_QUANTITIES_CREDITED', 'All quantities on this invoice has been credited. There is nothing to modify on this invoice');
    define('UI_TEXT_SET_DEFERRED_INCOME_ACCOUNT', 'You have to set Deferred Income Account in GL Setup to entry prepayment invoices.');
    define('UI_TEXT_SELECT_CORRECT_PREPAYMENT', 'Please select correct Sales Order Prepayment to be invoiced and try again.');
    define('UI_TEXT_PAGE_OPEN_AFTER_DELIVERY_SELECTION', 'This page can only be opened after delivery selection. Please select delivery to invoicing first.');
    define('UI_TEXT_SELECT_DELIVERY_TO_INVOICE', 'Select Delivery to Invoice');
    define('UI_TEXT_SELECTED_QUANTITY_INVALID', 'Selected quantity cannot be less than quantity credited nor more than quantity not invoiced yet.');
    define('UI_TEXT_ENTERED_INVOICE_DATE_INVALID', 'The entered invoice date is invalid.');
    define('UI_TEXT_ENTERED_DATE_OUT_OF_FISCAL_YEAR', 'The entered date is out of fiscal year or is closed for further data entry.');
    define('UI_TEXT_ENTERED_INVOICE_DUE_DATE_INVALID', 'The entered invoice due date is invalid.');
    define('UI_TEXT_MUST_ENTER_REFERENCE', 'You must enter a reference.');
    define('UI_TEXT_ENTERED_SHIPPING_VALUE_NOT_NUMERIC', 'The entered shipping value is not numeric.');
    define('UI_TEXT_NO_ITEM_QUANTITIES_ON_INVOICE', 'There are no item quantities on this invoice.');
    define('UI_TEXT_NO_NON_INVOICED_PAYMENTS', 'There is no non-invoiced payments for this order. If you want to issue final invoice, select delayed or cash payment terms.');
    define('UI_TEXT_ENTERED_REFERENCE_ALREADY_IN_USE', 'The entered reference is already in use.');
    define('UI_TEXT_CUSTOMER', 'Customer');
    define('UI_TEXT_BRANCH', 'Branch');
    define('UI_TEXT_PAYMENT_TERMS', 'Payment terms:');
    define('UI_TEXT_REFERENCE', 'Reference');
    define('UI_TEXT_SALES_TYPE', 'Sales Type');
    define('UI_TEXT_CURRENCY', 'Currency');
    define('UI_TEXT_DIMENSION', 'Dimension');
    define('UI_TEXT_SHIPPING_COMPANY', 'Shipping Company');
    define('UI_TEXT_DATE', 'Date');
    define('UI_TEXT_DUE_DATE', 'Due Date');
    define('UI_TEXT_DIMENSION_2', 'Dimension 2:');
    define('UI_TEXT_SELECTED_CUSTOMER_ACCOUNT_ON_HOLD', 'The selected customer account is currently on hold. Please contact the credit control personnel to discuss.');
    define('UI_TEXT_SALES_ORDER_ITEMS', 'Sales Order Items');
    define('UI_TEXT_INVOICE_ITEMS', 'Invoice Items');
    define('UI_TEXT_ITEM_CODE', 'Item Code');
    define('UI_TEXT_ITEM_DESCRIPTION', 'Item Description');
    define('UI_TEXT_UNITS', 'Units');
    define('UI_TEXT_QUANTITY', 'Quantity');
    define('UI_TEXT_PRICE', 'Price');
    define('UI_TEXT_TAX_TYPE', 'Tax Type');
    define('UI_TEXT_DISCOUNT', 'Discount');
    define('UI_TEXT_TOTAL', 'Total');
    define('UI_TEXT_DELIVERED', 'Delivered');
    define('UI_TEXT_INVOICED', 'Invoiced');
    define('UI_TEXT_THIS_INVOICE', 'This Invoice');
    define('UI_TEXT_DN', 'DN');
    define('UI_TEXT_CREDITED', 'Credited');
    define('UI_TEXT_REMOVE', 'Remove');
    define('UI_TEXT_SHIPPING_COST', 'Shipping Cost');
    define('UI_TEXT_SUB_TOTAL', 'Sub-total');
    define('UI_TEXT_INVOICE_TOTAL', 'Invoice Total');
    define('UI_TEXT_SALES_ORDER', 'Sales order:');
    define('UI_TEXT_PAYMENTS_RECEIVED', 'Payments received:');
    define('UI_TEXT_INVOICED_HERE', 'Invoiced here:');
    define('UI_TEXT_LEFT_TO_BE_INVOICED', 'Left to be invoiced:');
    define('UI_TEXT_INVOICED_SO_FAR', 'Invoiced so far:');
    define('UI_TEXT_MEMO', 'Memo:');
    define('UI_TEXT_UPDATE_BUTTON', 'Update');
    define('UI_TEXT_PROCESS_INVOICE', 'Process Invoice');
    define('UI_TEXT_MODIFYING_DELIVERY_NOTE', 'Modifying Delivery Note # %d.');
    define('UI_TEXT_DELIVERY_ENTERED', 'Delivery # %d has been entered.');
    define('UI_TEXT_VIEW_THIS_DELIVERY', '&View This Delivery');
    define('UI_TEXT_PRINT_DELIVERY_NOTE', '&Print Delivery Note');
    define('UI_TEXT_EMAIL_DELIVERY_NOTE', '&Email Delivery Note');
    define('UI_TEXT_PRINT_AS_PACKING_SLIP', 'P&rint as Packing Slip');
    define('UI_TEXT_EMAIL_AS_PACKING_SLIP', 'E&mail as Packing Slip');
    define('UI_TEXT_VIEW_GL_JOURNAL_ENTRIES_FOR_DISPATCH', 'View the GL Journal Entries for this Dispatch');
    define('UI_TEXT_INVOICE_THIS_DELIVERY', 'Invoice This Delivery');
    define('UI_TEXT_SELECT_ANOTHER_ORDER_FOR_DISPATCH', 'Select Another Order For Dispatch');
    define('UI_TEXT_ADD_AN_ATTACHMENT', 'Add an Attachment');
    define('UI_TEXT_VIEW_THIS_DELIVERY', '&View This Delivery');
    define('UI_TEXT_CONFIRM_DELIVERY_AND_INVOICE', 'Confirm Delivery and Invoice');
    define('UI_TEXT_SELECT_A_DIFFERENT_DELIVERY', 'Select A Different Delivery');
    define('UI_TEXT_SELECT_DIFFERENT_SALES_ORDER_TO_DELIVERY', 'Select a different sales order to delivery');
    define('UI_TEXT_ORDER_HAS_NO_ITEMS_NOTHING_TO_DELIVERY', 'This order has no items. There is nothing to delivery.');
    define('UI_TEXT_PREPAYMENT_ORDER_NOT_READY', 'This prepayment order is not yet ready for delivery due to insufficient amount received.');
    define('UI_TEXT_SELECT_DIFFERENT_DELIVERY', 'Select a different delivery');
    define('UI_TEXT_DELIVERY_ALL_ITEMS_INVOICED', 'This delivery has all items invoiced. There is nothing to modify.');
    define('UI_TEXT_PAGE_OPEN_IF_ORDER_SELECTED', 'This page can only be opened if an order or delivery note has been selected. Please select it first.');
    define('UI_TEXT_SELECT_SALES_ORDER_TO_DELIVERY', 'Select a Sales Order to Delivery');
    define('UI_TEXT_SELECTED_QUANTITY_LESS_THAN_INVOICED', 'Selected quantity cannot be less than quantity invoiced nor more than quantity not dispatched on sales order.');
    define('UI_TEXT_FREIGHT_COST_CANNOT_BE_LESS_THAN_ZERO', 'Freight cost cannot be less than zero');
    define('UI_TEXT_ENTERED_DATE_OF_DELIVERY_INVALID', 'The entered date of delivery is invalid.');
    define('UI_TEXT_ENTERED_DEADLINE_FOR_INVOICE_INVALID', 'The entered dead-line for invoice is invalid.');
    define('UI_TEXT_NO_ITEM_QUANTITIES_ON_DELIVERY_NOTE', 'There are no item quantities on this delivery note.');
    define('UI_TEXT_INSUFFICIENT_QUANTITY_FOR_ITEMS', 'This document cannot be processed because there is insufficient quantity for items marked.');
    define('UI_TEXT_FOR_SALES_ORDER', 'For Sales Order');
    define('UI_TEXT_DELIVERY_FROM', 'Delivery From');
    define('UI_TEXT_INVOICE_DEADLINE', 'Invoice Dead-line');
    define('UI_TEXT_DELIVERY_ITEMS', 'Delivery Items');
    define('UI_TEXT_ORDERED', 'Ordered');
    define('UI_TEXT_MAX_DELIVERY', 'Max. delivery');
    define('UI_TEXT_DELIVERED', 'Delivered');
    define('UI_TEXT_INVOICED', 'Invoiced');
    define('UI_TEXT_THIS_DELIVERY', 'This Delivery');
    define('UI_TEXT_AMOUNT_TOTAL', 'Amount Total');
    define('UI_TEXT_MARKED_ITEMS_INSUFFICIENT_QUANTITIES', 'Marked items have insufficient quantities in stock as on day of delivery.');
    define('UI_TEXT_ACTION_FOR_BALANCE', 'Action For Balance');
    define('UI_TEXT_PROCESS_DISPATCH', 'Process Dispatch');
    define('UI_TEXT_MODIFYING_CREDIT_INVOICE', 'Modifying Credit Invoice # %d.');
    define('UI_TEXT_CREDIT_NOTE_PROCESSED', 'Credit Note has been processed');
    define('UI_TEXT_VIEW_THIS_CREDIT_NOTE', '&View This Credit Note');
    define('UI_TEXT_PRINT_THIS_CREDIT_NOTE', '&Print This Credit Note');
    define('UI_TEXT_EMAIL_THIS_CREDIT_NOTE', '&Email This Credit Note');
    define('UI_TEXT_VIEW_GL_JOURNAL_ENTRIES_FOR_CREDIT_NOTE', 'View the GL &Journal Entries for this Credit Note');
    define('UI_TEXT_CREDIT_NOTE_UPDATED', 'Credit Note has been updated');
    define('UI_TEXT_ENTERED_SHIPPING_COST_INVALID', 'The entered shipping cost is invalid or less than zero.');
    define('UI_TEXT_SELECTED_QUANTITY_LESS_THAN_ZERO', 'Selected quantity cannot be less than zero nor more than quantity not credited yet.');
    define('UI_TEXT_PAGE_OPEN_IF_INVOICE_SELECTED', 'This page can only be opened if an invoice has been selected for crediting.');
    define('UI_TEXT_CREDITING_INVOICE', 'Crediting Invoice');
    define('UI_TEXT_INVOICE_DATE', 'Invoice Date');
    define('UI_TEXT_CREDIT_NOTE_DATE', 'Credit Note Date');
    define('UI_TEXT_INVOICED_QUANTITY', 'Invoiced Quantity');
    define('UI_TEXT_CREDIT_QUANTITY', 'Credit Quantity');
    define('UI_TEXT_DISCOUNT_PERCENT', 'Discount %');
    define('UI_TEXT_CREDIT_SHIPPING_COST', 'Credit Shipping Cost');
    define('UI_TEXT_CREDIT_NOTE_TOTAL', 'Credit Note Total');
    define('UI_TEXT_CREDIT_NOTE_TYPE', 'Credit Note Type');
    define('UI_TEXT_ITEMS_RETURNED_TO_LOCATION', 'Items Returned to Location');
    define('UI_TEXT_WRITE_OFF_COST_OF_ITEMS_TO', 'Write off the cost of the items to');
    define('UI_TEXT_PROCESS_CREDIT_NOTE', 'Process Credit Note');
    define('UI_TEXT_VIEW_DELIVERY', 'View this delivery');
    define('UI_TEXT_MODIFYING_CUSTOMER_CREDIT_NOTE', 'Modifying Customer Credit Note #%d');
    define('UI_TEXT_NO_ITEMS_DEFINED', 'There are no items defined in the system.');
    define('UI_TEXT_NO_CUSTOMERS_OR_BRANCHES', 'There are no customers, or there are no customers with branches. Please define customers and customer branches.');
    define('UI_TEXT_CREDIT_NOTE_PROCESSED', 'Credit Note # %d has been processed');
    define('UI_TEXT_VIEW_THIS_CREDIT_NOTE', '&View this credit note');
    define('UI_TEXT_PRINT_THIS_CREDIT_INVOICE', '&Print This Credit Invoice');
    define('UI_TEXT_EMAIL_THIS_CREDIT_INVOICE', '&Email This Credit Invoice');
    define('UI_TEXT_VIEW_GL_JOURNAL_ENTRIES_CREDIT_NOTE', 'View the GL &Journal Entries for this Credit Note');
    define('UI_TEXT_ENTER_ANOTHER_CREDIT_NOTE', 'Enter Another &Credit Note');
    define('UI_TEXT_ADD_AN_ATTACHMENT', 'Add an Attachment');
    define('UI_TEXT_NO_CUSTOMER_SELECTED', 'There is no customer selected.');
    define('UI_TEXT_CUSTOMER_NO_BRANCH', 'This customer has no branch defined.');
    define('UI_TEXT_ENTER_AT_LEAST_ONE_ITEM', 'You must enter at least one non empty item line.');
    define('UI_TEXT_ENTER_REFERENCE', 'You must enter a reference.');
    define('UI_TEXT_INVALID_CREDIT_NOTE_DATE', 'The entered date for the credit note is invalid.');
    define('UI_TEXT_DATE_OUT_OF_FISCAL_YEAR', 'The entered date is out of fiscal year or is closed for further data entry.');
    define('UI_TEXT_GL_ACCOUNT_REQUIRED_FOR_WRITE_OFF', 'For credit notes created to write off the stock, a general ledger account is required to be selected.');
    define('UI_TEXT_SELECT_ACCOUNT_FOR_WRITE_OFF', 'Please select an account to write the cost of the stock off to, then click on Process again.');
    define('UI_TEXT_REFERENCE_ALREADY_IN_USE', 'The entered reference is already in use.');
    define('UI_TEXT_QUANTITY_GREATER_THAN_ZERO', 'The quantity must be greater than zero.');
    define('UI_TEXT_INVALID_NEGATIVE_PRICE', 'The entered price is negative or invalid.');
    define('UI_TEXT_CUSTOMER_CREDIT_NOTE', 'Customer Credit Note');
    define('UI_TEXT_INVALID_DISCOUNT_PERCENT', 'The entered discount percent is negative, greater than 100 or invalid.');
    define('UI_TEXT_CREDIT_NOTE_ITEMS', 'Credit Note Items');
    define('UI_TEXT_RECURRENT_INVOICES_CREATED', '%s recurrent invoice(s) created, # %s - # %s.');
    define('UI_TEXT_PRINT_RECURRENT_INVOICES', '&Print Recurrent Invoices # %s - # %s');
    define('UI_TEXT_EMAIL_RECURRENT_INVOICES', '&Email Recurrent Invoices # %s - # %s');
    define('UI_TEXT_RECURRENT_INVOICE_CANNOT_GENERATE_BEFORE_LAST_DAY', 'Recurrent invoice cannot be generated before last day of covered period.');
    define('UI_TEXT_RECURRENT_INVOICES_NO_PRICE_DEFINED', 'Recurrent invoices cannot be generated because some items have no price defined in customer currency.');
    define('UI_TEXT_RECURRENT_INVOICES_PREPAYMENT_TERMS', 'Recurrent invoices cannot be generated because selected sales order template uses prepayment sales terms. Change payment terms and try again.');
    define('UI_TEXT_INVOICE_NOTICE_LABEL', 'Invoice notice:');
    define('UI_TEXT_RECURRENT_INVOICE_COVERS_PERIOD', 'Recurrent Invoice covers period %s - %s.');
    define('UI_TEXT_CONFIRM_ISSUE_INVOICES', 'You are about to issue %s invoices.\n Do you want to continue?');
    define('UI_TEXT_TEMPLATE_NO', 'Template No');
    define('UI_TEXT_CUSTOMER', 'Customer');
    define('UI_TEXT_BRANCH', 'Branch');
    define('UI_TEXT_GROUP', 'Group');
    define('UI_TEXT_DAYS', 'Days');
    define('UI_TEXT_MONTHLY', 'Monthly');
    define('UI_TEXT_BEGIN', 'Begin');
    define('UI_TEXT_END', 'End');
    define('UI_TEXT_NEXT_INVOICE', 'Next invoice');
    define('UI_TEXT_CREATE_INVOICES', 'Create %s Invoice(s)');
    define('UI_TEXT_MARKED_ITEMS_ARE_DUE', 'Marked items are due.');
    define('UI_TEXT_NO_RECURRENT_INVOICES_ARE_DUE', 'No recurrent invoices are due.');
    define('UI_TEXT_ALLOCATION_OF', 'Allocation of %s # %d');
    define('UI_TEXT_DATE_LABEL', 'Date:');
    define('UI_TEXT_TOTAL_LABEL', 'Total:');
    define('UI_TEXT_AMOUNT_TO_BE_SETTLED', 'Amount to be settled:');
    define('UI_TEXT_REFRESH', 'Refresh');
    define('UI_TEXT_START_AGAIN_ALLOCATION', 'Start again allocation of selected amount');
    define('UI_TEXT_PROCESS', 'Process');
    define('UI_TEXT_PROCESS_ALLOCATIONS', 'Process allocations');
    define('UI_TEXT_BACK_TO_ALLOCATIONS', 'Back to Allocations');
    define('UI_TEXT_ABANDON_ALLOCATIONS', 'Abandon allocations and return to selection of allocatable amounts');
    define('UI_TEXT_NO_UNSETTLED_TRANSACTIONS', 'There are no unsettled transactions to allocate.');
    define('UI_TEXT_SHOW_SETTLED_ITEMS', 'Show Settled Items:');
    define('UI_TEXT_ALLOCATE', 'Allocate');
    define('UI_TEXT_TRANSACTION_TYPE', 'Transaction Type');
    define('UI_TEXT_NUMBER', '#');
    define('UI_TEXT_LEFT_TO_ALLOCATE', 'Left to Allocate');
    define('UI_TEXT_MARKED_ITEMS_ARE_SETTLED', 'Marked items are settled.');
    define('UI_TEXT_SEARCH_CUSTOMERS', 'Search customers');
    define('UI_TEXT_SHORT_NAME', 'Short Name');
    define('UI_TEXT_ADDRESS', 'Address');
    define('UI_TEXT_TAX_ID', 'Tax ID');
    define('UI_TEXT_SHOW_SETTLED', 'show settled:');
    define('UI_TEXT_REFRESH_INQUIRY', 'Refresh Inquiry');
    define('UI_TEXT_ALLOCATION', 'Allocation');
    define('UI_TEXT_PAYMENT', 'Payment');
    define('UI_TEXT_ORDER', 'Order');
    define('UI_TEXT_DUE_DATE', 'Due Date');
    define('UI_TEXT_DEBIT', 'Debit');
    define('UI_TEXT_CREDIT', 'Credit');
    define('UI_TEXT_ALLOCATED', 'Allocated');
    define('UI_TEXT_BALANCE', 'Balance');
    define('UI_TEXT_TYPE_LABEL', 'Type:');
    define('UI_TEXT_MARKED_ITEMS_ARE_OVERDUE', 'Marked items are overdue.');
    define('UI_TEXT_SEARCH_BRANCHES', 'Search branches');
    define('UI_TEXT_REF', 'Ref');
    define('UI_TEXT_CONTACT', 'Contact');
    define('UI_TEXT_PHONE', 'Phone');
    define('UI_TEXT_CREDIT_THIS', 'Credit This');
    define('UI_TEXT_COPY_DELIVERY', 'Copy Delivery');
    define('UI_TEXT_COPY_INVOICE', 'Copy Invoice');
    define('UI_TEXT_PRINT_RECEIPT', 'Print Receipt');
    define('UI_TEXT_PRINT', 'Print');
    define('UI_TEXT_CUSTOMER_ACCOUNT_IS_ON_HOLD', 'CUSTOMER ACCOUNT IS ON HOLD');
    define('UI_TEXT_TERMS', 'Terms');
    define('UI_TEXT_CURRENT', 'Current');
    define('UI_TEXT_TOTAL_BALANCE', 'Total Balance');
    define('UI_TEXT_REFERENCE_LABEL', 'Reference:');
    define('UI_TEXT_ENTER_REFERENCE_FRAGMENT', 'Enter reference fragment or leave empty');
    define('UI_TEXT_ZERO_VALUES', 'Zero values');
    define('UI_TEXT_AMOUNT', 'Amount');
    define('UI_TEXT_DELIVERY_NUMBER_LABEL', '#:');
    define('UI_TEXT_LOCATION_LABEL', 'Location:');
    define('UI_TEXT_ITEM_LABEL', 'Item:');
    define('UI_TEXT_SELECT_DOCUMENTS', 'Select documents');
    define('UI_TEXT_DELIVERY_NUMBER', 'Delivery #');
    define('UI_TEXT_CUST_REF', 'Cust Ref');
    define('UI_TEXT_DELIVERY_DATE', 'Delivery Date');
    define('UI_TEXT_DUE_BY', 'Due By');
    define('UI_TEXT_DELIVERY_TOTAL', 'Delivery Total');
    define('UI_TEXT_BATCH', 'Batch');
    define('UI_TEXT_BATCH_INVOICING', 'Batch Invoicing');
    define('UI_TEXT_MARKED_ITEMS_ARE_OVERDUE', 'Marked items are overdue.');
    define('UI_TEXT_PRINT', 'Print');
    define('UI_TEXT_DISPATCH', 'Dispatch');
    define('UI_TEXT_SALES_ORDER', 'Sales Order');
    define('UI_TEXT_INVOICE', 'Invoice');
    define('UI_TEXT_DELIVERY', 'Delivery');
    define('UI_TEXT_PREPAYMENT_INVOICE', 'Prepayment Invoice');
    define('UI_TEXT_FINAL_INVOICE', 'Final Invoice');
    define('UI_TEXT_ORDER_NUMBER_LABEL', '#:');
    define('UI_TEXT_REF', 'Ref');
    define('UI_TEXT_DELIVERY_DATE', 'Delivery date');
    define('UI_TEXT_VALID_UNTIL', 'Valid until');
    define('UI_TEXT_ORDER_DATE', 'Order date');
    define('UI_TEXT_QUOTATION_DATE', 'Quotation date');
    define('UI_TEXT_FROM_LABEL', 'from:');
    define('UI_TEXT_TO_LABEL', 'to:');
    define('UI_TEXT_LOCATION_LABEL', 'Location:');
    define('UI_TEXT_ITEM_LABEL', 'Item:');
    define('UI_TEXT_SELECT_A_CUSTOMER_LABEL', 'Select a customer: ');
    define('UI_TEXT_SHOW_ALL_LABEL', 'Show All:');
    define('UI_TEXT_ZERO_VALUES', 'Zero values');
    define('UI_TEXT_NO_AUTO', 'No auto');
    define('UI_TEXT_SEARCH', 'Search');
    define('UI_TEXT_SELECT_DOCUMENTS', 'Select documents');
    define('UI_TEXT_ORDER_NUMBER', 'Order #');
    define('UI_TEXT_CUST_ORDER_REF', 'Cust Order Ref');
    define('UI_TEXT_REQUIRED_BY', 'Required By');
    define('UI_TEXT_DELIVERY_TO', 'Delivery To');
    define('UI_TEXT_ORDER_TOTAL', 'Order Total');
    define('UI_TEXT_QUOTE_NUMBER', 'Quote #');
    define('UI_TEXT_QUOTE_TOTAL', 'Quote Total');
    define('UI_TEXT_DESCRIPTION', 'Description');
    define('UI_TEXT_NEW_PAYMENTS', 'New Payments');
    define('UI_TEXT_TMPL', 'Tmpl');
    define('UI_TEXT_UPDATE', 'Update');
    define('UI_TEXT_THE_CREDIT_STATUS_DESCRIPTION_CANNOT_BE_EMPTY', 'The credit status description cannot be empty.');
    define('UI_TEXT_CANNOT_DELETE_THIS_CREDIT_STATUS_BECAUSE_CUSTOMER_ACCOUNTS_HAVE_BEEN_CREATED_REFERRING_TO_IT', 'Cannot delete this credit status because customer accounts have been created referring to it.');
    define('UI_TEXT_DISALLOW_INVOICES', 'Dissallow Invoices');
    define('UI_TEXT_INVOICE_OK', 'Invoice OK');
    define('UI_TEXT_NO_INVOICING', 'NO INVOICING');
    define('UI_TEXT_EDIT', 'Edit');
    define('UI_TEXT_DELETE', 'Delete');
    define('UI_TEXT_DESCRIPTION_LABEL', 'Description:');
    define('UI_TEXT_DISALLOW_INVOICING_QUESTION', 'Dissallow invoicing ?');
    define('UI_TEXT_THE_CUSTOMER_NAME_CANNOT_BE_EMPTY', 'The customer name cannot be empty.');
    define('UI_TEXT_THE_CUSTOMER_SHORT_NAME_CANNOT_BE_EMPTY', 'The customer short name cannot be empty.');
    define('UI_TEXT_THE_CREDIT_LIMIT_MUST_BE_NUMERIC_AND_NOT_LESS_THAN_ZERO', 'The credit limit must be numeric and not less than zero.');
    define('UI_TEXT_THE_PAYMENT_DISCOUNT_MUST_BE_NUMERIC_AND_IS_EXPECTED_TO_BE_LESS_THAN_100_PERCENT_AND_GREATER_THAN_OR_EQUAL_TO_0', 'The payment discount must be numeric and is expected to be less than 100% and greater than or equal to 0.');
    define('UI_TEXT_THE_DISCOUNT_PERCENTAGE_MUST_BE_NUMERIC_AND_IS_EXPECTED_TO_BE_LESS_THAN_100_PERCENT_AND_GREATER_THAN_OR_EQUAL_TO_0', 'The discount percentage must be numeric and is expected to be less than 100% and greater than or equal to 0.');
    define('UI_TEXT_CUSTOMER_HAS_BEEN_UPDATED', 'Customer has been updated.');
    define('UI_TEXT_A_NEW_CUSTOMER_HAS_BEEN_ADDED', 'A new customer has been added.');
    define('UI_TEXT_A_DEFAULT_BRANCH_HAS_BEEN_AUTOMATICALLY_CREATED_PLEASE_CHECK_DEFAULT_BRANCH_VALUES_BY_USING_LINK_BELOW', 'A default Branch has been automatically created, please check default Branch values by using link below.');
    define('UI_TEXT_THIS_CUSTOMER_CANNOT_BE_DELETED_BECAUSE_THERE_ARE_TRANSACTIONS_THAT_REFER_TO_IT', 'This customer cannot be deleted because there are transactions that refer to it.');
    define('UI_TEXT_CANNOT_DELETE_THE_CUSTOMER_RECORD_BECAUSE_ORDERS_HAVE_BEEN_CREATED_AGAINST_IT', 'Cannot delete the customer record because orders have been created against it.');
    define('UI_TEXT_CANNOT_DELETE_THIS_CUSTOMER_BECAUSE_THERE_ARE_BRANCH_RECORDS_SET_UP_AGAINST_IT', 'Cannot delete this customer because there are branch records set up against it.');
    define('UI_TEXT_SELECTED_CUSTOMER_HAS_BEEN_DELETED', 'Selected customer has been deleted.');
    define('UI_TEXT_NAME_AND_ADDRESS', 'Name and Address');
    define('UI_TEXT_CUSTOMER_NAME_LABEL', 'Customer Name:');
    define('UI_TEXT_CUSTOMER_SHORT_NAME_LABEL', 'Customer Short Name:');
    define('UI_TEXT_ADDRESS_LABEL', 'Address:');
    define('UI_TEXT_GSTNO_LABEL', 'GSTNo:');
    define('UI_TEXT_CUSTOMERS_CURRENCY_LABEL', 'Customer\'s Currency:');
    define('UI_TEXT_SALES_TYPE_PRICE_LIST_LABEL', 'Sales Type/Price List:');
    define('UI_TEXT_CUSTOMER_STATUS_LABEL', 'Customer status:');
    define('UI_TEXT_BRANCH', 'Branch');
    define('UI_TEXT_PHONE_LABEL', 'Phone:');
    define('UI_TEXT_SECONDARY_PHONE_NUMBER_LABEL', 'Secondary Phone Number:');
    define('UI_TEXT_FAX_NUMBER_LABEL', 'Fax Number:');
    define('UI_TEXT_E_MAIL_LABEL', 'E-mail:');
    define('UI_TEXT_BANK_ACCOUNT_NUMBER_LABEL', 'Bank Account Number:');
    define('UI_TEXT_SALES_PERSON_LABEL', 'Sales Person:');
    define('UI_TEXT_SALES', 'Sales');
    define('UI_TEXT_DISCOUNT_PERCENT_LABEL', 'Discount Percent:');
    define('UI_TEXT_PROMPT_PAYMENT_DISCOUNT_PERCENT_LABEL', 'Prompt Payment Discount Percent:');
    define('UI_TEXT_CREDIT_LIMIT_LABEL', 'Credit Limit:');
    define('UI_TEXT_CREDIT_STATUS_LABEL', 'Credit Status:');
    define('UI_TEXT_SELECT_OR_ADD', 'Select or &Add');
    define('UI_TEXT_ADD_OR_EDIT', '&Add or Edit ');
    define('UI_TEXT_GENERAL_NOTES_LABEL', 'General Notes:');
    define('UI_TEXT_DEFAULT_INVENTORY_LOCATION_LABEL', 'Default Inventory Location:');
    define('UI_TEXT_DEFAULT_SHIPPING_COMPANY_LABEL', 'Default Shipping Company:');
    define('UI_TEXT_PAYMENT_TERMS_LABEL', 'Payment Terms:');
    define('UI_TEXT_CREDIT_STATUS_LABEL', 'Credit Status:');
    define('UI_TEXT_SALES_AREA_LABEL', 'Sales Area:');
    define('UI_TEXT_TAX_GROUP_LABEL', 'Tax Group:');
    define('UI_TEXT_ADD_NEW_CUSTOMER', 'Add New Customer');
    define('UI_TEXT_UPDATE_CUSTOMER', 'Update Customer');
    define('UI_TEXT_SELECT_THIS_CUSTOMER_AND_RETURN_TO_DOCUMENT_ENTRY', 'Select this customer and return to document entry.');
    define('UI_TEXT_DELETE_CUSTOMER', 'Delete Customer');
    define('UI_TEXT_THERE_ARE_NO_SALES_TYPES_DEFINED_PLEASE_DEFINE_AT_LEAST_ONE_SALES_TYPE_BEFORE_ADDING_A_CUSTOMER', 'There are no sales types defined. Please define at least one sales type before adding a customer.');
    define('UI_TEXT_SHOW_INACTIVE_LABEL', 'Show inactive:');
    define('UI_TEXT_THERE_ARE_NO_CUSTOMERS_DEFINED_IN_THE_SYSTEM_PLEASE_DEFINE_A_CUSTOMER_TO_ADD_CUSTOMER_BRANCHES', 'There are no customers defined in the system. Please define a customer to add customer branches.');
    define('UI_TEXT_THERE_ARE_NO_SALES_PEOPLE_DEFINED_IN_THE_SYSTEM_AT_LEAST_ONE_SALES_PERSON_IS_REQUIRED_BEFORE_PROCEEDING', 'There are no sales people defined in the system. At least one sales person is required before proceeding.');
    define('UI_TEXT_THERE_ARE_NO_SALES_AREAS_DEFINED_IN_THE_SYSTEM_AT_LEAST_ONE_SALES_AREA_IS_REQUIRED_BEFORE_PROCEEDING', 'There are no sales areas defined in the system. At least one sales area is required before proceeding.');
    define('UI_TEXT_THERE_ARE_NO_SHIPPING_COMPANIES_DEFINED_IN_THE_SYSTEM_AT_LEAST_ONE_SHIPPING_COMPANY_IS_REQUIRED_BEFORE_PROCEEDING', 'There are no shipping companies defined in the system. At least one shipping company is required before proceeding.');
    define('UI_TEXT_THERE_ARE_NO_TAX_GROUPS_DEFINED_IN_THE_SYSTEM_AT_LEAST_ONE_TAX_GROUP_IS_REQUIRED_BEFORE_PROCEEDING', 'There are no tax groups defined in the system. At least one tax group is required before proceeding.');
    define('UI_TEXT_THE_BRANCH_NAME_CANNOT_BE_EMPTY', 'The Branch name cannot be empty.');
    define('UI_TEXT_THE_BRANCH_SHORT_NAME_CANNOT_BE_EMPTY', 'The Branch short name cannot be empty.');
    define('UI_TEXT_CANNOT_DELETE_THIS_BRANCH_BECAUSE_CUSTOMER_TRANSACTIONS_HAVE_BEEN_CREATED_TO_THIS_BRANCH', 'Cannot delete this branch because customer transactions have been created to this branch.');
    define('UI_TEXT_CANNOT_DELETE_THIS_BRANCH_BECAUSE_SALES_ORDERS_EXIST_FOR_IT_PURGE_OLD_SALES_ORDERS_FIRST', 'Cannot delete this branch because sales orders exist for it. Purge old sales orders first.');
    define('UI_TEXT_NAME_AND_CONTACT', 'Name and Contact');
    define('UI_TEXT_BRANCH_NAME_LABEL', 'Branch Name:');
    define('UI_TEXT_BRANCH_SHORT_NAME_LABEL', 'Branch Short Name:');
    define('UI_TEXT_SALES_GROUP_LABEL', 'Sales Group:');
    define('UI_TEXT_GL_ACCOUNTS', 'GL Accounts');
    define('UI_TEXT_SALES_ACCOUNT_LABEL', 'Sales Account:');
    define('UI_TEXT_SALES_DISCOUNT_ACCOUNT_LABEL', 'Sales Discount Account:');
    define('UI_TEXT_ACCOUNTS_RECEIVABLE_ACCOUNT_LABEL', 'Accounts Receivable Account:');
    define('UI_TEXT_PROMPT_PAYMENT_DISCOUNT_ACCOUNT_LABEL', 'Prompt Payment Discount Account:');
    define('UI_TEXT_GENERAL_CONTACT_DATA', 'General contact data');
    define('UI_TEXT_CONTACT_PERSON_LABEL', 'Contact Person:');
    define('UI_TEXT_PHONE_NUMBER_LABEL', 'Phone Number:');
    define('UI_TEXT_DOCUMENT_LANGUAGE_LABEL', 'Document Language:');
    define('UI_TEXT_CUSTOMER_DEFAULT', 'Customer default');
    define('UI_TEXT_ADDRESSES', 'Addresses');
    define('UI_TEXT_MAILING_ADDRESS_LABEL', 'Mailing Address:');
    define('UI_TEXT_BILLING_ADDRESS_LABEL', 'Billing Address:');
    define('UI_TEXT_SHORT_NAME', 'Short Name');
    define('UI_TEXT_NAME', 'Name');
    define('UI_TEXT_BANK_ACCOUNT_NUMBER_LABEL', 'Bank Account Number:');
    define('UI_TEXT_SECONDARY_PHONE_NUMBER_LABEL', 'Secondary Phone Number:');
    define('UI_TEXT_FAX_NUMBER_LABEL', 'Fax Number:');
    define('UI_TEXT_EMAIL_LABEL', 'E-mail:');
    define('UI_TEXT_GENERAL_NOTES_LABEL', 'General Notes:');
    define('UI_TEXT_SELECT_A_CUSTOMER_LABEL', 'Select a customer: ');
    define('UI_TEXT_CONTACT', 'Contact');
    define('UI_TEXT_SALES_PERSON', 'Sales Person');
    define('UI_TEXT_AREA', 'Area');
    define('UI_TEXT_PHONE_NO', 'Phone No');
    define('UI_TEXT_FAX_NO', 'Fax No');
    define('UI_TEXT_EMAIL', 'E-mail');
    define('UI_TEXT_TAX_GROUP', 'Tax Group');
    define('UI_TEXT_INACTIVE', 'Inactive');
    define('UI_TEXT_THE_SELECTED_CUSTOMER_DOES_NOT_HAVE_ANY_BRANCHES_PLEASE_CREATE_AT_LEAST_ONE_BRANCH', 'The selected customer does not have any branches. Please create at least one branch.');
    define('UI_TEXT_GENERAL_SETTINGS', '&General settings');
    define('UI_TEXT_CONTACTS', '&Contacts');
    define('UI_TEXT_THERE_IS_NO_TEMPLATE_ORDER_IN_DATABASE_YOU_HAVE_TO_CREATE_AT_LEAST_ONE_SALES_ORDER_MARKED_AS_TEMPLATE_TO_BE_ABLE_TO_DEFINE_RECURRENT_INVOICES', 'There is no template order in database.
	You have to create at least one sales order marked as template to be able to define recurrent invoices.');
    define('UI_TEXT_THIS_CUSTOMER_HAS_NO_BRANCHES_PLEASE_DEFINE_AT_LEAST_ONE_BRANCH_FOR_THIS_CUSTOMER_FIRST', 'This customer has no branches. Please define at least one branch for this customer first.');
    define('UI_TEXT_THERE_ARE_NO_TAX_GROUPS_DEFINED_IN_THE_SYSTEM_AT_LEAST_ONE_TAX_GROUP_IS_REQUIRED_BEFORE_PROCEEDING', 'There are no tax groups defined in the system. At least one tax group is required before proceeding.');
    define('UI_TEXT_THE_INVOICE_DESCRIPTION_CANNOT_BE_EMPTY', 'The invoice description cannot be empty.');
    define('UI_TEXT_THIS_RECURRENT_INVOICE_DESCRIPTION_IS_ALREADY_IN_USE', 'This recurrent invoice description is already in use.');
    define('UI_TEXT_THE_ENTERED_DATE_IS_INVALID', 'The entered date is invalid.');
    define('UI_TEXT_NO_RECURENCE_INTERVAL_HAS_BEEN_ENTERED', 'No recurence interval has been entered.');
    define('UI_TEXT_DESCRIPTION', 'Description');
    define('UI_TEXT_TEMPLATE_NO', 'Template No');
    define('UI_TEXT_CUSTOMER', 'Customer');
    define('UI_TEXT_BRANCH', 'Branch');
    define('UI_TEXT_GROUP', 'Group');
    define('UI_TEXT_DAYS', 'Days');
    define('UI_TEXT_MONTHLY', 'Monthly');
    define('UI_TEXT_BEGIN', 'Begin');
    define('UI_TEXT_END', 'End');
    define('UI_TEXT_LAST_CREATED', 'Last Created');
    define('UI_TEXT_DESCRIPTION_LABEL', 'Description:');
    define('UI_TEXT_TEMPLATE_LABEL', 'Template:');
    define('UI_TEXT_CUSTOMER_LABEL', 'Customer:');
    define('UI_TEXT_BRANCH_LABEL', 'Branch:');
    define('UI_TEXT_SALES_GROUP_LABEL', 'Sales Group:');
    define('UI_TEXT_DAYS_LABEL', 'Days:');
    define('UI_TEXT_MONTHLY_LABEL', 'Monthly:');
    define('UI_TEXT_BEGIN_LABEL', 'Begin:');
    define('UI_TEXT_END_LABEL', 'End:');
    define('UI_TEXT_LAST_CREATED_LABEL', 'Last Created');
};
