<?php
/**
 * UI string constants for multilingual readiness.
 */

if (!defined('UI_TEXT_GL_INQUIRY_TITLE')) {
    define('UI_TEXT_GL_INQUIRY_TITLE', 'General Ledger Inquiry');
    define('UI_TEXT_ACCOUNT_LABEL', 'Account:');
    define('UI_TEXT_ALL_ACCOUNTS', 'All Accounts');
    define('UI_TEXT_FROM_LABEL', 'from:');
    define('UI_TEXT_TO_LABEL', 'to:');
    define('UI_TEXT_DIMENSION', 'Dimension');
    define('UI_TEXT_MEMO_PLACEHOLDER', 'Enter memo fragment or leave empty');
    define('UI_TEXT_AMOUNT_MIN', 'Amount min:');
    define('UI_TEXT_AMOUNT_MAX', 'Amount max:');
    define('UI_TEXT_SHOW', 'Show');
    define('UI_TEXT_TYPE', 'Type');
    define('UI_TEXT_NUMBER', '#');
    define('UI_TEXT_REFERENCE', 'Reference');
    define('UI_TEXT_DATE', 'Date');
    define('UI_TEXT_ACCOUNT_COLUMN', 'Account');
    define('UI_TEXT_PERSON_ITEM', 'Person/Item');
    define('UI_TEXT_DEBIT', 'Debit');
    define('UI_TEXT_CREDIT', 'Credit');
    define('UI_TEXT_BALANCE', 'Balance');
    define('UI_TEXT_MEMO', 'Memo');
    define('UI_TEXT_OPENING_BALANCE', 'Opening Balance');
    define('UI_TEXT_ENDING_BALANCE', 'Ending Balance');
    define('UI_TEXT_WARNING_OPENING_MISMATCH', 'The Opening Balance is not in balance, probably due to a non closed Previous Fiscalyear.');
    define('UI_TEXT_GL_LABEL', 'GL');
    define('UI_TEXT_SELECT', 'Select');
    define('UI_TEXT_VOID_TRANSACTION_TITLE', 'Void a Transaction');
    define('UI_TEXT_TRANSACTION_TYPE_LABEL', 'Transaction Type:');
    define('UI_TEXT_SEARCH', 'Search');
    define('UI_TEXT_MARKED_WILL_BE_VOIDED', 'Marked transactions will be voided.');
    define('UI_TEXT_TRANSACTION_NUMBER', 'Transaction #:');
    define('UI_TEXT_VOIDING_DATE', 'Voiding Date:');
    define('UI_TEXT_MEMO_LABEL', 'Memo:');
    define('UI_TEXT_VOID_TRANSACTION_BUTTON', 'Void Transaction');
    define('UI_TEXT_ENTERED_TRANSACTION_NOT_FOUND', 'The entered transaction does not exist or cannot be voided.');
    define('UI_TEXT_INSUFFICIENT_QUANTITY_WARNING', 'The void cannot be processed because there is an insufficient quantity for item:');
    define('UI_TEXT_QUANTITY_ON_HAND', 'Quantity On Hand');
    define('UI_TEXT_VOID_CONFIRMATION', 'Are you sure you want to void this transaction ? This action cannot be undone.');
    define('UI_TEXT_VOID_PROCEED', 'Proceed');
    define('UI_TEXT_CANCEL', 'Cancel');
    define('UI_TEXT_CLOSED_TRANSACTION_ERROR', 'The selected transaction was closed for edition and cannot be voided.');
    define('UI_TEXT_INVALID_DATE_ERROR', 'The entered date is invalid.');
    define('UI_TEXT_DATE_OUT_OF_FISCAL_YEAR_ERROR', 'The entered date is out of fiscal year or is closed for further data entry.');
    define('UI_TEXT_NUMERIC_TRANSACTION_NUMBER_ERROR', 'The transaction number is expected to be numeric and greater than zero.');
    define('UI_TEXT_ALREADY_VOIDED_ERROR', 'The selected transaction has already been voided.');
    define('UI_TEXT_TRANSACTION_VOIDED_NOTICE', 'Selected transaction has been voided.');
    define('UI_TEXT_REFERENCE_COLUMN', 'Reference');
    define('UI_TEXT_DATE_COLUMN', 'Date');
    define('UI_TEXT_NUMBER_COLUMN', '#');
    define('UI_TEXT_NA', 'N/A');
    define('UI_TEXT_PRINT', 'Print');
    define('UI_TEXT_ONLY_DOCUMENTS_PRINTABLE', 'Only documents can be printed.');
    define('UI_TEXT_TYPE_LABEL', 'Type:');
    define('UI_TEXT_FROM_NUMBER', 'from #:');
    define('UI_TEXT_TO_NUMBER', 'to #:');
    define('UI_TEXT_START_TRANS_NUMERIC_ERROR', 'The starting transaction number is expected to be numeric and greater than zero.');
    define('UI_TEXT_END_TRANS_NUMERIC_ERROR', 'The ending transaction number is expected to be numeric and greater than zero.');
    define('UI_TEXT_VIEW_PRINT_TRANSACTIONS_TITLE', 'View or Print Transactions');
    define('UI_TEXT_UNSPECIFIED_TAG_TYPE', 'Unspecified tag type');
    define('UI_TEXT_TAG_NAME_EMPTY_ERROR', 'The tag name cannot be empty.');
    define('UI_TEXT_CANNOT_DELETE_TAG_ERROR', 'Cannot delete this tag because records have been created referring to it.');
    define('UI_TEXT_TAG_NAME', 'Tag Name');
    define('UI_TEXT_TAG_DESCRIPTION', 'Tag Description');
    define('UI_TEXT_EDIT', 'Edit');
    define('UI_TEXT_DELETE', 'Delete');
    define('UI_TEXT_ACCOUNT_TAGS_TITLE', 'Account Tags');
    define('UI_TEXT_DIMENSION_TAGS_TITLE', 'Dimension Tags');
    define('UI_TEXT_TAG_NAME_LABEL', 'Tag Name:');
    define('UI_TEXT_TAG_DESCRIPTION_LABEL', 'Tag Description:');
    define('UI_TEXT_USERS_TITLE', 'Users');
    define('UI_TEXT_USER_LOGIN_TOO_SHORT_ERROR', 'The user login entered must be at least 4 characters long.');
    define('UI_TEXT_PASSWORD_TOO_SHORT_ERROR', 'The password entered must be at least 4 characters long.');
    define('UI_TEXT_PASSWORD_CONTAINS_LOGIN_ERROR', 'The password cannot contain the user login.');
    define('UI_TEXT_USER_UPDATED_NOTICE', 'The selected user has been updated.');
    define('UI_TEXT_USER_ADDED_NOTICE', 'A new user has been added.');
    define('UI_TEXT_CANNOT_DELETE_USER_ERROR', 'Cannot delete this user because entries are associated with this user.');
    define('UI_TEXT_USER_DELETED_NOTICE', 'User has been deleted.');
    define('UI_TEXT_USER_LOGIN', 'User login');
    define('UI_TEXT_FULL_NAME', 'Full Name');
    define('UI_TEXT_PHONE', 'Phone');
    define('UI_TEXT_EMAIL', 'E-mail');
    define('UI_TEXT_LAST_VISIT', 'Last Visit');
    define('UI_TEXT_ACCESS_LEVEL', 'Access Level');
    define('UI_TEXT_USER_LOGIN_LABEL', 'User login:');
    define('UI_TEXT_PASSWORD_LABEL', 'Password:');
    define('UI_TEXT_ENTER_NEW_PASSWORD_INSTRUCTION', 'Enter a new password to change, leave empty to keep current.');
    define('UI_TEXT_TELEPHONE_LABEL', 'Telephone No.:');
    define('UI_TEXT_EMAIL_ADDRESS_LABEL', 'Email Address:');
    define('UI_TEXT_LANGUAGE_LABEL', 'Language:');
    define('UI_TEXT_USERS_POS_LABEL', "User's POS:");
    define('UI_TEXT_PRINTING_PROFILE_LABEL', 'Printing profile:');
    define('UI_TEXT_USE_POPUP_WINDOW_LABEL', 'Use popup window for reports:');
    define('UI_TEXT_BROWSER_PRINTING_SUPPORT', 'Browser printing support');
    define('UI_TEXT_POPUP_WINDOW_INSTRUCTION', 'Set this option to on if your browser directly supports pdf files');
}
